-- Migration 062 — Geofencing: radius field in RRL_ADDR
-- Sprint 118 | 2026-05-29

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RABAEV.RRL_ADDR ADD GEO_FENCE_RADIUS_M NUMBER(5) DEFAULT 200';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Update all existing addresses to default 200m radius
UPDATE RABAEV.RRL_ADDR SET GEO_FENCE_RADIUS_M = 200 WHERE GEO_FENCE_RADIUS_M IS NULL;
COMMIT;
/
