select STATE,BASELINE_ID from RRL_STOCK_RELEASE where RELEASE_ID=1;
select TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH from user_tab_columns where
 (TABLE_NAME='RRL_REMAINS' and COLUMN_NAME in('CELL','HARD_RESERVED_BASE','STOCK_VERSION','BASE_UOM'))
 or (TABLE_NAME='RRL_EVENTS' and COLUMN_NAME in('OPERATION_ID','BASE_QTY','CELL_FROM','CELL_TO'));
select CONSTRAINT_NAME,STATUS,VALIDATED from user_constraints where CONSTRAINT_NAME in('RRL_REMAINS_HARD_CK','RRL_EVENTS_OPERATION_UK');
select count(*) NEW_OPERATIONS from RRL_STOCK_OPERATION;