select OBJECT_NAME,OBJECT_TYPE,STATUS from user_objects
where OBJECT_NAME like 'RRL_STOCK_%' order by OBJECT_NAME,OBJECT_TYPE;
select NAME,TYPE,LINE,POSITION,TEXT from user_errors where NAME like 'RRL_STOCK_%' order by NAME,TYPE,SEQUENCE;
select STATE,BASELINE_ID from RRL_STOCK_RELEASE where RELEASE_ID=1;
select count(*) POSTED_OPERATIONS from RRL_STOCK_OPERATION;
select count(*) UNCONVERTED_WRITERS from RRL_STOCK_WRITER_REGISTRY where STATE='UNCONVERTED';
