select OBJECT_NAME,OBJECT_TYPE,STATUS from USER_OBJECTS
where OBJECT_NAME in ('RRL_STOCK_PALLET_UOM','RRL_STOCK_TASK_PLAN','RRL_STOCK_TASK_CORE');
select NAME,TYPE,LINE,TEXT from USER_ERRORS
where NAME in ('RRL_STOCK_PALLET_UOM','RRL_STOCK_TASK_PLAN','RRL_STOCK_TASK_CORE');
