select NAME,TYPE,LINE,TEXT from USER_ERRORS where NAME in('RRL_STOCK_INTERNAL_CMD','RRL_STOCK_NATIVE_API','RRL_STOCK_POSTING_API','RRL_STOCK_JOURNAL_GUARD');
select STATE,BASELINE_ID from RRL_STOCK_RELEASE where RELEASE_ID=1;
