select OBJECT_NAME,STATUS from USER_OBJECTS where OBJECT_NAME in('RRL_INTERNAL_MOVE2','RRL_INTERNAL_MOVE3','RRL_INTERNAL_MOVE2_SP_OLD','RRL_INTERNAL_MOVE3_SP_OLD');
select NAME,LINE,TEXT from USER_ERRORS where NAME in('RRL_INTERNAL_MOVE2','RRL_INTERNAL_MOVE3','RRL_INTERNAL_MOVE2_SP_OLD','RRL_INTERNAL_MOVE3_SP_OLD');
