select NAME,TYPE,LINE,TEXT from USER_ERRORS where NAME in('RRL_STOCK_BALANCE_CORE','RRL_STOCK_EFFECT_CORE','RRL_STOCK_SHIPPING_CORE','RRL_STOCK_POSTING_API');
select STATE from RRL_STOCK_RELEASE where RELEASE_ID=1;
