select OBJECT_NAME,OBJECT_TYPE,STATUS from USER_OBJECTS
 where OBJECT_NAME in('RRL_STOCK_SHIPPING_CORE','RRL_STOCK_CASE_PICK_CMD','RRL_STOCK_CASE_MOVE_CMD');
select NAME,TYPE,LINE,TEXT from USER_ERRORS
 where NAME in('RRL_STOCK_SHIPPING_CORE','RRL_STOCK_CASE_PICK_CMD','RRL_STOCK_CASE_MOVE_CMD');
select CONSTRAINT_NAME,STATUS,VALIDATED from USER_CONSTRAINTS where CONSTRAINT_NAME='RRL_CASE_SHIPMENT_UK';
select MIGRATION_ID,STATUS from RRL_SCHEMA_MIGRATIONS where MIGRATION_ID='2026-10-09-001-case-existing-st-shipment';
