select STATE,BASELINE_ID from RRL_STOCK_RELEASE where RELEASE_ID=1;
select SETTING_VALUE from RRL_SYSTEM_SETTINGS where SETTING_KEY='STOCK_LEGACY_TRIGGER_ENABLED';
select STATE,count(*) from RRL_STOCK_WRITER_REGISTRY group by STATE;
select OBJECT_NAME,OBJECT_TYPE from USER_OBJECTS where OBJECT_NAME like 'RRL_STOCK_%' and STATUS!='VALID' and OBJECT_NAME not like '%_OLD';
select nvl(sum(REMAIN),0) PHYSICAL,nvl(sum(HARD_RESERVED_BASE),0) HARD from RRL_REMAINS;
select MIGRATION_ID,STATUS from RRL_SCHEMA_MIGRATIONS where MIGRATION_ID like '2026-10-09-%' order by MIGRATION_ID;
