DROP TABLE RABAEV.RRL_TT_LOAD_TASK CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TT_LOAD_TASK
(
  TT_ID      INTEGER,
  DOCK       VARCHAR2(50 BYTE),
  LOAD_FROM  DATE,
  LOAD_TO    DATE,
  WARE_ID    INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


