-- Installation metadata only, no warehouse/business tests.
select OBJECT_NAME,OBJECT_TYPE,STATUS from USER_OBJECTS
 where OBJECT_NAME in('RRL_SKU_RECEIPT_POLICY','RRL_SKU_RECEIPT_PROFILE','RRL_SKU_RECEIPT_POLICY_LOG','RRL_SAP_IDOC_INBOX');
select MIGRATION_ID,STATUS,APPLIED_AT from RRL_SCHEMA_MIGRATIONS where MIGRATION_ID='2026-10-07-001-ni01-sap-retail';