
--RRL_SBORKA_PALLET_ROWS.*

select
ARTICUL ,
sum( QUANTITY ) , 
count( QUANTITY )

 from 
RRL_SBORKA_PALLET_ROWS ,
RRL_SBORKA_PALLETS

  where 
  RRL_SBORKA_PALLETS.PALLET_UID = RRL_SBORKA_PALLET_ROWS.PALLET_UID
  
  and RRL_SBORKA_PALLETS.STDATE  > to_date( '01.05.2010' )
  and RRL_SBORKA_PALLETS.STDATE  < to_date( '01.06.2010' )
  

  
  group by ARTICUL