

  select RE.CELL , PAL.ARTICUL ,  PAL.UNIT_COUNT*PAL.PRICE from RRL_REMAINS RE , RRL_CELLS  CE , RRL_PALLETS PAL
  where RE.CELL=CE.CELL and CE.WARE_ID=1 and RE.UID_POLETA=PAL.UID_PALLET
  and CE.OTBOR=0 and CE.BLOCKED_FOR_REMAINS=0


