SET DEFINE OFF;
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('10πετ', 1, 11, 10000, 4);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('15πετ', 1, 16, 15000, 3);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('10', 0, 11, 10000, 2);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('15', 0, 16, 15000, 1);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('5', 0, 9, 5000, 5);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('5πετ', 1, 9, 5000, 6);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('20', 0, 31, 20, 8);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('20πετ', 1, 31, 20, 7);
Insert into RABAEV.RRL_TRANSPORT_TYPE
   (TRANSPORTTYPE, REF, NORMA_PALLET, NORMA_WEIGHT, ORD)
 Values
   ('νες', 0, 0, 0, 200);
COMMIT;
