-- Migration 042 — Verify
SELECT 'RRL_V_AVAILABLE_STS',
       CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'MISSING' END
  FROM user_views WHERE view_name = 'RRL_V_AVAILABLE_STS'
UNION ALL
SELECT 'IDX_SP_TRANSTASK',
       CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'MISSING' END
  FROM user_indexes WHERE index_name = 'IDX_SP_TRANSTASK'
UNION ALL
SELECT 'IDX_SP_STDATE',
       CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'MISSING' END
  FROM user_indexes WHERE index_name = 'IDX_SP_STDATE'
UNION ALL
SELECT 'IDX_TT_SHIPDATE',
       CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'MISSING' END
  FROM user_indexes WHERE index_name = 'IDX_TT_SHIPDATE';
