-- Migration 042 — Rollback
BEGIN EXECUTE IMMEDIATE 'DROP VIEW RABAEV.RRL_V_AVAILABLE_STS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX RABAEV.IDX_SP_TRANSTASK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX RABAEV.IDX_SP_STDATE';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX RABAEV.IDX_TT_SHIPDATE';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;
