-- Rollback 055 — Fleet CRUD: Транспортные средства
DROP FUNCTION RABAEV.RRL_TR_VEHICLE_ADD;
DROP PROCEDURE RABAEV.RRL_TR_VEHICLE_UPDATE;
DROP PROCEDURE RABAEV.RRL_TR_VEHICLE_DEL;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE RABAEV.SEQ_TR_VEHICLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
