-- Rollback 056
DROP FUNCTION RABAEV.RRL_TR_VODITEL_ADD;
DROP PROCEDURE RABAEV.RRL_TR_VODITEL_UPDATE;
DROP PROCEDURE RABAEV.RRL_TR_VODITEL_DEL;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE RABAEV.SEQ_TR_VODITEL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
