"""Application contracts for atomic receiving commands and read models."""
from typing import Protocol


class ReceivingPort(Protocol):
    def receive(self, order_id: str, payload: dict, actor: str) -> dict: ...
    def complete(self, task_id: int, scans: dict, actor: str) -> dict: ...
    def replan(self, task_id: int, body: dict, actor: str) -> dict: ...
    def cancel(self, task_id: int, reason: str, actor: str) -> dict: ...


class LabelPort(Protocol):
    def issue(self, order_id: str, payload: dict, actor: str) -> dict: ...
    def document(self, label_id: str, format: str, dpi: int = 203) -> str: ...
    def confirm(self, label_id: str, scan: str, actor: str) -> dict: ...


class ConfigurationPort(Protocol):
    def get(self, warehouse: int) -> dict: ...
    def read_rule(self, warehouse: int, key: str, kind: str) -> dict: ...
    def save(self, warehouse: int, body: dict, actor: str) -> dict: ...
    def sku_rule(self, warehouse: int, articul: str, body: dict, actor: str = "API") -> dict: ...
    def cell_rule(self, warehouse: int, cell: str, body: dict, actor: str) -> dict: ...


class ReconciliationPort(Protocol):
    def close(self, order_id: str, operation: str, reason: str, actor: str) -> dict: ...
    def reopen(self, order_id: str, operation: str, reason: str, actor: str) -> dict: ...


class QueriesPort(Protocol):
    def composition(self, pallet: str, after: str = '', limit: int = 50) -> dict: ...
