DROP INDEX RABAEV.ART;

CREATE INDEX RABAEV.ART ON RABAEV.RRL_ARTICUL_MODS
(ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.LOT_AUDIT_ERROR_LINES_PK;

CREATE INDEX RABAEV.LOT_AUDIT_ERROR_LINES_PK ON RABAEV.LOT_AUDIT_ERROR_LINES
(SSCC)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.LOT_AUDIT_PK;

CREATE UNIQUE INDEX RABAEV.LOT_AUDIT_PK ON RABAEV.LOT_AUDIT
(SSCC)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.ORDER_AUDIT_LINES_PK;

CREATE UNIQUE INDEX RABAEV.ORDER_AUDIT_LINES_PK ON RABAEV.ORDER_AUDIT_ERROR_LINES
(ORDER_NUMBER, UID1)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.ORDER_AUDIT_PK;

CREATE UNIQUE INDEX RABAEV.ORDER_AUDIT_PK ON RABAEV.ORDER_AUDIT
(ORDER_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.ORDER_MOV_HIST_PK;

CREATE UNIQUE INDEX RABAEV.ORDER_MOV_HIST_PK ON RABAEV.ORDER_MOV_HIST
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.PALLET_MULTIPLE_I;

CREATE INDEX RABAEV.PALLET_MULTIPLE_I ON RABAEV.RRL_ARTICULS
(PALLET_MULTIPLE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.PALLET_ROW_ID_I8;

CREATE INDEX RABAEV.PALLET_ROW_ID_I8 ON RABAEV.RRL_EVENTS
(PALLET_ROW_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RIGHTS_PK;

CREATE UNIQUE INDEX RABAEV.RIGHTS_PK ON RABAEV.RIGHTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_ADDR_I33;

CREATE INDEX RABAEV.RRL_ADDR_I33 ON RABAEV.RRL_ADDR
(NAPR, RAION, REGION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_ADDR_PK;

CREATE UNIQUE INDEX RABAEV.RRL_ADDR_PK ON RABAEV.RRL_ADDR
(ADDR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_ARTICULS_BARCODE_SHT;

CREATE INDEX RABAEV.RRL_ARTICULS_BARCODE_SHT ON RABAEV.RRL_ARTICULS
(BARCODE_SHT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_ARTICULS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_ARTICULS_PK ON RABAEV.RRL_ARTICULS
(ACTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_ARTICUL_MODS_ID;

CREATE UNIQUE INDEX RABAEV.RRL_ARTICUL_MODS_ID ON RABAEV.RRL_ARTICUL_MODS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_BILLING_I1;

CREATE INDEX RABAEV.RRL_BILLING_I1 ON RABAEV.RRL_BILLING
(USER_ID, TIMEOF, OPERATION, PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_BILLING_PK;

CREATE UNIQUE INDEX RABAEV.RRL_BILLING_PK ON RABAEV.RRL_BILLING
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_BILL_COMPANY_PK;

CREATE UNIQUE INDEX RABAEV.RRL_BILL_COMPANY_PK ON RABAEV.RRL_BILL_COMPANY
(COMPANYNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_BILL_ORDERS_I4;

CREATE INDEX RABAEV.RRL_BILL_ORDERS_I4 ON RABAEV.RRL_BILL_ORDERS
(NUM, COMPANY, DATEOFORDER, DATEFROM, DATETO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_BILL_ORDERS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_BILL_ORDERS_PK ON RABAEV.RRL_BILL_ORDERS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_CELLS_EXP;

CREATE INDEX RABAEV.RRL_CELLS_EXP ON RABAEV.RRL_CELLS
(EXPEDITION_GROUP)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_CELLS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_CELLS_PK ON RABAEV.RRL_CELLS
(CELL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_CELLS_WARE_ID;

CREATE INDEX RABAEV.RRL_CELLS_WARE_ID ON RABAEV.RRL_CELLS
(WARE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_EVENTS_DATE_EVENT;

CREATE INDEX RABAEV.RRL_EVENTS_DATE_EVENT ON RABAEV.RRL_EVENTS
(DATE_EVENT, UID_POLETA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_EVENTS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_EVENTS_PK ON RABAEV.RRL_EVENTS
(ID_EVENT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_HISTORY_NOTES_PK;

CREATE UNIQUE INDEX RABAEV.RRL_HISTORY_NOTES_PK ON RABAEV.RRL_HISTORY_NOTES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_INVENTARIZ_LINES_PK;

CREATE UNIQUE INDEX RABAEV.RRL_INVENTARIZ_LINES_PK ON RABAEV.RRL_INVENTARIZ_LINES
(ID_LINE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_INVETARIZ_PK;

CREATE UNIQUE INDEX RABAEV.RRL_INVETARIZ_PK ON RABAEV.RRL_INVETARIZ
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_OTHOD_NAKLAD_I1;

CREATE INDEX RABAEV.RRL_OTHOD_NAKLAD_I1 ON RABAEV.RRL_OTHOD_NAKLAD
(CREATIONDATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_OTHOD_NAKLAD_PK;

CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_PK ON RABAEV.RRL_OTHOD_NAKLAD
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_A;

CREATE INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_A ON RABAEV.RRL_OTHOD_NAKLAD_ROWS
(ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_ART;

CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_ART ON RABAEV.RRL_OTHOD_NAKLAD_ROWS
(ARTICUL, ID_NAKLAD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_PK ON RABAEV.RRL_OTHOD_NAKLAD_ROWS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_OTHOD_NAKLAD_U9;

CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_U9 ON RABAEV.RRL_OTHOD_NAKLAD
(NAKLADNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PALLETS_MI;

CREATE INDEX RABAEV.RRL_PALLETS_MI ON RABAEV.RRL_PALLETS
(CREATION_DATE, EXPIRY_DATE, ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PALLETS_NAKLAD;

CREATE INDEX RABAEV.RRL_PALLETS_NAKLAD ON RABAEV.RRL_PALLETS
(PRIHOD_NAKLAD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PALLETS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_PALLETS_PK ON RABAEV.RRL_PALLETS
(UID_PALLET)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_1;

CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_1 ON RABAEV.RRL_PRIHOD_NAKLAD
(DATE_OF_NAKLAD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_4;

CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_4 ON RABAEV.RRL_PRIHOD_NAKLAD
(NAKLAD_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_I2;

CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_I2 ON RABAEV.RRL_PRIHOD_NAKLAD
(SM_NAKLAD_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_I8;

CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_I8 ON RABAEV.RRL_PRIHOD_NAKLAD
(ZAKAZ_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_ID;

CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ID ON RABAEV.RRL_PRIHOD_NAKLAD
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_A;

CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_A ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_ART;

CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_ART ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ARTICUL, ORDID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_ID2;

CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_ID2 ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ORDID, ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_PK ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_REMAINS_IND;

CREATE INDEX RABAEV.RRL_REMAINS_IND ON RABAEV.RRL_REMAINS
(CELL, UID_POLETA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_COND_PK;

CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_COND_PK ON RABAEV.RRL_SBORKA_PALLETS_COND
(COND)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_I2;

CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I2 ON RABAEV.RRL_SBORKA_PALLETS
(ST_NUMBER, PALLET_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_I5;

CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_I5 ON RABAEV.RRL_SBORKA_PALLETS
(PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_I7;

CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I7 ON RABAEV.RRL_SBORKA_PALLETS
(STATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_I88;

CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I88 ON RABAEV.RRL_SBORKA_PALLETS
(SBORSHIK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_I9;

CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I9 ON RABAEV.RRL_SBORKA_PALLETS
(TRANSTASK_ID, STDATE, CREATE_DATE, WARE_ID, ORD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_I_99;

CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I_99 ON RABAEV.RRL_SBORKA_PALLETS
(ADDR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_PK ON RABAEV.RRL_SBORKA_PALLETS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE;

CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE ON RABAEV.RRL_SBORKA_PALLETS
(ZONE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE_IN;

CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE_IN ON RABAEV.RRL_SBORKA_PALLETS
(ZONE_TIME_PLAN_IN, ZONE_TIME_PLAN_OUT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I1;

CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I1 ON RABAEV.RRL_SBORKA_PALLET_ROWS
(PALLET_UID, ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I9;

CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I9 ON RABAEV.RRL_SBORKA_PALLET_ROWS
(WARE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PK ON RABAEV.RRL_SBORKA_PALLET_ROWS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PPU;

CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PPU ON RABAEV.RRL_SBORKA_PALLET_ROWS
(PRIHOD_PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_PRICE_I3;

CREATE INDEX RABAEV.RRL_TRANSPORT_PRICE_I3 ON RABAEV.RRL_TRANSPORT_PRICE
(PRICE_NAME, COMPANY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_PRICE_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TRANSPORT_PRICE_PK ON RABAEV.RRL_TRANSPORT_PRICE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_TASK;

CREATE INDEX RABAEV.RRL_TRANSPORT_TASK ON RABAEV.RRL_TRANSPORT_TASK
(CREATEDATE, SHIPMENT_DATE, DELETED, PAY_ORDER_ID, VODITEL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_TASK_DOCK;

CREATE INDEX RABAEV.RRL_TRANSPORT_TASK_DOCK ON RABAEV.RRL_TRANSPORT_TASK
(DOCK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_TASK_DOCK_RESERV;

CREATE INDEX RABAEV.RRL_TRANSPORT_TASK_DOCK_RESERV ON RABAEV.RRL_TRANSPORT_TASK
(DOCK_REZERV_TIME_FROM, DOCK_REZERV_TIME_TO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_TASK_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TRANSPORT_TASK_PK ON RABAEV.RRL_TRANSPORT_TASK
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_TASK_USER;

CREATE INDEX RABAEV.RRL_TRANSPORT_TASK_USER ON RABAEV.RRL_TRANSPORT_TASK
(USER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TRANSPORT_TYPE_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TRANSPORT_TYPE_PK ON RABAEV.RRL_TRANSPORT_TYPE
(TRANSPORTTYPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TR_VEHICLE_I;

CREATE UNIQUE INDEX RABAEV.RRL_TR_VEHICLE_I ON RABAEV.RRL_TR_VEHICLE
(NUM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TR_VEHICLE_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TR_VEHICLE_PK ON RABAEV.RRL_TR_VEHICLE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TR_VODITEL_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TR_VODITEL_PK ON RABAEV.RRL_TR_VODITEL
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TT_DOCK_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TT_DOCK_PK ON RABAEV.RRL_TT_DOCK
(DOCK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TT_PATH_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TT_PATH_PK ON RABAEV.RRL_TT_PATH
(PATH1)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TT_ZONES_PK;

CREATE UNIQUE INDEX RABAEV.RRL_TT_ZONES_PK ON RABAEV.RRL_TT_ZONES
(SUB_ZONE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_TT_ZONES_XY;

CREATE INDEX RABAEV.RRL_TT_ZONES_XY ON RABAEV.RRL_TT_ZONES
(X, Y)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RRL_VERSIONS_PK;

CREATE UNIQUE INDEX RABAEV.RRL_VERSIONS_PK ON RABAEV.RRL_VERSIONS
(VERSION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.RUSERS_PK;

CREATE UNIQUE INDEX RABAEV.RUSERS_PK ON RABAEV.RUSERS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX RABAEV.USER_GROUP_PK;

CREATE UNIQUE INDEX RABAEV.USER_GROUP_PK ON RABAEV.USER_GROUP
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


