-- Migration 060 — GPS vehicle positions
-- Sprint 110 | 2026-05-29

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE RABAEV.RRL_VEHICLE_GPS (
      ID          NUMBER(15) PRIMARY KEY,
      VEHICLE_ID  NUMBER(10) NOT NULL,
      LAT         NUMBER(10,7),
      LON         NUMBER(10,7),
      SPEED_KMH   NUMBER(5),
      TS          DATE NOT NULL,
      CREATED_AT  DATE DEFAULT SYSDATE
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE RABAEV.SEQ_VEHICLE_GPS START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE RABAEV.RRL_VEHICLE_GPS_LAST (
      VEHICLE_ID  NUMBER(10) PRIMARY KEY,
      LAT         NUMBER(10,7),
      LON         NUMBER(10,7),
      SPEED_KMH   NUMBER(5),
      TS          DATE,
      UPDATED_AT  DATE DEFAULT SYSDATE
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_VGPS_VEH ON RABAEV.RRL_VEHICLE_GPS (VEHICLE_ID, TS)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
