set define off
set sqlblanklines on
whenever sqlerror exit failure rollback

prompt Restore RABAEV schema snapshot
prompt Run as SYSTEM or another privileged user connected to the target PDB.

@ddl/000_create_user.sql
@ddl/001_tables.sql
@ddl/002_sequences.sql
@ddl/003_views.sql
@ddl/004_packages.sql
@ddl/005_package_bodies.sql
@ddl/006_functions.sql
@ddl/007_procedures.sql
@ddl/008_triggers.sql
@ddl/009_indexes.sql

@data/inventory_line_pallet_audit_001.sql
@data/lot_audit_001.sql
@data/lot_audit_error_lines_001.sql
@data/order_audit_001.sql
@data/order_audit_error_lines_001.sql
@data/order_mov_hist_001.sql
@data/place_audit_001.sql
@data/place_audit_error_lines_001.sql
@data/q1_001.sql
@data/rights_001.sql
@data/rrl_addr_001.sql
@data/rrl_alarms_001.sql
@data/rrl_articul_mods_001.sql
@data/rrl_articuls_001.sql
@data/rrl_bill_company_001.sql
@data/rrl_billing_001.sql
@data/rrl_billing_nastr_intmov_001.sql
@data/rrl_bill_orders_001.sql
@data/rrl_cells_001.sql
@data/rrl_cells_conditions_mapping_001.sql
@data/rrl_compl_reserve_001.sql
@data/rrl_compl_reserve_002.sql
@data/rrl_compl_seq_001.sql
@data/rrl_constants_001.sql
@data/rrl_cross_docking_zones_001.sql
@data/rrl_error_log_001.sql
@data/rrl_events_001.sql
@data/rrl_history_notes_001.sql
@data/rrl_inventariz_lines_001.sql
@data/rrl_invetariz_001.sql
@data/rrl_login_history_001.sql
@data/rrl_object_001.sql
@data/rrl_order_pallet_rows_001.sql
@data/rrl_order_rows_001.sql
@data/rrl_order_rows_002.sql
@data/rrl_order_rows_003.sql
@data/rrl_order_rows_004.sql
@data/rrl_order_rows_005.sql
@data/rrl_order_rows_006.sql
@data/rrl_order_rows_007.sql
@data/rrl_order_rows_008.sql
@data/rrl_orders_001.sql
@data/rrl_orders_pall_versions_001.sql
@data/rrl_othod_naklad_001.sql
@data/rrl_othod_naklad_rows_001.sql
@data/rrl_pallets_001.sql
@data/rrl_pallets_002.sql
@data/rrl_pallets_003.sql
@data/rrl_pallets_004.sql
@data/rrl_pallets_005.sql
@data/rrl_pallets_006.sql
@data/rrl_pallets_007.sql
@data/rrl_pallets_008.sql
@data/rrl_pallets_009.sql
@data/rrl_prihod_naklad_001.sql
@data/rrl_prihod_naklad_rows_001.sql
@data/rrl_printforms_001.sql
@data/rrl_remains_001.sql
@data/rrl_remain_snapshot_001.sql
@data/rrl_remain_snapshot_rows_001.sql
@data/rrl_revision_row_001.sql
@data/rrl_revizion_001.sql
@data/rrl_sborka_pallet_rows_001.sql
@data/rrl_sborka_pallet_rows_002.sql
@data/rrl_sborka_pallet_rows_003.sql
@data/rrl_sborka_pallet_rows_004.sql
@data/rrl_sborka_pallet_rows_005.sql
@data/rrl_sborka_pallet_rows_006.sql
@data/rrl_sborka_pallets_001.sql
@data/rrl_sborka_pallets_002.sql
@data/rrl_sborka_pallets_003.sql
@data/rrl_sborka_pallets_004.sql
@data/rrl_sborka_pallets_005.sql
@data/rrl_sborka_pallets_006.sql
@data/rrl_sborka_pallets_007.sql
@data/rrl_sborka_pallets_008.sql
@data/rrl_sborka_pallets_009.sql
@data/rrl_sborka_pallets_010.sql
@data/rrl_sborka_pallets_cond_001.sql
@data/rrl_sborka_pallets_history_001.sql
@data/rrl_sborka_pall_rows_parts_001.sql
@data/rrl_summary_pick_list_001.sql
@data/rrl_summary_pick_list_rows_001.sql
@data/rrl_tovaro_nositel_001.sql
@data/rrl_transport_price_001.sql
@data/rrl_transport_task_001.sql
@data/rrl_transport_task_history_001.sql
@data/rrl_transport_type_001.sql
@data/rrl_tr_vehicle_001.sql
@data/rrl_tr_voditel_001.sql
@data/rrl_tr_voditel_ext_001.sql
@data/rrl_tt_bill_price_km_001.sql
@data/rrl_tt_dock_001.sql
@data/rrl_tt_global_mess_001.sql
@data/rrl_tt_load_task_001.sql
@data/rrl_tt_path_001.sql
@data/rrl_tt_zones_001.sql
@data/rrl_type_pall_001.sql
@data/rrl_versions_001.sql
@data/rrl_ware_distr_time_param_001.sql
@data/rrl_ware_masks_001.sql
@data/rrl_wares_001.sql
@data/rrl_ware_tracks_001.sql
@data/rrl_wt_001.sql
@data/rusers_001.sql
@data/sfera_ean_001.sql
@data/tmp_orders_pall_versions_001.sql
@data/tmp_pallet_rows_001.sql
@data/user_group_001.sql

@verify.sql
