ALTER TABLE RABAEV.RRL_SBORKA_PALLET_ROWS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_SBORKA_PALLET_ROWS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_SBORKA_PALLET_ROWS
(
  ID                     INTEGER,
  PALLET_UID             VARCHAR2(50 BYTE),
  ARTICUL                VARCHAR2(15 BYTE),
  SHORTNAME              VARCHAR2(255 BYTE),
  SHTRIHKOD              VARCHAR2(4000 BYTE),
  EI                     VARCHAR2(3 BYTE),
  TAREWEIGHT             NUMBER,
  ORDER_WEIGHT           NUMBER,
  TARESIZE               NUMBER,
  QUANTITY               NUMBER,
  SORTFIELD              INTEGER,
  AUCTION                VARCHAR2(255 BYTE),
  DOCID                  VARCHAR2(15 BYTE),
  WARE_ID                INTEGER,
  PATH                   VARCHAR2(50 BYTE),
  PACK_COUNT             INTEGER,
  ORIGINAL_QUANTITY      NUMBER                 DEFAULT 0,
  ORIGINAL_ORDER_WEIGHT  NUMBER                 DEFAULT 0,
  TIME_OF_CHECKING       DATE,
  CURRENT_MOD_ID         INTEGER,
  SELECTED               INTEGER,
  VYCHERK_USER_ID        VARCHAR2(50 BYTE),
  PRIHOD_PALLET_UID      VARCHAR2(50 BYTE),
  SOBRANO                NUMBER,
  EXPIRY_DATE            DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PPU ON RABAEV.RRL_SBORKA_PALLET_ROWS
(PRIHOD_PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PK ON RABAEV.RRL_SBORKA_PALLET_ROWS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I1 ON RABAEV.RRL_SBORKA_PALLET_ROWS
(PALLET_UID, ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I9 ON RABAEV.RRL_SBORKA_PALLET_ROWS
(WARE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RABAEV.RRL_SBORKA_PALLET_ROWS ADD (
  CONSTRAINT RRL_SBORKA_PALLET_ROWS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

