ALTER TABLE RABAEV.RRL_SBORKA_PALLETS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_SBORKA_PALLETS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_SBORKA_PALLETS
(
  ID                  INTEGER,
  ST_NUMBER           VARCHAR2(50 BYTE),
  CREATE_DATE         DATE,
  WARE_ID             INTEGER,
  PALLET_NUMBER       INTEGER,
  PALLET_UID          VARCHAR2(100 BYTE),
  ADDR                VARCHAR2(255 BYTE),
  STATE               VARCHAR2(50 BYTE),
  STDATE              DATE,
  NAKLAD_NUMBER       VARCHAR2(50 BYTE),
  TRANSTASK_ID        INTEGER,
  ROWS_NUMBER         INTEGER                   DEFAULT 0,
  NAPR                VARCHAR2(255 BYTE),
  ORIGINAL_ST_NUMBER  VARCHAR2(50 BYTE),
  WOOD_WEIGHT         NUMBER                    DEFAULT 0,
  PROOVED             INTEGER                   DEFAULT 0,
  TRIAL_WEIGHT        NUMBER                    DEFAULT 0,
  ZONE                VARCHAR2(50 BYTE),
  USER_ID             VARCHAR2(50 BYTE),
  ORD                 INTEGER                   DEFAULT 0,
  SBORSHIK            VARCHAR2(50 BYTE),
  KLADOVSHIK          VARCHAR2(15 BYTE),
  PROOVED_BY_SCAN     INTEGER                   DEFAULT 0,
  PRIM                VARCHAR2(1024 BYTE),
  COUNT_OF_ERRORS     INTEGER                   DEFAULT 0,
  VESOVSHIK           VARCHAR2(55 BYTE),
  TT_OPLATA           NUMBER                    DEFAULT 0,
  CONDITION           INTEGER                   DEFAULT 0,
  COUNT_OF_PRINTS     INTEGER                   DEFAULT 0,
  ZONE_TIME_PLAN_IN   TIMESTAMP(0),
  ZONE_TIME_PLAN_OUT  TIMESTAMP(0)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I_99 ON RABAEV.RRL_SBORKA_PALLETS
(ADDR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I9 ON RABAEV.RRL_SBORKA_PALLETS
(TRANSTASK_ID, STDATE, CREATE_DATE, WARE_ID, ORD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE_IN ON RABAEV.RRL_SBORKA_PALLETS
(ZONE_TIME_PLAN_IN, ZONE_TIME_PLAN_OUT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE ON RABAEV.RRL_SBORKA_PALLETS
(ZONE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_PK ON RABAEV.RRL_SBORKA_PALLETS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_I5 ON RABAEV.RRL_SBORKA_PALLETS
(PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I2 ON RABAEV.RRL_SBORKA_PALLETS
(ST_NUMBER, PALLET_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I7 ON RABAEV.RRL_SBORKA_PALLETS
(STATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I88 ON RABAEV.RRL_SBORKA_PALLETS
(SBORSHIK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER RABAEV.RRL_SBORKA_PALLETS_TRG
BEFORE INSERT 
ON RABAEV.RRL_SBORKA_PALLETS FOR EACH ROW
DECLARE
BEGIN


if :New.ID is null then
  SELECT RRL_SBORKA_PALLETS_SQ.NEXTVAL
    INTO :New.ID
    FROM dual;
    end if;
 

  SELECT SYSTIMESTAMP
    INTO :New.CREATE_DATE
    FROM dual;


END;
/


ALTER TABLE RABAEV.RRL_SBORKA_PALLETS ADD (
  CONSTRAINT RRL_SBORKA_PALLETS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

