ALTER TABLE RABAEV.RRL_ARTICULS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_ARTICULS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_ARTICULS
(
  ACTICUL           VARCHAR2(15 CHAR),
  NORMA_UKLADKI     NUMBER                      NOT NULL,
  CELL              VARCHAR2(50 CHAR),
  NAME              VARCHAR2(255 CHAR),
  UNIT_TYPE         VARCHAR2(20 CHAR),
  BARCODE_SHT       VARCHAR2(128 CHAR)          DEFAULT 777                   NOT NULL,
  BARCODE_KOR       VARCHAR2(128 CHAR),
  BARCODE_BL        VARCHAR2(128 CHAR),
  WEIGHT_OF_KOR     NUMBER,
  COUNT_IN_ROW      INTEGER,
  ROWS_IN_PAL       INTEGER,
  COUNT_SHT_IN_KOR  NUMBER,
  COUNT_SHT_IN_BL   NUMBER                      DEFAULT 1,
  PALLET_MULTIPLE   NUMBER                      DEFAULT 1,
  CARTON_WEIGHT     NUMBER                      DEFAULT 0,
  ETAJ_LIMIT        INTEGER                     DEFAULT 100,
  BESTBEFOREDAYS    INTEGER                     DEFAULT 360,
  SSP               NUMBER                      DEFAULT 0,
  ABC_GROUP         VARCHAR2(1 BYTE),
  XYZ_GROUP         VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RABAEV.RRL_ARTICULS.ETAJ_LIMIT IS 'Выше данного этажа не размещать';


ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_PRIHOD_NAKLAD CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_PRIHOD_NAKLAD
(
  NAKLAD_NUMBER     VARCHAR2(20 CHAR),
  DATE_OF_NAKLAD    DATE,
  DATE_OF_ACCEPT    DATE,
  POSTAVSHIK_NAME   VARCHAR2(50 CHAR),
  SM_NAKLAD_NUMBER  VARCHAR2(50 CHAR),
  CONDITION         INTEGER                     DEFAULT 0,
  ID                INTEGER,
  WARE_ID           INTEGER                     DEFAULT 1,
  ZAKAZ_NUMBER      VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_PALLETS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_PALLETS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_PALLETS
(
  UID_PALLET        VARCHAR2(50 CHAR),
  ARTICUL           VARCHAR2(15 CHAR),
  CREATION_DATE     DATE,
  EXPIRY_DATE       DATE,
  UNIT_COUNT        NUMBER,
  PRICE             NUMBER,
  PRIHOD_NAKLAD_ID  INTEGER                     NOT NULL,
  PRINTED           INTEGER                     DEFAULT 0,
  KLADOVSHIK        VARCHAR2(15 BYTE),
  PRODUCED_DATE     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TRANSPORT_TASK
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TRANSPORT_TASK CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TRANSPORT_TASK
(
  ID                     INTEGER,
  CREATEDATE             DATE,
  TRANSPORT              VARCHAR2(50 BYTE),
  TRANSTYPE              VARCHAR2(10 BYTE),
  ROUTETYPE              VARCHAR2(100 BYTE),
  CONDITION              VARCHAR2(15 BYTE)      DEFAULT 'Спланирован',
  TRANSP_ZONE            VARCHAR2(15 BYTE),
  WAVE                   VARCHAR2(15 BYTE),
  SHIPMENT_DATE          DATE,
  PLANNED_DELIVERY_DATE  DATE,
  VODITEL_ID             INTEGER,
  PRIMECHANIE            VARCHAR2(1024 BYTE),
  DELETED                INTEGER                DEFAULT 0,
  DOCK                   VARCHAR2(50 BYTE),
  PRICE                  NUMBER,
  HOURS                  NUMBER,
  RANGE1                 NUMBER,
  TEMP_REGION            VARCHAR2(1024 BYTE),
  PAY_ORDER_ID           INTEGER                DEFAULT 0,
  TEMP_WEIGHT            NUMBER,
  USER_ID                VARCHAR2(50 BYTE),
  PAY_REGION             VARCHAR2(1024 BYTE),
  ADDR_PREMIO            INTEGER,
  SHIPMENT_TIME          DATE,
  DOCK_REZERV_TIME_FROM  TIMESTAMP(0),
  DOCK_REZERV_TIME_TO    TIMESTAMP(0)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TR_VEHICLE
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TR_VEHICLE CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TR_VEHICLE
(
  ID           INTEGER,
  NUM          VARCHAR2(50 BYTE),
  TR_TYPE      VARCHAR2(15 BYTE),
  MARKA        VARCHAR2(50 BYTE),
  REF_REJIM    VARCHAR2(50 BYTE)                DEFAULT 'без',
  WORKING_NOW  INTEGER                          DEFAULT 1,
  PALLETS      INTEGER,
  BLOCKED      INTEGER                          DEFAULT 0,
  GIDROBORT    INTEGER                          DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TR_VODITEL
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TR_VODITEL CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TR_VODITEL
(
  ID              INTEGER,
  F               VARCHAR2(50 BYTE),
  I               VARCHAR2(50 BYTE),
  O               VARCHAR2(50 BYTE),
  DELETED         INTEGER                       DEFAULT 0,
  SOBSTVENNYY     INTEGER                       DEFAULT 0,
  VEH_ID          INTEGER,
  PASSPORT        VARCHAR2(255 BYTE),
  DOVERENNOST_OT  VARCHAR2(50 BYTE),
  TRANSPORT_NUM   VARCHAR2(50 BYTE),
  ADDR            VARCHAR2(255 BYTE),
  TEL             VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_ADDR
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_ADDR CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_ADDR
(
  ADDR            VARCHAR2(255 BYTE),
  NAPR            VARCHAR2(50 BYTE),
  RAION           VARCHAR2(50 BYTE),
  REGION          VARCHAR2(250 BYTE),
  ORD             INTEGER                       DEFAULT 0,
  TRANSPORT_TYPE  VARCHAR2(15 BYTE)             DEFAULT 15,
  PRIM1           VARCHAR2(255 BYTE),
  STOL            INTEGER                       DEFAULT 0,
  DOLGOTA         NUMBER,
  SHIROTA         NUMBER,
  LEAD_TIME       INTEGER                       DEFAULT 0,
  CLIENT_GROUP    VARCHAR2(50 BYTE),
  SHIPPING_TIME   VARCHAR2(5 BYTE)              DEFAULT '00:00'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_ARTICUL_MODS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_ARTICUL_MODS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_ARTICUL_MODS
(
  ID             INTEGER,
  ARTICUL        VARCHAR2(15 BYTE),
  NAME           VARCHAR2(50 BYTE),
  SHT_IN_KOR     NUMBER,
  SHT_WEIGHT     NUMBER,
  KARTON_WEIGHT  NUMBER,
  DELETED        INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_SBORKA_PALLETS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_SBORKA_PALLETS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_SBORKA_PALLETS
(
  ID                  INTEGER,
  ST_NUMBER           VARCHAR2(50 BYTE),
  CREATE_DATE         DATE,
  WARE_ID             INTEGER,
  PALLET_NUMBER       INTEGER,
  PALLET_UID          VARCHAR2(100 BYTE),
  ADDR                VARCHAR2(255 BYTE),
  STATE               VARCHAR2(50 BYTE),
  STDATE              DATE,
  NAKLAD_NUMBER       VARCHAR2(50 BYTE),
  TRANSTASK_ID        INTEGER,
  ROWS_NUMBER         INTEGER                   DEFAULT 0,
  NAPR                VARCHAR2(255 BYTE),
  ORIGINAL_ST_NUMBER  VARCHAR2(50 BYTE),
  WOOD_WEIGHT         NUMBER                    DEFAULT 0,
  PROOVED             INTEGER                   DEFAULT 0,
  TRIAL_WEIGHT        NUMBER                    DEFAULT 0,
  ZONE                VARCHAR2(50 BYTE),
  USER_ID             VARCHAR2(50 BYTE),
  ORD                 INTEGER                   DEFAULT 0,
  SBORSHIK            VARCHAR2(50 BYTE),
  KLADOVSHIK          VARCHAR2(15 BYTE),
  PROOVED_BY_SCAN     INTEGER                   DEFAULT 0,
  PRIM                VARCHAR2(1024 BYTE),
  COUNT_OF_ERRORS     INTEGER                   DEFAULT 0,
  VESOVSHIK           VARCHAR2(55 BYTE),
  TT_OPLATA           NUMBER                    DEFAULT 0,
  CONDITION           INTEGER                   DEFAULT 0,
  COUNT_OF_PRINTS     INTEGER                   DEFAULT 0,
  ZONE_TIME_PLAN_IN   TIMESTAMP(0),
  ZONE_TIME_PLAN_OUT  TIMESTAMP(0)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_SBORKA_PALLET_ROWS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_SBORKA_PALLET_ROWS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_SBORKA_PALLET_ROWS
(
  ID                     INTEGER,
  PALLET_UID             VARCHAR2(50 BYTE),
  ARTICUL                VARCHAR2(15 BYTE),
  SHORTNAME              VARCHAR2(255 BYTE),
  SHTRIHKOD              VARCHAR2(4000 BYTE),
  EI                     VARCHAR2(3 BYTE),
  TAREWEIGHT             NUMBER,
  ORDER_WEIGHT           NUMBER,
  TARESIZE               NUMBER,
  QUANTITY               NUMBER,
  SORTFIELD              INTEGER,
  AUCTION                VARCHAR2(255 BYTE),
  DOCID                  VARCHAR2(15 BYTE),
  WARE_ID                INTEGER,
  PATH                   VARCHAR2(50 BYTE),
  PACK_COUNT             INTEGER,
  ORIGINAL_QUANTITY      NUMBER                 DEFAULT 0,
  ORIGINAL_ORDER_WEIGHT  NUMBER                 DEFAULT 0,
  TIME_OF_CHECKING       DATE,
  CURRENT_MOD_ID         INTEGER,
  SELECTED               INTEGER,
  VYCHERK_USER_ID        VARCHAR2(50 BYTE),
  PRIHOD_PALLET_UID      VARCHAR2(50 BYTE),
  SOBRANO                NUMBER,
  EXPIRY_DATE            DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TRANSPORT_PRICE
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TRANSPORT_PRICE CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TRANSPORT_PRICE
(
  ID               INTEGER,
  PRICE_NAME       VARCHAR2(1024 BYTE)          NOT NULL,
  PRICE            NUMBER(10,2)                 NOT NULL,
  COMPANY          VARCHAR2(255 BYTE)           DEFAULT null,
  RANGE1           NUMBER,
  PRICE_FOR_HOURS  NUMBER                       DEFAULT 0,
  TYPE_TR          VARCHAR2(15 BYTE),
  PRICE_FOLDER     INTEGER                      DEFAULT 0,
  PRICE_FOR_ADDR   NUMBER                       DEFAULT 0,
  NORM_HOURS       NUMBER                       DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TT_DOCK
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TT_DOCK CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TT_DOCK
(
  DOCK             VARCHAR2(15 BYTE),
  WARE_ID          INTEGER,
  ORD              INTEGER,
  DOCK_IS_BLOCKED  INTEGER                      DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TT_ZONES
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TT_ZONES CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TT_ZONES
(
  ZONE      VARCHAR2(20 BYTE),
  SUB_ZONE  VARCHAR2(25 BYTE),
  DOCK      VARCHAR2(15 BYTE),
  X         NUMBER                              DEFAULT 1000,
  Y         NUMBER                              DEFAULT 1000
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.Q1 CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.Q1
(
  ID  INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.RRL_TT_BILL_PRICE_KM CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TT_BILL_PRICE_KM
(
  TT       VARCHAR2(15 BYTE),
  KM_FROM  INTEGER,
  KM_TO    INTEGER,
  PRICE    INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RUSERS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RUSERS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RUSERS
(
  ID                           NVARCHAR2(50)    NOT NULL,
  NAME                         NVARCHAR2(255),
  PRAVO_INVENTORY_EDIT         INTEGER          DEFAULT 0,
  PRAVO_CHECK_ORDER            INTEGER          DEFAULT 0,
  PRAVO_LIGHT_INVENTORY_CHECK  INTEGER          DEFAULT 0,
  DELETED                      INTEGER          DEFAULT 0,
  PRAVO_RAZVOZ_ZAYAVOK         INTEGER          DEFAULT 0,
  WMSUSER_ID                   VARCHAR2(5 BYTE),
  PRAVO_EAN_PRODUCT_CHANGE     INTEGER          DEFAULT 0,
  PRAVO_KARSHIK                INTEGER          DEFAULT 0,
  WARE_ID                      INTEGER          DEFAULT 1,
  PASS                         VARCHAR2(50 BYTE),
  PRAVO_ADMIN_LOGIN            INTEGER,
  SMFILEPATH                   VARCHAR2(1024 BYTE),
  IP_SERVER_PRINT              VARCHAR2(50 BYTE),
  USER_GROUP                   VARCHAR2(15 BYTE),
  SMENA                        VARCHAR2(5 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.SFERA_EAN CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.SFERA_EAN
(
  TMC_UID      VARCHAR2(50 CHAR)                NOT NULL,
  EAN_SHT      VARCHAR2(20 CHAR),
  EAN_BL       VARCHAR2(20 CHAR),
  EAN_KOR      VARCHAR2(20 CHAR),
  MANUALENTER  CHAR(1 CHAR)                     DEFAULT 'Y',
  SHT_IN_BL    INTEGER                          NOT NULL,
  BL_IN_KOR    INTEGER                          NOT NULL,
  УИД          INTEGER,
  NAME         VARCHAR2(255 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.RRL_REMAINS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_REMAINS
(
  CELL                 VARCHAR2(20 BYTE),
  UID_POLETA           VARCHAR2(50 BYTE),
  REMAIN               NUMBER,
  OTHOD_NAKL_ID        INTEGER                  DEFAULT 0,
  TIME_OF_LAST_UPDATE  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD_ROWS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_PRIHOD_NAKLAD_ROWS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(
  ORDID          INTEGER,
  ARTICUL        VARCHAR2(15 CHAR),
  EXPIRY_DATE    DATE,
  ID             INTEGER,
  COUNT1         NUMBER                         DEFAULT 0,
  PRICE          NUMBER                         DEFAULT 0,
  INVENT_CELL    VARCHAR2(15 BYTE),
  KOLPAL         NUMBER,
  SROK_GODNOSTI  INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD_ROWS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_OTHOD_NAKLAD_ROWS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_OTHOD_NAKLAD_ROWS
(
  ID         INTEGER,
  ID_NAKLAD  INTEGER                            NOT NULL,
  ARTICUL    VARCHAR2(15 CHAR)                  NOT NULL,
  COUNT1     NUMBER                             NOT NULL,
  PRICE      NUMBER                             DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_OTHOD_NAKLAD CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_OTHOD_NAKLAD
(
  ID                   INTEGER,
  NAKLADNAME           VARCHAR2(50 CHAR)        NOT NULL,
  MAG_NO               VARCHAR2(50 CHAR)        NOT NULL,
  NAKLADDATE           DATE                     NOT NULL,
  CREATIONDATE         DATE                     NOT NULL,
  PLANNEDDELIVERYDATE  DATE,
  CONDITION            INTEGER                  DEFAULT 0,
  SUMM                 NUMBER                   DEFAULT 0,
  WARE_ID              INTEGER                  DEFAULT 1
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_INVETARIZ
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_INVETARIZ CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_INVETARIZ
(
  ID       INTEGER,
  DATE_OF  DATE                                 NOT NULL,
  TYPE1    INTEGER                              DEFAULT 1                     NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_INVENTARIZ_LINES
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_INVENTARIZ_LINES CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_INVENTARIZ_LINES
(
  ID_OF_INVENT  INTEGER                         NOT NULL,
  ID_LINE       INTEGER,
  CELL          VARCHAR2(50 CHAR)               NOT NULL,
  PALLET_ID     VARCHAR2(50 CHAR)               NOT NULL,
  COUNT1        NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_CELLS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_CELLS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_CELLS
(
  CELL                    VARCHAR2(15 CHAR),
  OTBOR                   INTEGER               DEFAULT 0,
  BLOCKED_FOR_REMAINS     INTEGER               DEFAULT 0,
  BLOCKED_FOR_POPOLNENIE  INTEGER               DEFAULT 0,
  UID_POLETA_FOR_BLOCK    VARCHAR2(50 CHAR),
  TIME_FOR_BLOCK          DATE,
  X                       INTEGER               DEFAULT 10000                 NOT NULL,
  Y                       INTEGER               DEFAULT 10000                 NOT NULL,
  Z                       INTEGER               DEFAULT 10000                 NOT NULL,
  BLOCKED_FOR_ACCEPT      INTEGER               DEFAULT 0,
  WARE_ID                 INTEGER               DEFAULT 1,
  IS_SYSTEM               INTEGER               DEFAULT 0,
  EXPEDITION_GROUP        VARCHAR2(15 BYTE),
  LAST_TIME_OF_UPDATE     DATE,
  LIMIT_WEIGHT            NUMBER                DEFAULT 10000,
  LIMIT_HEIGHT            NUMBER                DEFAULT 10000
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RABAEV.RRL_CELLS.LIMIT_WEIGHT IS 'Ограничения на вес товара в ячейке';

COMMENT ON COLUMN RABAEV.RRL_CELLS.LIMIT_HEIGHT IS 'Ограничения на высоту паллета';


ALTER TABLE RABAEV.RRL_EVENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_EVENTS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_EVENTS
(
  ID_EVENT        NUMBER,
  CELL_FROM       VARCHAR2(20 BYTE),
  CELL_TO         VARCHAR2(20 BYTE),
  DATE_EVENT      DATE                          NOT NULL,
  DATE_OF_ORDER   DATE,
  COUNT_EVENT     NUMBER,
  TYPE_EVENT      NUMBER(38)                    NOT NULL,
  UID_POLETA      VARCHAR2(50 BYTE),
  USER_ID         VARCHAR2(50 BYTE)             NOT NULL,
  PRIHOD_NAKL_ID  INTEGER                       DEFAULT 0,
  OTHOD_NAKL_ID   INTEGER                       DEFAULT 0,
  PALLET_ROW_ID   INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.PLACE_AUDIT_ERROR_LINES CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.PLACE_AUDIT_ERROR_LINES
(
  PALLETID    VARCHAR2(25 CHAR)                 NOT NULL,
  CONDITION   VARCHAR2(15 CHAR),
  UNIT_COUNT  INTEGER                           DEFAULT 0                     NOT NULL,
  UID1        VARCHAR2(12 CHAR),
  EAN         VARCHAR2(25 CHAR),
  RUSER       NVARCHAR2(50),
  DATE1       DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.PLACE_AUDIT CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.PLACE_AUDIT
(
  PALLETID   VARCHAR2(25 CHAR)                  NOT NULL,
  CONDITION  VARCHAR2(25 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.ORDER_MOV_HIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.ORDER_MOV_HIST CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.ORDER_MOV_HIST
(
  ID          INTEGER                           NOT NULL,
  ORDER_UID   INTEGER                           NOT NULL,
  ZONE        NVARCHAR2(15),
  RUSER       NVARCHAR2(15)                     NOT NULL,
  TIME_STAMP  DATE,
  LAST_FLAG   INTEGER                           DEFAULT 1,
  USSCC       VARCHAR2(50 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.ORDER_AUDIT_ERROR_LINES
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.ORDER_AUDIT_ERROR_LINES CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.ORDER_AUDIT_ERROR_LINES
(
  ORDER_NUMBER   VARCHAR2(25 CHAR)              NOT NULL,
  CONDITION      VARCHAR2(15 CHAR),
  UNIT_COUNT     INTEGER                        DEFAULT 0                     NOT NULL,
  UID1           VARCHAR2(12 CHAR),
  EAN            VARCHAR2(25 CHAR),
  TIME_OF_AUDIT  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.ORDER_AUDIT CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.ORDER_AUDIT
(
  ORDER_NUMBER  VARCHAR2(25 CHAR)               NOT NULL,
  CONDITION     VARCHAR2(25 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.LOT_AUDIT_ERROR_LINES CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.LOT_AUDIT_ERROR_LINES
(
  SSCC           VARCHAR2(25 CHAR)              NOT NULL,
  CONDITION      VARCHAR2(15 CHAR),
  UNIT_COUNT     NUMBER                         DEFAULT 0                     NOT NULL,
  UID1           VARCHAR2(12 CHAR),
  EAN            VARCHAR2(25 CHAR),
  TIME_OF_AUDIT  DATE,
  PLAN_COUNT     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.LOT_AUDIT
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.LOT_AUDIT CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.LOT_AUDIT
(
  SSCC       VARCHAR2(25 CHAR)                  NOT NULL,
  CONDITION  VARCHAR2(25 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.INVENTORY_LINE_PALLET_AUDIT CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.INVENTORY_LINE_PALLET_AUDIT
(
  УИД           VARCHAR2(25 CHAR)               NOT NULL,
  КОЛ           INTEGER                         DEFAULT 0,
  PALLETID      VARCHAR2(25 CHAR)               NOT NULL,
  ДАТАСОЗДАНИЯ  DATE,
  USER_ID       VARCHAR2(50 CHAR),
  METHOD        VARCHAR2(20 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.RRL_WARES CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_WARES
(
  ID                           INTEGER,
  NAME                         VARCHAR2(50 BYTE),
  OVERFLOW_CELL_NAME           VARCHAR2(50 BYTE) DEFAULT 'OVERFLOW',
  PREFIX                       VARCHAR2(3 BYTE),
  FAKE_ROWS                    INTEGER          DEFAULT 0,
  FAKE_ART                     VARCHAR2(25 BYTE) DEFAULT 'Z0001',
  BLOCK_IF_NO_PROOVE           INTEGER          DEFAULT 0,
  VERIFY_VYCHERK               INTEGER          DEFAULT 0,
  WRITE_BOTH_EXPIRYANDBEST     INTEGER          DEFAULT 0,
  SPIS_IF_HRAN_NO_EMPTY        VARCHAR2(10 BYTE),
  ALLOW_HALF_VYCHERK           INTEGER          DEFAULT 1,
  SPIS_OTBOR_ON_SCAN_OPALL     INTEGER          DEFAULT 0,
  SPIS_OTBOR_ON_WPROOVE_OPALL  INTEGER          DEFAULT 0,
  TIME_COEFF                   NUMBER           DEFAULT 0.33,
  XYZ_XCOV                     NUMBER           DEFAULT 0.1,
  XYZ_YCOV                     NUMBER           DEFAULT 0.5,
  ABC_A                        NUMBER           DEFAULT 0.8,
  ABC_B                        NUMBER           DEFAULT 0.10,
  ABC_XYZ_TIME_EDGES_IN_DAYS   NUMBER(30),
  VERIFY_VYCHERK_IN_OTBOR      INTEGER          DEFAULT 0,
  PRINT_EXPIRY_DATE_OP         INTEGER          DEFAULT 0,
  COUNT_OF_PRINTS              INTEGER          DEFAULT 10000,
  WEIGHT_LIMIT_WARNING         INTEGER          DEFAULT 0,
  WEIGHT_LIMIT_STOP            INTEGER          DEFAULT 0,
  PARENT_WARE_ID               INTEGER,
  ORD2                         INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RABAEV.RRL_WARES.SPIS_IF_HRAN_NO_EMPTY IS 'Имя ячейки, куда списать товар, когда идет размещение в непустую ячейку';

COMMENT ON COLUMN RABAEV.RRL_WARES.XYZ_XCOV IS 'Коэффциент ковариации Х. по умолчанию 0,1';

COMMENT ON COLUMN RABAEV.RRL_WARES.XYZ_YCOV IS 'Коэффициент ковариации Y. По умолчанию = 0.5';


ALTER TABLE RABAEV.USER_GROUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.USER_GROUP CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.USER_GROUP
(
  ID    VARCHAR2(15 BYTE),
  NAME  VARCHAR2(255 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RIGHTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RIGHTS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RIGHTS
(
  RIGHT1      VARCHAR2(30 BYTE),
  USER_GROUP  VARCHAR2(15 BYTE),
  ID          INTEGER,
  DESCR       VARCHAR2(255 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_BILL_ORDERS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_BILL_ORDERS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_BILL_ORDERS
(
  ID           INTEGER,
  NUM          VARCHAR2(15 BYTE),
  COMPANY      VARCHAR2(30 BYTE),
  DATEOFORDER  DATE,
  DATEFROM     DATE,
  DATETO       DATE,
  CLOSED       INTEGER                          DEFAULT 0,
  SUMM         NUMBER                           DEFAULT 0,
  PAYED        INTEGER                          DEFAULT 0,
  NUM_PLAT     VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_BILL_COMPANY
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_BILL_COMPANY CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_BILL_COMPANY
(
  COMPANYNAME    VARCHAR2(30 BYTE),
  ADDR           VARCHAR2(255 BYTE),
  DELETED        INTEGER                        DEFAULT 0,
  POS            INTEGER,
  COLOR          VARCHAR2(50 BYTE),
  SPECIAL_PRICE  INTEGER                        DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_SBORKA_PALLETS_COND
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_SBORKA_PALLETS_COND CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_SBORKA_PALLETS_COND
(
  COND        VARCHAR2(25 BYTE),
  DONE        INTEGER                           DEFAULT 0,
  SENDT       INTEGER                           DEFAULT 1,
  IN_PROCESS  INTEGER                           DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.RRL_ERROR_LOG CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_ERROR_LOG
(
  ERROR    VARCHAR2(1024 BYTE),
  DATET    DATE,
  USER_ID  VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_VERSIONS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_VERSIONS CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_VERSIONS
(
  VERSION  VARCHAR2(150 BYTE),
  ALLOW    INTEGER                              DEFAULT 1
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_HISTORY_NOTES
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_HISTORY_NOTES CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_HISTORY_NOTES
(
  ID         INTEGER,
  USER_ID    VARCHAR2(50 BYTE),
  ADDR_TO    VARCHAR2(50 BYTE),
  ADDR_FROM  VARCHAR2(50 BYTE),
  MESS       VARCHAR2(1024 BYTE),
  PUID       VARCHAR2(100 BYTE),
  COUNT1     NUMBER,
  EVENTDATE  DATE,
  MESS2      VARCHAR2(1024 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.RRL_TT_LOAD_TASK CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TT_LOAD_TASK
(
  TT_ID      INTEGER,
  DOCK       VARCHAR2(50 BYTE),
  LOAD_FROM  DATE,
  LOAD_TO    DATE,
  WARE_ID    INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TT_PATH
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TT_PATH CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TT_PATH
(
  PATH1            VARCHAR2(1024 BYTE),
  RANGE1           NUMBER,
  NORMATIVE_HOURS  NUMBER                       DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_TRANSPORT_TYPE
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_TRANSPORT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_TRANSPORT_TYPE
(
  TRANSPORTTYPE  VARCHAR2(25 BYTE),
  REF            INTEGER,
  NORMA_PALLET   INTEGER,
  NORMA_WEIGHT   NUMBER,
  ORD            INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.RRL_BILLING_NASTR_INTMOV CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_BILLING_NASTR_INTMOV
(
  EXPEDIT_GROUP_TO    VARCHAR2(20 BYTE),
  USER_GROUP          VARCHAR2(20 BYTE),
  UE                  NUMBER                    DEFAULT 0,
  EXPEDIT_GROUP_FROM  VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RABAEV.RRL_BILLING
 DROP PRIMARY KEY CASCADE;
DROP TABLE RABAEV.RRL_BILLING CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_BILLING
(
  ID          INTEGER,
  USER_ID     VARCHAR2(50 BYTE),
  UE          NUMBER,
  TIMEOF      DATE,
  OPERATION   VARCHAR2(50 BYTE),
  PRIM        VARCHAR2(255 BYTE),
  PALLET_UID  VARCHAR2(50 BYTE),
  DELETED     INTEGER,
  CELL_FROM   VARCHAR2(50 BYTE),
  CELL_TO     VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RABAEV.RRL_WARE_DISTR_TIME_PARAM CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_WARE_DISTR_TIME_PARAM
(
  WARE_ID         VARCHAR2(50 BYTE),
  TIME_PERC_FROM  NUMBER,
  TIME_PERC_TO    NUMBER,
  DISTR_PERC      NUMBER,
  CLIENT_GROUP    VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RABAEV.RRL_WARE_DISTR_TIME_PARAM IS 'Параметры допустимых сроков дистрибуции в зависимости от склада, группы магазинов.';


DROP TABLE RABAEV.RRL_SBORKA_PALLETS_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE RABAEV.RRL_SBORKA_PALLETS_HISTORY
(
  ID          INTEGER,
  PALLET_UID  VARCHAR2(50 BYTE),
  USER_ID     VARCHAR2(50 BYTE),
  ZONE        VARCHAR2(50 BYTE),
  EVENT       VARCHAR2(50 BYTE),
  TIME1       DATE,
  WEIGHT      NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RABAEV.USER_GROUP_PK ON RABAEV.USER_GROUP
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RUSERS_PK ON RABAEV.RUSERS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_VERSIONS_PK ON RABAEV.RRL_VERSIONS
(VERSION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_TT_ZONES_XY ON RABAEV.RRL_TT_ZONES
(X, Y)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TT_ZONES_PK ON RABAEV.RRL_TT_ZONES
(SUB_ZONE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TT_PATH_PK ON RABAEV.RRL_TT_PATH
(PATH1)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TT_DOCK_PK ON RABAEV.RRL_TT_DOCK
(DOCK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TR_VODITEL_PK ON RABAEV.RRL_TR_VODITEL
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TR_VEHICLE_I ON RABAEV.RRL_TR_VEHICLE
(NUM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TR_VEHICLE_PK ON RABAEV.RRL_TR_VEHICLE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TRANSPORT_TYPE_PK ON RABAEV.RRL_TRANSPORT_TYPE
(TRANSPORTTYPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TRANSPORT_TASK_PK ON RABAEV.RRL_TRANSPORT_TASK
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_TRANSPORT_TASK_DOCK ON RABAEV.RRL_TRANSPORT_TASK
(DOCK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_TRANSPORT_TASK_DOCK_RESERV ON RABAEV.RRL_TRANSPORT_TASK
(DOCK_REZERV_TIME_FROM, DOCK_REZERV_TIME_TO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_TRANSPORT_TASK ON RABAEV.RRL_TRANSPORT_TASK
(CREATEDATE, SHIPMENT_DATE, DELETED, PAY_ORDER_ID, VODITEL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_TRANSPORT_TASK_USER ON RABAEV.RRL_TRANSPORT_TASK
(USER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_TRANSPORT_PRICE_I3 ON RABAEV.RRL_TRANSPORT_PRICE
(PRICE_NAME, COMPANY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_TRANSPORT_PRICE_PK ON RABAEV.RRL_TRANSPORT_PRICE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I9 ON RABAEV.RRL_SBORKA_PALLET_ROWS
(WARE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_I1 ON RABAEV.RRL_SBORKA_PALLET_ROWS
(PALLET_UID, ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PK ON RABAEV.RRL_SBORKA_PALLET_ROWS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLET_ROWS_PPU ON RABAEV.RRL_SBORKA_PALLET_ROWS
(PRIHOD_PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_COND_PK ON RABAEV.RRL_SBORKA_PALLETS_COND
(COND)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I88 ON RABAEV.RRL_SBORKA_PALLETS
(SBORSHIK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I7 ON RABAEV.RRL_SBORKA_PALLETS
(STATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I2 ON RABAEV.RRL_SBORKA_PALLETS
(ST_NUMBER, PALLET_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_I5 ON RABAEV.RRL_SBORKA_PALLETS
(PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_SBORKA_PALLETS_PK ON RABAEV.RRL_SBORKA_PALLETS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE ON RABAEV.RRL_SBORKA_PALLETS
(ZONE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_ZONE_IN ON RABAEV.RRL_SBORKA_PALLETS
(ZONE_TIME_PLAN_IN, ZONE_TIME_PLAN_OUT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I9 ON RABAEV.RRL_SBORKA_PALLETS
(TRANSTASK_ID, STDATE, CREATE_DATE, WARE_ID, ORD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_SBORKA_PALLETS_I_99 ON RABAEV.RRL_SBORKA_PALLETS
(ADDR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_REMAINS_IND ON RABAEV.RRL_REMAINS
(CELL, UID_POLETA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_A ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_ART ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ARTICUL, ORDID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_ID2 ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ORDID, ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ROWS_PK ON RABAEV.RRL_PRIHOD_NAKLAD_ROWS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_I8 ON RABAEV.RRL_PRIHOD_NAKLAD
(ZAKAZ_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_4 ON RABAEV.RRL_PRIHOD_NAKLAD
(NAKLAD_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_ID ON RABAEV.RRL_PRIHOD_NAKLAD
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_PRIHOD_NAKLAD_I2 ON RABAEV.RRL_PRIHOD_NAKLAD
(SM_NAKLAD_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_PRIHOD_NAKLAD_1 ON RABAEV.RRL_PRIHOD_NAKLAD
(DATE_OF_NAKLAD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_PALLETS_MI ON RABAEV.RRL_PALLETS
(CREATION_DATE, EXPIRY_DATE, ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_PALLETS_NAKLAD ON RABAEV.RRL_PALLETS
(PRIHOD_NAKLAD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_PALLETS_PK ON RABAEV.RRL_PALLETS
(UID_PALLET)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_PK ON RABAEV.RRL_OTHOD_NAKLAD_ROWS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_A ON RABAEV.RRL_OTHOD_NAKLAD_ROWS
(ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_ROWS_ART ON RABAEV.RRL_OTHOD_NAKLAD_ROWS
(ARTICUL, ID_NAKLAD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_OTHOD_NAKLAD_I1 ON RABAEV.RRL_OTHOD_NAKLAD
(CREATIONDATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_PK ON RABAEV.RRL_OTHOD_NAKLAD
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_OTHOD_NAKLAD_U9 ON RABAEV.RRL_OTHOD_NAKLAD
(NAKLADNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_INVETARIZ_PK ON RABAEV.RRL_INVETARIZ
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_INVENTARIZ_LINES_PK ON RABAEV.RRL_INVENTARIZ_LINES
(ID_LINE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_HISTORY_NOTES_PK ON RABAEV.RRL_HISTORY_NOTES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_EVENTS_PK ON RABAEV.RRL_EVENTS
(ID_EVENT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_EVENTS_DATE_EVENT ON RABAEV.RRL_EVENTS
(DATE_EVENT, UID_POLETA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.PALLET_ROW_ID_I8 ON RABAEV.RRL_EVENTS
(PALLET_ROW_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_CELLS_WARE_ID ON RABAEV.RRL_CELLS
(WARE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_CELLS_PK ON RABAEV.RRL_CELLS
(CELL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_CELLS_EXP ON RABAEV.RRL_CELLS
(EXPEDITION_GROUP)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_BILL_ORDERS_I4 ON RABAEV.RRL_BILL_ORDERS
(NUM, COMPANY, DATEOFORDER, DATEFROM, DATETO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_BILL_ORDERS_PK ON RABAEV.RRL_BILL_ORDERS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_BILL_COMPANY_PK ON RABAEV.RRL_BILL_COMPANY
(COMPANYNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_BILLING_I1 ON RABAEV.RRL_BILLING
(USER_ID, TIMEOF, OPERATION, PALLET_UID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_BILLING_PK ON RABAEV.RRL_BILLING
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_ARTICUL_MODS_ID ON RABAEV.RRL_ARTICUL_MODS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.ART ON RABAEV.RRL_ARTICUL_MODS
(ARTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_ARTICULS_BARCODE_SHT ON RABAEV.RRL_ARTICULS
(BARCODE_SHT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_ARTICULS_PK ON RABAEV.RRL_ARTICULS
(ACTICUL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.PALLET_MULTIPLE_I ON RABAEV.RRL_ARTICULS
(PALLET_MULTIPLE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.RRL_ADDR_I33 ON RABAEV.RRL_ADDR
(NAPR, RAION, REGION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RRL_ADDR_PK ON RABAEV.RRL_ADDR
(ADDR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.RIGHTS_PK ON RABAEV.RIGHTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.ORDER_MOV_HIST_PK ON RABAEV.ORDER_MOV_HIST
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.ORDER_AUDIT_LINES_PK ON RABAEV.ORDER_AUDIT_ERROR_LINES
(ORDER_NUMBER, UID1)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.ORDER_AUDIT_PK ON RABAEV.ORDER_AUDIT
(ORDER_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RABAEV.LOT_AUDIT_ERROR_LINES_PK ON RABAEV.LOT_AUDIT_ERROR_LINES
(SSCC)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RABAEV.LOT_AUDIT_PK ON RABAEV.LOT_AUDIT
(SSCC)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER RABAEV.RRL_PRIHOD_NAKLAD_TRG
BEFORE INSERT 
ON RABAEV.RRL_PRIHOD_NAKLAD FOR EACH ROW
DECLARE
BEGIN


if :New.ID is null then
  SELECT RRL_PRIH_ORD_ID.NEXTVAL
    INTO :New.ID
    FROM dual;
    end if;
    



END;
/

ALTER TRIGGER RABAEV.RRL_PRIHOD_NAKLAD_TRG DISABLE;


CREATE OR REPLACE TRIGGER RABAEV.SFERA_EAN_TRG
BEFORE INSERT 
ON RABAEV.SFERA_EAN FOR EACH ROW
DECLARE
BEGIN


if :New.УИД is null then
  SELECT SFERA_EAN_ID.NEXTVAL
    INTO :New.УИД
    FROM dual;
    end if;
    



END;
/


CREATE OR REPLACE TRIGGER RABAEV.RRL_t_event_update_remain
  AFTER INSERT
  ON RABAEV.RRL_EVENTS   for each row
declare
  vRemain number;
  procedure UpRemain
    -- Процедура увеличивает остаток в ячейке :new.cell_to на :new.count_event
  is

  begin
    -- смотрим, что лежит в новой ячейке
    -- проверяем только наличие по текущей полете... Хорошо было бы проверить эту ячейку на
    -- наличие в ней чего-нить от других полет и сделать какие-нибудь выводы ...
    select sum(remain) into vRemain
    from RRL_remains
    where cell = :new.cell_to
    and uid_poleta = :new.uid_poleta;

    if vRemain is null then
      -- в ячейке таких полет не обнаружено. добавляем запись
     insert into RRL_remains (uid_poleta, cell, remain , othod_nakl_id , TIME_OF_LAST_UPDATE ) 
     values (:new.uid_poleta, :new.cell_to, :new.count_event , :new.othod_nakl_id , SYSTIMESTAMP );
    else
      -- есть какой-то остаток
      update RRL_remains
      set remain = remain+:new.count_event , othod_nakl_id =  :new.othod_nakl_id , TIME_OF_LAST_UPDATE = SYSTIMESTAMP 
      where cell = :new.cell_to
      and uid_poleta = :new.uid_poleta;
    end if;   
    
  end;


  
  
  
  
  procedure DownRemain
    -- Процедура уменьшает остаток в ячейке :new.cell_from на :new.count_event
  is
  begin
    select sum(remain) into vRemain -- на всякий случай сделали сумму
    from RRL_remains
    where cell = :new.cell_from
    and uid_poleta = :new.uid_poleta;

    if vRemain is null then 
      -- странно, однако, в ячейке не та полета, или ячейка совсем пустая...
      -- запишем отрицательный остаток 
      insert into RRL_remains(uid_poleta, cell, remain ,  TIME_OF_LAST_UPDATE  ) 
      values (:new.uid_poleta , :new.cell_from, -:new.count_event , SYSTIMESTAMP );
    elsif vRemain = :new.count_event then
      -- из ячейки все будет выбрано подчистую, она останется пустая.
      -- поэтому наверно остаток можно удалить
      delete from RRL_remains
      where cell = :new.cell_from
      and uid_poleta = :new.uid_poleta;
    else
      -- остаток какой-то не нулевой остается (может быть и отрицательный)
      -- проапдейтим остаток
      update RRL_remains
      set remain = remain-:new.count_event , TIME_OF_LAST_UPDATE=SYSTIMESTAMP
      where cell = :new.cell_from
      and uid_poleta = :new.uid_poleta;
    end if;   
  end;  

begin

    if(:new.count_event<>0) then
      if :new.type_event = 1 then  
        -- если событие это приемка
        -- добавляем запись в таблицу остатков
        UpRemain;
      elsif :new.type_event = 2 then  
        -- если событие это перемещение
        -- меняем данные в таблице остатков
        DownRemain;
        UpRemain;
      elsif :new.type_event = 3 then  
        -- если событие это отбор
        DownRemain;
      end if;
    end if;
  
end;
/


CREATE OR REPLACE TRIGGER RABAEV.ORDER_MOV_HIST_TRG
BEFORE INSERT 
ON RABAEV.ORDER_MOV_HIST FOR EACH ROW
DECLARE
BEGIN

if :New.ID is null then

  SELECT RABAEV.ORDER_MOV_HIST_ID.NEXTVAL
    INTO :New.ID 
        FROM dual;
        
end if;
    
 

END;
/


CREATE OR REPLACE TRIGGER RABAEV.RRL_TR_VEHICLE_TRG
BEFORE INSERT 
ON RABAEV.RRL_TR_VEHICLE FOR EACH ROW
DECLARE
BEGIN

    if :New.ID is null then

      SELECT  RABAEV.RRL_TR_VEHICLE_SQ.NEXTVAL 
        INTO   :New.ID 
            FROM dual;           
    end if;
        

END;
/


CREATE OR REPLACE TRIGGER RABAEV.RRL_SBORKA_PALLETS_TRG
BEFORE INSERT 
ON RABAEV.RRL_SBORKA_PALLETS FOR EACH ROW
DECLARE
BEGIN


if :New.ID is null then
  SELECT RRL_SBORKA_PALLETS_SQ.NEXTVAL
    INTO :New.ID
    FROM dual;
    end if;
 

  SELECT SYSTIMESTAMP
    INTO :New.CREATE_DATE
    FROM dual;


END;
/


CREATE OR REPLACE TRIGGER RABAEV.RRL_SBORKA_PALLETS_HISTORY_TRG
BEFORE INSERT 
ON RABAEV.RRL_SBORKA_PALLETS_HISTORY FOR EACH ROW
DECLARE
BEGIN

if :New.ID is null then

  SELECT  RABAEV.RRL_SBORKA_PALLETS_HISTSQ.NEXTVAL 
    INTO   :New.ID 
        FROM dual;
        
        
    SELECT  SYSDATE 
    INTO   :New.TIME1 
        FROM dual;      
        
end if;
    
 

END;
/


CREATE OR REPLACE TRIGGER RABAEV.RRL_TR_VODITEL_TRG
BEFORE INSERT 
ON RABAEV.RRL_TR_VODITEL FOR EACH ROW
DECLARE
BEGIN

    if :New.ID is null then

      SELECT  RABAEV.RRL_TR_VODITEL_SQ.NEXTVAL 
        INTO   :New.ID 
            FROM dual;           
    end if;
        

END;
/


ALTER TABLE RABAEV.RRL_ARTICULS ADD (
  CONSTRAINT RRL_ARTICULS_PK
 PRIMARY KEY
 (ACTICUL)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD ADD (
  CONSTRAINT RRL_PRIHOD_NAKLAD_PK
 PRIMARY KEY
 (SM_NAKLAD_NUMBER));

ALTER TABLE RABAEV.RRL_PALLETS ADD (
  CONSTRAINT RRL_PALLETS_PK
 PRIMARY KEY
 (UID_PALLET)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TRANSPORT_TASK ADD (
  CONSTRAINT RRL_TRANSPORT_TASK_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TR_VEHICLE ADD (
  CONSTRAINT RRL_TR_VEHICLE_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TR_VODITEL ADD (
  CONSTRAINT RRL_TR_VODITEL_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_ADDR ADD (
  CONSTRAINT RRL_ADDR_PK
 PRIMARY KEY
 (ADDR)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_ARTICUL_MODS ADD (
  CONSTRAINT RRL_ARTICUL_MODS_ID
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_SBORKA_PALLETS ADD (
  CONSTRAINT RRL_SBORKA_PALLETS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_SBORKA_PALLET_ROWS ADD (
  CONSTRAINT RRL_SBORKA_PALLET_ROWS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TRANSPORT_PRICE ADD (
  CONSTRAINT RRL_TRANSPORT_PRICE_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TT_DOCK ADD (
  CONSTRAINT RRL_TT_DOCK_PK
 PRIMARY KEY
 (DOCK)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TT_ZONES ADD (
  CONSTRAINT RRL_TT_ZONES_PK
 PRIMARY KEY
 (SUB_ZONE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RUSERS ADD (
  CONSTRAINT RUSERS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD_ROWS ADD (
  CONSTRAINT RRL_PRIHOD_NAKLAD_ROWS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD_ROWS ADD (
  CONSTRAINT RRL_OTHOD_NAKLAD_ROWS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD ADD (
  CONSTRAINT RRL_OTHOD_NAKLAD_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_INVETARIZ ADD (
  CONSTRAINT RRL_INVETARIZ_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_INVENTARIZ_LINES ADD (
  CONSTRAINT RRL_INVENTARIZ_LINES_PK
 PRIMARY KEY
 (ID_LINE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_CELLS ADD (
  CONSTRAINT RRL_CELLS_PK
 PRIMARY KEY
 (CELL)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_EVENTS ADD (
  CONSTRAINT RRL_EVENTS_PK
 PRIMARY KEY
 (ID_EVENT)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.ORDER_MOV_HIST ADD (
  CONSTRAINT ORDER_MOV_HIST_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.ORDER_AUDIT_ERROR_LINES ADD (
  CONSTRAINT ORDER_AUDIT_LINES_PK
 PRIMARY KEY
 (ORDER_NUMBER, UID1)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.LOT_AUDIT ADD (
  CONSTRAINT LOT_AUDIT_PK
 PRIMARY KEY
 (SSCC)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.USER_GROUP ADD (
  CONSTRAINT USER_GROUP_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RIGHTS ADD (
  CONSTRAINT RIGHTS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_BILL_ORDERS ADD (
  CONSTRAINT RRL_BILL_ORDERS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_BILL_COMPANY ADD (
  CONSTRAINT RRL_BILL_COMPANY_PK
 PRIMARY KEY
 (COMPANYNAME)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_SBORKA_PALLETS_COND ADD (
  CONSTRAINT RRL_SBORKA_PALLETS_COND_PK
 PRIMARY KEY
 (COND)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_VERSIONS ADD (
  CONSTRAINT RRL_VERSIONS_PK
 PRIMARY KEY
 (VERSION)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_HISTORY_NOTES ADD (
  CONSTRAINT RRL_HISTORY_NOTES_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TT_PATH ADD (
  CONSTRAINT RRL_TT_PATH_PK
 PRIMARY KEY
 (PATH1)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_TRANSPORT_TYPE ADD (
  CONSTRAINT RRL_TRANSPORT_TYPE_PK
 PRIMARY KEY
 (TRANSPORTTYPE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE RABAEV.RRL_BILLING ADD (
  CONSTRAINT RRL_BILLING_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

