ALTER TABLE RABAEV.RRL_TT_DOCK
  DROP CONSTRAINT RRL_TT_DOCK_PK;

ALTER TABLE RABAEV.RRL_TT_DOCK ADD (
  CONSTRAINT RRL_TT_DOCK_PK
 PRIMARY KEY
 (DOCK));

ALTER TABLE RABAEV.RRL_TT_ZONES
  DROP CONSTRAINT RRL_TT_ZONES_PK;

ALTER TABLE RABAEV.RRL_TT_ZONES ADD (
  CONSTRAINT RRL_TT_ZONES_PK
 PRIMARY KEY
 (SUB_ZONE));

ALTER TABLE RABAEV.RRL_TT_PATH
  DROP CONSTRAINT RRL_TT_PATH_PK;

ALTER TABLE RABAEV.RRL_TT_PATH ADD (
  CONSTRAINT RRL_TT_PATH_PK
 PRIMARY KEY
 (PATH1));

ALTER TABLE RABAEV.RRL_BILL_ORDERS
  DROP CONSTRAINT RRL_BILL_ORDERS_PK;

ALTER TABLE RABAEV.RRL_BILL_ORDERS ADD (
  CONSTRAINT RRL_BILL_ORDERS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_VERSIONS
  DROP CONSTRAINT RRL_VERSIONS_PK;

ALTER TABLE RABAEV.RRL_VERSIONS ADD (
  CONSTRAINT RRL_VERSIONS_PK
 PRIMARY KEY
 (VERSION));

ALTER TABLE RABAEV.RRL_HISTORY_NOTES
  DROP CONSTRAINT RRL_HISTORY_NOTES_PK;

ALTER TABLE RABAEV.RRL_HISTORY_NOTES ADD (
  CONSTRAINT RRL_HISTORY_NOTES_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_BILL_COMPANY
  DROP CONSTRAINT RRL_BILL_COMPANY_PK;

ALTER TABLE RABAEV.RRL_BILL_COMPANY ADD (
  CONSTRAINT RRL_BILL_COMPANY_PK
 PRIMARY KEY
 (COMPANYNAME));

ALTER TABLE RABAEV.RRL_TRANSPORT_PRICE
  DROP CONSTRAINT RRL_TRANSPORT_PRICE_PK;

ALTER TABLE RABAEV.RRL_TRANSPORT_PRICE ADD (
  CONSTRAINT RRL_TRANSPORT_PRICE_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.USER_GROUP
  DROP CONSTRAINT USER_GROUP_PK;

ALTER TABLE RABAEV.USER_GROUP ADD (
  CONSTRAINT USER_GROUP_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_ADDR
  DROP CONSTRAINT RRL_ADDR_PK;

ALTER TABLE RABAEV.RRL_ADDR ADD (
  CONSTRAINT RRL_ADDR_PK
 PRIMARY KEY
 (ADDR));

ALTER TABLE RABAEV.RRL_BILLING
  DROP CONSTRAINT RRL_BILLING_PK;

ALTER TABLE RABAEV.RRL_BILLING ADD (
  CONSTRAINT RRL_BILLING_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_TRANSPORT_TYPE
  DROP CONSTRAINT RRL_TRANSPORT_TYPE_PK;

ALTER TABLE RABAEV.RRL_TRANSPORT_TYPE ADD (
  CONSTRAINT RRL_TRANSPORT_TYPE_PK
 PRIMARY KEY
 (TRANSPORTTYPE));

ALTER TABLE RABAEV."BIN$8UzdV2u7Sv6b5lXGeOkI/w==$0"
  DROP CONSTRAINT "BIN$CAL6NCiJStK4kQJIhWuBUw==$0";

ALTER TABLE RABAEV."BIN$8UzdV2u7Sv6b5lXGeOkI/w==$0" ADD (
  CONSTRAINT "BIN$CAL6NCiJStK4kQJIhWuBUw==$0"
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_SBORKA_PALLETS_COND
  DROP CONSTRAINT RRL_SBORKA_PALLETS_COND_PK;

ALTER TABLE RABAEV.RRL_SBORKA_PALLETS_COND ADD (
  CONSTRAINT RRL_SBORKA_PALLETS_COND_PK
 PRIMARY KEY
 (COND));

ALTER TABLE RABAEV.RRL_TRANSPORT_TASK
  DROP CONSTRAINT RRL_TRANSPORT_TASK_PK;

ALTER TABLE RABAEV.RRL_TRANSPORT_TASK ADD (
  CONSTRAINT RRL_TRANSPORT_TASK_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_ARTICUL_MODS
  DROP CONSTRAINT RRL_ARTICUL_MODS_ID;

ALTER TABLE RABAEV.RRL_ARTICUL_MODS ADD (
  CONSTRAINT RRL_ARTICUL_MODS_ID
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_TR_VEHICLE
  DROP CONSTRAINT RRL_TR_VEHICLE_PK;

ALTER TABLE RABAEV.RRL_TR_VEHICLE ADD (
  CONSTRAINT RRL_TR_VEHICLE_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RIGHTS
  DROP CONSTRAINT RIGHTS_PK;

ALTER TABLE RABAEV.RIGHTS ADD (
  CONSTRAINT RIGHTS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_TR_VODITEL
  DROP CONSTRAINT RRL_TR_VODITEL_PK;

ALTER TABLE RABAEV.RRL_TR_VODITEL ADD (
  CONSTRAINT RRL_TR_VODITEL_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_SBORKA_PALLETS
  DROP CONSTRAINT RRL_SBORKA_PALLETS_PK;

ALTER TABLE RABAEV.RRL_SBORKA_PALLETS ADD (
  CONSTRAINT RRL_SBORKA_PALLETS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_SBORKA_PALLET_ROWS
  DROP CONSTRAINT RRL_SBORKA_PALLET_ROWS_PK;

ALTER TABLE RABAEV.RRL_SBORKA_PALLET_ROWS ADD (
  CONSTRAINT RRL_SBORKA_PALLET_ROWS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.LOT_AUDIT
  DROP CONSTRAINT LOT_AUDIT_PK;

ALTER TABLE RABAEV.LOT_AUDIT ADD (
  CONSTRAINT LOT_AUDIT_PK
 PRIMARY KEY
 (SSCC));

ALTER TABLE RABAEV.ORDER_AUDIT_ERROR_LINES
  DROP CONSTRAINT ORDER_AUDIT_LINES_PK;

ALTER TABLE RABAEV.ORDER_AUDIT_ERROR_LINES ADD (
  CONSTRAINT ORDER_AUDIT_LINES_PK
 PRIMARY KEY
 (ORDER_NUMBER, UID1));

ALTER TABLE RABAEV.ORDER_MOV_HIST
  DROP CONSTRAINT ORDER_MOV_HIST_PK;

ALTER TABLE RABAEV.ORDER_MOV_HIST ADD (
  CONSTRAINT ORDER_MOV_HIST_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_EVENTS
  DROP CONSTRAINT RRL_EVENTS_PK;

ALTER TABLE RABAEV.RRL_EVENTS ADD (
  CONSTRAINT RRL_EVENTS_PK
 PRIMARY KEY
 (ID_EVENT));

ALTER TABLE RABAEV.RRL_ARTICULS
  DROP CONSTRAINT RRL_ARTICULS_PK;

ALTER TABLE RABAEV.RRL_ARTICULS ADD (
  CONSTRAINT RRL_ARTICULS_PK
 PRIMARY KEY
 (ACTICUL));

ALTER TABLE RABAEV.RRL_CELLS
  DROP CONSTRAINT RRL_CELLS_PK;

ALTER TABLE RABAEV.RRL_CELLS ADD (
  CONSTRAINT RRL_CELLS_PK
 PRIMARY KEY
 (CELL));

ALTER TABLE RABAEV.RRL_INVENTARIZ_LINES
  DROP CONSTRAINT RRL_INVENTARIZ_LINES_PK;

ALTER TABLE RABAEV.RRL_INVENTARIZ_LINES ADD (
  CONSTRAINT RRL_INVENTARIZ_LINES_PK
 PRIMARY KEY
 (ID_LINE));

ALTER TABLE RABAEV.RRL_INVETARIZ
  DROP CONSTRAINT RRL_INVETARIZ_PK;

ALTER TABLE RABAEV.RRL_INVETARIZ ADD (
  CONSTRAINT RRL_INVETARIZ_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD
  DROP CONSTRAINT RRL_OTHOD_NAKLAD_PK;

ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD ADD (
  CONSTRAINT RRL_OTHOD_NAKLAD_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD_ROWS
  DROP CONSTRAINT RRL_OTHOD_NAKLAD_ROWS_PK;

ALTER TABLE RABAEV.RRL_OTHOD_NAKLAD_ROWS ADD (
  CONSTRAINT RRL_OTHOD_NAKLAD_ROWS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RRL_PALLETS
  DROP CONSTRAINT RRL_PALLETS_PK;

ALTER TABLE RABAEV.RRL_PALLETS ADD (
  CONSTRAINT RRL_PALLETS_PK
 PRIMARY KEY
 (UID_PALLET));

ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD
  DROP CONSTRAINT RRL_PRIHOD_NAKLAD_PK;

ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD ADD (
  CONSTRAINT RRL_PRIHOD_NAKLAD_PK
 PRIMARY KEY
 (SM_NAKLAD_NUMBER));

ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD_ROWS
  DROP CONSTRAINT RRL_PRIHOD_NAKLAD_ROWS_PK;

ALTER TABLE RABAEV.RRL_PRIHOD_NAKLAD_ROWS ADD (
  CONSTRAINT RRL_PRIHOD_NAKLAD_ROWS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE RABAEV.RUSERS
  DROP CONSTRAINT RUSERS_PK;

ALTER TABLE RABAEV.RUSERS ADD (
  CONSTRAINT RUSERS_PK
 PRIMARY KEY
 (ID));

