-- Sprint 11 rollback: удалить таблицы и последовательности нормативов

DROP TABLE RABAEV.RRL_TT_OPERATIONS CASCADE CONSTRAINTS;
DROP TABLE RABAEV.RRL_TRANSPORT_NORMS CASCADE CONSTRAINTS;
DROP SEQUENCE RABAEV.SEQ_TT_OPERATIONS;
DROP SEQUENCE RABAEV.SEQ_TRANSPORT_NORMS;

COMMIT;
