-- Migration 041 — Rollback
-- Удаляет таблицу RRL_TOPOLOGY_PICK_FACE_SLOT и добавленные столбцы.
-- ОСТОРОЖНО: уничтожает все данные о мелкоштучных слотах.

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RABAEV.RRL_TOPOLOGY_PICK_FACE_SLOT CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE RABAEV.RRL_TOPOLOGY_PICK_FACE_SLOT_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RABAEV.RRL_TOPOLOGY_AISLE DROP COLUMN AISLE_WIDTH_M';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RABAEV.RRL_TOPOLOGY_AISLE DROP COLUMN DISTANCE_FROM_START_M';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RABAEV.RRL_TOPOLOGY_AISLE DROP COLUMN AISLE_LABEL';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
COMMIT;
