-- 052_rollback.sql — откат Sprint 8
-- Удаляет индексы и колонку APPLIED_AT.

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX RABAEV.IDX_RLADM_FROM';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX RABAEV.IDX_RLP_PLANDATE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM user_tab_columns
   WHERE table_name = 'RRL_PLANNER_PLANS'
     AND column_name = 'APPLIED_AT';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE RABAEV.RRL_PLANNER_PLANS DROP COLUMN APPLIED_AT';
  END IF;
END;
/

COMMIT;
