from typing import Protocol


class SupplyPort(Protocol):
    def receive(self, raw: bytes, actor: str) -> dict: ...
    def list(self, warehouse_id: int | None, limit: int = 100) -> list[dict]: ...
    def get(self, order_id: str) -> dict: ...
    def by_receipt_document(self, document_id: int) -> dict: ...


class AcknowledgementPort(Protocol):
    def receive(self, raw: bytes, actor: str) -> dict: ...
    def list_events(self, limit: int) -> list[dict]: ...
    def retry(self, event_id: str) -> dict: ...
