--
-- Create Database Script 
--   Database Version   : 10.2.0.1.0 
--   TOAD Version       : 9.1.0.62 
--   DB Connect String  : REFSTOCK 
--   Script Created by  : RABAEV 
--   Script Created at  : 28.01.2010 6:34:25 
--   Physical Location  :  
--   Notes              :  
--

--
-- SYSAUX  (Tablespace) 
--
CREATE TABLESPACE SYSAUX DATAFILE 
  '/u01/app/oracle/oradata/REFSTOCK/sysaux01.dbf' SIZE 1160M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- SYSTEM  (Tablespace) 
--
CREATE TABLESPACE SYSTEM DATAFILE 
  '/u01/app/oracle/oradata/REFSTOCK/system01.dbf' SIZE 640M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
FLASHBACK ON;


--
-- TEMP  (Tablespace) 
--
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  '/u01/app/oracle/oradata/REFSTOCK/temp01.dbf' SIZE 317M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


--
-- UNDOTBS1  (Tablespace) 
--
CREATE UNDO TABLESPACE UNDOTBS1 DATAFILE 
  '/u01/app/oracle/oradata/REFSTOCK/undotbs01.dbf' SIZE 2035M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
ONLINE
RETENTION NOGUARANTEE
BLOCKSIZE 8K
FLASHBACK ON;


--
-- USERS  (Tablespace) 
--
CREATE TABLESPACE USERS DATAFILE 
  '/u01/app/oracle/oradata/REFSTOCK/users01.dbf' SIZE 5832960K AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


ALTER DATABASE ADD LOGFILE GROUP 1(
  '/u01/app/oracle/oradata/REFSTOCK/redo01.log')
    SIZE 50M;


ALTER DATABASE ADD LOGFILE GROUP 2(
  '/u01/app/oracle/oradata/REFSTOCK/redo02.log')
    SIZE 50M;


ALTER DATABASE ADD LOGFILE GROUP 3(
  '/u01/app/oracle/oradata/REFSTOCK/redo03.log')
    SIZE 50M;


--
-- DEFAULT  (Profile) 
--
CREATE PROFILE DEFAULT LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 10
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME UNLIMITED
  PASSWORD_GRACE_TIME UNLIMITED
  PASSWORD_VERIFY_FUNCTION NULL;


--
-- MONITORING_PROFILE  (Profile) 
--
CREATE PROFILE MONITORING_PROFILE LIMIT
  SESSIONS_PER_USER DEFAULT
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME DEFAULT
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS UNLIMITED
  PASSWORD_LIFE_TIME DEFAULT
  PASSWORD_REUSE_TIME DEFAULT
  PASSWORD_REUSE_MAX DEFAULT
  PASSWORD_LOCK_TIME DEFAULT
  PASSWORD_GRACE_TIME DEFAULT
  PASSWORD_VERIFY_FUNCTION DEFAULT;


--
-- CONNECT  (Role) 
--
CREATE ROLE CONNECT NOT IDENTIFIED;



--
-- RESOURCE  (Role) 
--
CREATE ROLE RESOURCE NOT IDENTIFIED;



--
-- DBA  (Role) 
--
CREATE ROLE DBA NOT IDENTIFIED;



--
-- SELECT_CATALOG_ROLE  (Role) 
--
CREATE ROLE SELECT_CATALOG_ROLE NOT IDENTIFIED;



--
-- EXECUTE_CATALOG_ROLE  (Role) 
--
CREATE ROLE EXECUTE_CATALOG_ROLE NOT IDENTIFIED;



--
-- DELETE_CATALOG_ROLE  (Role) 
--
CREATE ROLE DELETE_CATALOG_ROLE NOT IDENTIFIED;



--
-- EXP_FULL_DATABASE  (Role) 
--
CREATE ROLE EXP_FULL_DATABASE NOT IDENTIFIED;



--
-- IMP_FULL_DATABASE  (Role) 
--
CREATE ROLE IMP_FULL_DATABASE NOT IDENTIFIED;



--
-- RECOVERY_CATALOG_OWNER  (Role) 
--
CREATE ROLE RECOVERY_CATALOG_OWNER NOT IDENTIFIED;



--
-- GATHER_SYSTEM_STATISTICS  (Role) 
--
CREATE ROLE GATHER_SYSTEM_STATISTICS NOT IDENTIFIED;



--
-- LOGSTDBY_ADMINISTRATOR  (Role) 
--
CREATE ROLE LOGSTDBY_ADMINISTRATOR NOT IDENTIFIED;



--
-- AQ_ADMINISTRATOR_ROLE  (Role) 
--
CREATE ROLE AQ_ADMINISTRATOR_ROLE NOT IDENTIFIED;



--
-- AQ_USER_ROLE  (Role) 
--
CREATE ROLE AQ_USER_ROLE NOT IDENTIFIED;



--
-- GLOBAL_AQ_USER_ROLE  (Role) 
--
CREATE ROLE GLOBAL_AQ_USER_ROLE IDENTIFIED GLOBALLY;



--
-- SCHEDULER_ADMIN  (Role) 
--
CREATE ROLE SCHEDULER_ADMIN NOT IDENTIFIED;



--
-- HS_ADMIN_ROLE  (Role) 
--
CREATE ROLE HS_ADMIN_ROLE NOT IDENTIFIED;



--
-- AUTHENTICATEDUSER  (Role) 
--
CREATE ROLE AUTHENTICATEDUSER NOT IDENTIFIED;



--
-- OEM_ADVISOR  (Role) 
--
CREATE ROLE OEM_ADVISOR NOT IDENTIFIED;



--
-- OEM_MONITOR  (Role) 
--
CREATE ROLE OEM_MONITOR NOT IDENTIFIED;



--
-- WM_ADMIN_ROLE  (Role) 
--
CREATE ROLE WM_ADMIN_ROLE NOT IDENTIFIED;



--
-- JAVAUSERPRIV  (Role) 
--
CREATE ROLE JAVAUSERPRIV NOT IDENTIFIED;



--
-- JAVAIDPRIV  (Role) 
--
CREATE ROLE JAVAIDPRIV NOT IDENTIFIED;



--
-- JAVASYSPRIV  (Role) 
--
CREATE ROLE JAVASYSPRIV NOT IDENTIFIED;



--
-- JAVADEBUGPRIV  (Role) 
--
CREATE ROLE JAVADEBUGPRIV NOT IDENTIFIED;



--
-- EJBCLIENT  (Role) 
--
CREATE ROLE EJBCLIENT NOT IDENTIFIED;



--
-- JAVA_ADMIN  (Role) 
--
CREATE ROLE JAVA_ADMIN NOT IDENTIFIED;



--
-- JAVA_DEPLOY  (Role) 
--
CREATE ROLE JAVA_DEPLOY NOT IDENTIFIED;



--
-- CTXAPP  (Role) 
--
CREATE ROLE CTXAPP NOT IDENTIFIED;



--
-- XDBADMIN  (Role) 
--
CREATE ROLE XDBADMIN NOT IDENTIFIED;



--
-- XDBWEBSERVICES  (Role) 
--
CREATE ROLE XDBWEBSERVICES NOT IDENTIFIED;



--
-- OLAP_DBA  (Role) 
--
CREATE ROLE OLAP_DBA NOT IDENTIFIED;



--
-- OLAP_USER  (Role) 
--
CREATE ROLE OLAP_USER NOT IDENTIFIED;



--
-- MGMT_USER  (Role) 
--
CREATE ROLE MGMT_USER NOT IDENTIFIED;



--
-- SYSTEM  (Rollback Segment) 
--
CREATE ROLLBACK SEGMENT SYSTEM
  TABLESPACE SYSTEM
  STORAGE    (
              INITIAL          112K
              MINEXTENTS       1
              MAXEXTENTS       32765
             );
ALTER ROLLBACK SEGMENT SYSTEM ONLINE;


--
-- ANONYMOUS  (User) 
--
CREATE USER ANONYMOUS
  IDENTIFIED BY VALUES 'anonymous'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for ANONYMOUS 
  GRANT CREATE SESSION TO ANONYMOUS;


--
-- CTXSYS  (User) 
--
CREATE USER CTXSYS
  IDENTIFIED BY VALUES '71E687F036AD56E5'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for CTXSYS 
  GRANT RESOURCE TO CTXSYS;
  GRANT CTXAPP TO CTXSYS WITH ADMIN OPTION;
  ALTER USER CTXSYS DEFAULT ROLE ALL;
  -- 7 System Privileges for CTXSYS 
  GRANT UNLIMITED TABLESPACE TO CTXSYS;
  GRANT CREATE VIEW TO CTXSYS;
  GRANT ALTER SESSION TO CTXSYS;
  GRANT CREATE SYNONYM TO CTXSYS;
  GRANT DROP PUBLIC SYNONYM TO CTXSYS;
  GRANT CREATE SESSION TO CTXSYS;
  GRANT CREATE PUBLIC SYNONYM TO CTXSYS;


--
-- DBSNMP  (User) 
--
CREATE USER DBSNMP
  IDENTIFIED BY VALUES '0C1C530B2D8A74C6'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE MONITORING_PROFILE
  ACCOUNT UNLOCK;
  -- 1 Role for DBSNMP 
  GRANT OEM_MONITOR TO DBSNMP;
  ALTER USER DBSNMP DEFAULT ROLE ALL;
  -- 4 System Privileges for DBSNMP 
  GRANT UNLIMITED TABLESPACE TO DBSNMP;
  GRANT SELECT ANY DICTIONARY TO DBSNMP;
  GRANT CREATE PROCEDURE TO DBSNMP;
  GRANT CREATE TABLE TO DBSNMP;


--
-- DIP  (User) 
--
CREATE USER DIP
  IDENTIFIED BY VALUES 'CE4A36B8E06CA59C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for DIP 
  GRANT CREATE SESSION TO DIP;


--
-- DMSYS  (User) 
--
CREATE USER DMSYS
  IDENTIFIED BY VALUES 'BFBA5A553FD9E28A'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 15 System Privileges for DMSYS 
  GRANT CREATE JOB TO DMSYS;
  GRANT DROP PUBLIC SYNONYM TO DMSYS;
  GRANT QUERY REWRITE TO DMSYS;
  GRANT ALTER SESSION TO DMSYS;
  GRANT CREATE TRIGGER TO DMSYS;
  GRANT CREATE TYPE TO DMSYS;
  GRANT CREATE PUBLIC SYNONYM TO DMSYS;
  GRANT ALTER SYSTEM TO DMSYS;
  GRANT CREATE PROCEDURE TO DMSYS;
  GRANT CREATE SESSION TO DMSYS;
  GRANT CREATE SEQUENCE TO DMSYS;
  GRANT CREATE VIEW TO DMSYS;
  GRANT CREATE SYNONYM TO DMSYS;
  GRANT CREATE LIBRARY TO DMSYS;
  GRANT CREATE TABLE TO DMSYS;
  -- 1 Tablespace Quota for DMSYS 
  ALTER USER DMSYS QUOTA 200M ON SYSAUX;


--
-- EXFSYS  (User) 
--
CREATE USER EXFSYS
  IDENTIFIED BY VALUES '66F4EF5650C20355'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for EXFSYS 
  GRANT CONNECT TO EXFSYS;
  GRANT RESOURCE TO EXFSYS;
  ALTER USER EXFSYS DEFAULT ROLE ALL;
  -- 8 System Privileges for EXFSYS 
  GRANT CREATE OPERATOR TO EXFSYS;
  GRANT CREATE JOB TO EXFSYS;
  GRANT ADMINISTER DATABASE TRIGGER TO EXFSYS;
  GRANT MANAGE SCHEDULER TO EXFSYS;
  GRANT CREATE ANY TRIGGER TO EXFSYS;
  GRANT CREATE LIBRARY TO EXFSYS;
  GRANT CREATE INDEXTYPE TO EXFSYS;
  GRANT UNLIMITED TABLESPACE TO EXFSYS;


--
-- MDDATA  (User) 
--
CREATE USER MDDATA
  IDENTIFIED BY VALUES 'DF02A496267DEE66'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for MDDATA 
  GRANT RESOURCE TO MDDATA;
  GRANT CONNECT TO MDDATA;
  ALTER USER MDDATA DEFAULT ROLE ALL;
  -- 1 System Privilege for MDDATA 
  GRANT UNLIMITED TABLESPACE TO MDDATA;


--
-- MDSYS  (User) 
--
CREATE USER MDSYS
  IDENTIFIED BY VALUES '72979A94BAD2AF80'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for MDSYS 
  GRANT CONNECT TO MDSYS;
  GRANT RESOURCE TO MDSYS;
  ALTER USER MDSYS DEFAULT ROLE ALL;
  -- 14 System Privileges for MDSYS 
  GRANT CREATE VIEW TO MDSYS;
  GRANT DROP PUBLIC SYNONYM TO MDSYS;
  GRANT DELETE ANY TABLE TO MDSYS;
  GRANT UNLIMITED TABLESPACE TO MDSYS;
  GRANT CREATE INDEXTYPE TO MDSYS;
  GRANT CREATE OPERATOR TO MDSYS;
  GRANT CREATE TABLE TO MDSYS;
  GRANT CREATE PUBLIC SYNONYM TO MDSYS;
  GRANT CREATE PROCEDURE TO MDSYS;
  GRANT CREATE LIBRARY TO MDSYS;
  GRANT CREATE TYPE TO MDSYS;
  GRANT CREATE SEQUENCE TO MDSYS;
  GRANT CREATE ANY TRIGGER TO MDSYS;
  GRANT CREATE SESSION TO MDSYS;
  -- 5 Java Privileges for MDSYS 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'md/lib/*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
  SYS.DBMS_JAVA.DISABLE_PERMISSION
    (key => KEYNUM);
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'sdo/demos/georaster/jlibs/*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
  SYS.DBMS_JAVA.DISABLE_PERMISSION
    (key => KEYNUM);
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'md\lib\*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'sdo\demos\georaster\jlibs\*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'getClassLoader'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/


--
-- MGMT_VIEW  (User) 
--
CREATE USER MGMT_VIEW
  IDENTIFIED BY VALUES 'CF114B59593139DA'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for MGMT_VIEW 
  GRANT MGMT_USER TO MGMT_VIEW;
  ALTER USER MGMT_VIEW DEFAULT ROLE ALL;


--
-- OLAPSYS  (User) 
--
CREATE USER OLAPSYS
  IDENTIFIED BY VALUES '3FB8EF9DB538647C'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for OLAPSYS 
  GRANT RESOURCE TO OLAPSYS;
  GRANT OLAP_DBA TO OLAPSYS;
  ALTER USER OLAPSYS DEFAULT ROLE ALL;
  -- 13 System Privileges for OLAPSYS 
  GRANT CREATE VIEW TO OLAPSYS;
  GRANT CREATE SESSION TO OLAPSYS;
  GRANT CREATE PROCEDURE TO OLAPSYS;
  GRANT DROP ANY DIMENSION TO OLAPSYS;
  GRANT SELECT ANY TABLE TO OLAPSYS;
  GRANT DROP ANY SYNONYM TO OLAPSYS;
  GRANT CREATE SEQUENCE TO OLAPSYS;
  GRANT DROP PUBLIC SYNONYM TO OLAPSYS;
  GRANT UNLIMITED TABLESPACE TO OLAPSYS;
  GRANT CREATE ANY SYNONYM TO OLAPSYS;
  GRANT CREATE ANY DIMENSION TO OLAPSYS;
  GRANT CREATE TABLE TO OLAPSYS;
  GRANT CREATE PUBLIC SYNONYM TO OLAPSYS;
  -- 1 Tablespace Quota for OLAPSYS 
  ALTER USER OLAPSYS QUOTA UNLIMITED ON SYSAUX;


--
-- ORDPLUGINS  (User) 
--
CREATE USER ORDPLUGINS
  IDENTIFIED BY VALUES '88A2B2C183431F00'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 10 System Privileges for ORDPLUGINS 
  GRANT CREATE OPERATOR TO ORDPLUGINS;
  GRANT DROP PUBLIC SYNONYM TO ORDPLUGINS;
  GRANT CREATE TYPE TO ORDPLUGINS;
  GRANT CREATE PROCEDURE TO ORDPLUGINS;
  GRANT CREATE SESSION TO ORDPLUGINS;
  GRANT CREATE INDEXTYPE TO ORDPLUGINS;
  GRANT UNLIMITED TABLESPACE TO ORDPLUGINS;
  GRANT CREATE TABLE TO ORDPLUGINS;
  GRANT CREATE LIBRARY TO ORDPLUGINS;
  GRANT CREATE PUBLIC SYNONYM TO ORDPLUGINS;


--
-- ORDSYS  (User) 
--
CREATE USER ORDSYS
  IDENTIFIED BY VALUES '7EFA02EC7EA6B86F'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 Role for ORDSYS 
  GRANT JAVAUSERPRIV TO ORDSYS;
  ALTER USER ORDSYS DEFAULT ROLE ALL;
  -- 13 System Privileges for ORDSYS 
  GRANT CREATE INDEXTYPE TO ORDSYS;
  GRANT CREATE OPERATOR TO ORDSYS;
  GRANT CREATE ANY SYNONYM TO ORDSYS;
  GRANT CREATE TYPE TO ORDSYS;
  GRANT CREATE PROCEDURE TO ORDSYS;
  GRANT DROP ANY SYNONYM TO ORDSYS;
  GRANT DROP PUBLIC SYNONYM TO ORDSYS;
  GRANT UNLIMITED TABLESPACE TO ORDSYS;
  GRANT CREATE SESSION TO ORDSYS;
  GRANT CREATE TABLE TO ORDSYS;
  GRANT CREATE LIBRARY TO ORDSYS;
  GRANT CREATE VIEW TO ORDSYS;
  GRANT CREATE PUBLIC SYNONYM TO ORDSYS;
  -- 1 Java Privilege for ORDSYS 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'ORDSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'getClassLoader'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/


--
-- OUTLN  (User) 
--
CREATE USER OUTLN
  IDENTIFIED BY VALUES '4A3BA55E08595C81'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 Role for OUTLN 
  GRANT RESOURCE TO OUTLN;
  ALTER USER OUTLN DEFAULT ROLE ALL;
  -- 3 System Privileges for OUTLN 
  GRANT CREATE SESSION TO OUTLN;
  GRANT UNLIMITED TABLESPACE TO OUTLN;
  GRANT EXECUTE ANY PROCEDURE TO OUTLN;


--
-- RABAEV  (User) 
--
CREATE USER RABAEV
  IDENTIFIED BY VALUES 'C7B4E42B7CAF4C9C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for RABAEV 
  GRANT CONNECT TO RABAEV WITH ADMIN OPTION;
  ALTER USER RABAEV DEFAULT ROLE ALL;
  -- 3 System Privileges for RABAEV 
  GRANT SELECT ANY SEQUENCE TO RABAEV WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO RABAEV WITH ADMIN OPTION;
  GRANT SELECT ANY DICTIONARY TO RABAEV WITH ADMIN OPTION;
  -- 1 Tablespace Quota for RABAEV 
  ALTER USER RABAEV QUOTA UNLIMITED ON USERS;


--
-- REFSTOCK  (User) 
--
CREATE USER REFSTOCK
  IDENTIFIED BY VALUES '880D9FB01B984070'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 32 Roles for REFSTOCK 
  GRANT OLAP_DBA TO REFSTOCK WITH ADMIN OPTION;
  GRANT JAVADEBUGPRIV TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO REFSTOCK WITH ADMIN OPTION;
  GRANT WM_ADMIN_ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT OEM_MONITOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT JAVA_ADMIN TO REFSTOCK WITH ADMIN OPTION;
  GRANT MGMT_USER TO REFSTOCK WITH ADMIN OPTION;
  GRANT OLAP_USER TO REFSTOCK WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO REFSTOCK WITH ADMIN OPTION;
  GRANT JAVAIDPRIV TO REFSTOCK WITH ADMIN OPTION;
  GRANT SELECT_CATALOG_ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CTXAPP TO REFSTOCK WITH ADMIN OPTION;
  GRANT JAVAUSERPRIV TO REFSTOCK WITH ADMIN OPTION;
  GRANT JAVA_DEPLOY TO REFSTOCK WITH ADMIN OPTION;
  GRANT LOGSTDBY_ADMINISTRATOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT JAVASYSPRIV TO REFSTOCK WITH ADMIN OPTION;
  GRANT XDBADMIN TO REFSTOCK WITH ADMIN OPTION;
  GRANT CONNECT TO REFSTOCK WITH ADMIN OPTION;
  GRANT OEM_ADVISOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT DELETE_CATALOG_ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT EJBCLIENT TO REFSTOCK WITH ADMIN OPTION;
  GRANT RESOURCE TO REFSTOCK WITH ADMIN OPTION;
  GRANT HS_ADMIN_ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT AUTHENTICATEDUSER TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE_CATALOG_ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT AQ_ADMINISTRATOR_ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT RECOVERY_CATALOG_OWNER TO REFSTOCK WITH ADMIN OPTION;
  GRANT AQ_USER_ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT GATHER_SYSTEM_STATISTICS TO REFSTOCK WITH ADMIN OPTION;
  GRANT XDBWEBSERVICES TO REFSTOCK WITH ADMIN OPTION;
  GRANT SCHEDULER_ADMIN TO REFSTOCK WITH ADMIN OPTION;
  GRANT DBA TO REFSTOCK WITH ADMIN OPTION;
  ALTER USER REFSTOCK DEFAULT ROLE ALL;
  -- 164 System Privileges for REFSTOCK 
  GRANT FLASHBACK ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY DIMENSION TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY DIMENSION TO REFSTOCK WITH ADMIN OPTION;
  GRANT MANAGE FILE GROUP TO REFSTOCK WITH ADMIN OPTION;
  GRANT UNDER ANY TYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXEMPT IDENTITY POLICY TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE LIBRARY TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY CLUSTER TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP TABLESPACE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT SELECT ANY DICTIONARY TO REFSTOCK WITH ADMIN OPTION;
  GRANT MANAGE TABLESPACE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT RESTRICTED SESSION TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DELETE ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE ANY CLASS TO REFSTOCK WITH ADMIN OPTION;
  GRANT ANALYZE ANY DICTIONARY TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE DIMENSION TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER PROFILE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE TRIGGER TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE ANY LIBRARY TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY SEQUENCE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY INDEX TO REFSTOCK WITH ADMIN OPTION;
  GRANT UNDER ANY VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY INDEXTYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE ANY TYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT AUDIT SYSTEM TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY OUTLINE TO REFSTOCK WITH ADMIN OPTION;
  GRANT COMMENT ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY OPERATOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE SEQUENCE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY OPERATOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY CONTEXT TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE INDEXTYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE OPERATOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT IMPORT FULL DATABASE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY CLUSTER TO REFSTOCK WITH ADMIN OPTION;
  GRANT FORCE TRANSACTION TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE JOB TO REFSTOCK WITH ADMIN OPTION;
  GRANT DEBUG ANY PROCEDURE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY LIBRARY TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ROLLBACK SEGMENT TO REFSTOCK WITH ADMIN OPTION;
  GRANT QUERY REWRITE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY JOB TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE PROCEDURE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE SESSION TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY SQL PROFILE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ADVISOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY INDEXTYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY MATERIALIZED VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY TRIGGER TO REFSTOCK WITH ADMIN OPTION;
  GRANT DEBUG CONNECT SESSION TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY SEQUENCE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY LIBRARY TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY DIRECTORY TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROCEDURE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE DATABASE LINK TO REFSTOCK WITH ADMIN OPTION;
  GRANT INSERT ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT LOCK ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER TABLESPACE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CHANGE NOTIFICATION TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'REFSTOCK',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT ALTER ANY TYPE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'REFSTOCK', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => TRUE);
END;
/
  GRANT CREATE ANY DIMENSION TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE MATERIALIZED VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER RESOURCE COST TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ROLLBACK SEGMENT TO REFSTOCK WITH ADMIN OPTION;
  GRANT ADMINISTER SQL TUNING SET TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY PROCEDURE TO REFSTOCK WITH ADMIN OPTION;
  GRANT AUDIT ANY TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO REFSTOCK WITH ADMIN OPTION;
  GRANT MANAGE SCHEDULER TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY INDEXTYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY TRIGGER TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ALTER ROLLBACK SEGMENT TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXEMPT ACCESS POLICY TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY PROCEDURE TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROGRAM TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'REFSTOCK',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT GRANT ANY PRIVILEGE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER DATABASE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP USER TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY CONTEXT TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY INDEX TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY MATERIALIZED VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ADMINISTER ANY SQL TUNING SET TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY DIRECTORY TO REFSTOCK WITH ADMIN OPTION;
  GRANT ANALYZE ANY TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'REFSTOCK',
  ADMIN_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ON COMMIT REFRESH TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE PUBLIC DATABASE LINK TO REFSTOCK WITH ADMIN OPTION;
  GRANT GRANT ANY OBJECT PRIVILEGE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY LIBRARY TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY PROCEDURE TO REFSTOCK WITH ADMIN OPTION;
  GRANT FORCE ANY TRANSACTION TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DROP ANY OUTLINE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT BECOME USER TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER SYSTEM TO REFSTOCK WITH ADMIN OPTION;
  GRANT SELECT ANY TRANSACTION TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY TYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY INDEX TO REFSTOCK WITH ADMIN OPTION;
  GRANT MERGE ANY VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT UNDER ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY SYNONYM TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT GRANT ANY ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE CLUSTER TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE TABLESPACE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT RESUMABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY CLUSTER TO REFSTOCK WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXPORT FULL DATABASE TO REFSTOCK WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'REFSTOCK',
  GRANT_OPTION => TRUE);
END;
/
  GRANT MANAGE ANY FILE GROUP TO REFSTOCK WITH ADMIN OPTION;
  GRANT GLOBAL QUERY REWRITE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY TRIGGER TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE EXTERNAL JOB TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE ANY INDEXTYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY OPERATOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP PROFILE TO REFSTOCK WITH ADMIN OPTION;
  GRANT BACKUP ANY TABLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER USER TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE USER TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY SYNONYM TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER SESSION TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY SQL PROFILE TO REFSTOCK WITH ADMIN OPTION;
  GRANT ADMINISTER DATABASE TRIGGER TO REFSTOCK WITH ADMIN OPTION;
  GRANT EXECUTE ANY OPERATOR TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY TYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE TYPE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY MATERIALIZED VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE PROFILE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP PUBLIC DATABASE LINK TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE SYNONYM TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY OUTLINE TO REFSTOCK WITH ADMIN OPTION;
  GRANT SELECT ANY SEQUENCE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE VIEW TO REFSTOCK WITH ADMIN OPTION;
  GRANT READ ANY FILE GROUP TO REFSTOCK WITH ADMIN OPTION;
  GRANT ALTER ANY SQL PROFILE TO REFSTOCK WITH ADMIN OPTION;
  GRANT DROP ANY ROLE TO REFSTOCK WITH ADMIN OPTION;
  GRANT CREATE ANY SEQUENCE TO REFSTOCK WITH ADMIN OPTION;
  -- 1 Tablespace Quota for REFSTOCK 
  ALTER USER REFSTOCK QUOTA UNLIMITED ON USERS;


--
-- REF_TEMPL  (User) 
--
CREATE USER REF_TEMPL
  IDENTIFIED BY VALUES 'C0EAAD6A1A4EE62A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 32 Roles for REF_TEMPL 
  GRANT SCHEDULER_ADMIN TO REF_TEMPL WITH ADMIN OPTION;
  GRANT XDBADMIN TO REF_TEMPL WITH ADMIN OPTION;
  GRANT JAVASYSPRIV TO REF_TEMPL WITH ADMIN OPTION;
  GRANT HS_ADMIN_ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT OLAP_USER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT WM_ADMIN_ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT OLAP_DBA TO REF_TEMPL WITH ADMIN OPTION;
  GRANT RESOURCE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EJBCLIENT TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DELETE_CATALOG_ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT XDBWEBSERVICES TO REF_TEMPL WITH ADMIN OPTION;
  GRANT AQ_ADMINISTRATOR_ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT LOGSTDBY_ADMINISTRATOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT JAVADEBUGPRIV TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE_CATALOG_ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT OEM_ADVISOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT JAVAIDPRIV TO REF_TEMPL WITH ADMIN OPTION;
  GRANT GATHER_SYSTEM_STATISTICS TO REF_TEMPL WITH ADMIN OPTION;
  GRANT AUTHENTICATEDUSER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT JAVA_DEPLOY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT JAVAUSERPRIV TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CONNECT TO REF_TEMPL WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT MGMT_USER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT JAVA_ADMIN TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CTXAPP TO REF_TEMPL WITH ADMIN OPTION;
  GRANT OEM_MONITOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DBA TO REF_TEMPL WITH ADMIN OPTION;
  GRANT AQ_USER_ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT RECOVERY_CATALOG_OWNER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT SELECT_CATALOG_ROLE TO REF_TEMPL WITH ADMIN OPTION;
  ALTER USER REF_TEMPL DEFAULT ROLE ALL;
  -- 164 System Privileges for REF_TEMPL 
  GRANT CREATE TYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY MATERIALIZED VIEW TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE PROFILE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP PUBLIC DATABASE LINK TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE SYNONYM TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT RESTRICTED SESSION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY OPERATOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY JOB TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE PROCEDURE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE SESSION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT MANAGE SCHEDULER TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT SELECT ANY TRANSACTION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY TYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY INDEX TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY OUTLINE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT SELECT ANY SEQUENCE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE VIEW TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DELETE ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY CONTEXT TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE INDEXTYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE OPERATOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY SQL PROFILE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ADVISOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY INDEXTYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY MATERIALIZED VIEW TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY TRIGGER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY INDEXTYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY TRIGGER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY VIEW TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'REF_TEMPL',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT MERGE ANY VIEW TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXPORT FULL DATABASE TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT READ ANY FILE GROUP TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY SQL PROFILE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY SEQUENCE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT BACKUP ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER USER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE USER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXEMPT IDENTITY POLICY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE LIBRARY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY CLUSTER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP TABLESPACE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT UNDER ANY VIEW TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY INDEXTYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE ANY TYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT AUDIT SYSTEM TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ROLLBACK SEGMENT TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'REF_TEMPL', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => TRUE);
END;
/
  GRANT CREATE ANY DIMENSION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE MATERIALIZED VIEW TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER RESOURCE COST TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ROLLBACK SEGMENT TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY CONTEXT TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY INDEX TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY PROCEDURE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT FORCE ANY TRANSACTION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT GRANT ANY ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE CLUSTER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE TABLESPACE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY SYNONYM TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER SESSION TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE ANY OUTLINE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT COMMENT ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT QUERY REWRITE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY VIEW TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ADMINISTER SQL TUNING SET TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY PROCEDURE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT AUDIT ANY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY MATERIALIZED VIEW TO REF_TEMPL WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DROP ANY SQL PROFILE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ADMINISTER DATABASE TRIGGER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE ANY OPERATOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY TYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT SELECT ANY DICTIONARY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT MANAGE TABLESPACE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY OPERATOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE SEQUENCE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ADMINISTER ANY SQL TUNING SET TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY DIRECTORY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ANALYZE ANY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY OUTLINE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ROLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT BECOME USER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER SYSTEM TO REF_TEMPL WITH ADMIN OPTION;
  GRANT RESUMABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY CLUSTER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT FLASHBACK ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY DIMENSION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY DIMENSION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE ANY CLASS TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ANALYZE ANY DICTIONARY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE DIMENSION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER PROFILE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT IMPORT FULL DATABASE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY CLUSTER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DEBUG CONNECT SESSION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY SEQUENCE TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ALTER ROLLBACK SEGMENT TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ON COMMIT REFRESH TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE PUBLIC DATABASE LINK TO REF_TEMPL WITH ADMIN OPTION;
  GRANT UNDER ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT MANAGE ANY FILE GROUP TO REF_TEMPL WITH ADMIN OPTION;
  GRANT GLOBAL QUERY REWRITE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY TRIGGER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT MANAGE FILE GROUP TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE TRIGGER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT FORCE TRANSACTION TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY LIBRARY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY DIRECTORY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROCEDURE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE DATABASE LINK TO REF_TEMPL WITH ADMIN OPTION;
  GRANT INSERT ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT LOCK ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER TABLESPACE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXEMPT ACCESS POLICY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY PROCEDURE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT GRANT ANY OBJECT PRIVILEGE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY LIBRARY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY SYNONYM TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE EXTERNAL JOB TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE ANY INDEXTYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT UNDER ANY TYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE ANY LIBRARY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY SEQUENCE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY INDEX TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE JOB TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DEBUG ANY PROCEDURE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER ANY LIBRARY TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CHANGE NOTIFICATION TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'REF_TEMPL',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT ALTER ANY TYPE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROGRAM TO REF_TEMPL WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'REF_TEMPL',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'REF_TEMPL',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT GRANT ANY PRIVILEGE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT ALTER DATABASE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP USER TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP ANY TABLE TO REF_TEMPL WITH ADMIN OPTION;
  GRANT CREATE ANY OPERATOR TO REF_TEMPL WITH ADMIN OPTION;
  GRANT DROP PROFILE TO REF_TEMPL WITH ADMIN OPTION;
  -- 1 Tablespace Quota for REF_TEMPL 
  ALTER USER REF_TEMPL QUOTA UNLIMITED ON USERS;


--
-- SCOTT  (User) 
--
CREATE USER SCOTT
  IDENTIFIED BY VALUES 'F894844C34402B67'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SCOTT 
  GRANT RESOURCE TO SCOTT;
  GRANT CONNECT TO SCOTT;
  ALTER USER SCOTT DEFAULT ROLE ALL;
  -- 1 System Privilege for SCOTT 
  GRANT UNLIMITED TABLESPACE TO SCOTT;


--
-- SI_INFORMTN_SCHEMA  (User) 
--
CREATE USER SI_INFORMTN_SCHEMA
  IDENTIFIED BY VALUES '84B8CBCA4D477FA3'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for SI_INFORMTN_SCHEMA 
  GRANT UNLIMITED TABLESPACE TO SI_INFORMTN_SCHEMA;


--
-- SYS  (User) 
--
CREATE USER SYS
  IDENTIFIED BY VALUES 'DCB748A5BC5390F2'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 31 Roles for SYS 
  GRANT CTXAPP TO SYS WITH ADMIN OPTION;
  GRANT SELECT_CATALOG_ROLE TO SYS WITH ADMIN OPTION;
  GRANT CONNECT TO SYS WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO SYS WITH ADMIN OPTION;
  GRANT OLAP_DBA TO SYS WITH ADMIN OPTION;
  GRANT JAVAUSERPRIV TO SYS WITH ADMIN OPTION;
  GRANT HS_ADMIN_ROLE TO SYS WITH ADMIN OPTION;
  GRANT OLAP_USER TO SYS WITH ADMIN OPTION;
  GRANT DBA TO SYS WITH ADMIN OPTION;
  GRANT AQ_ADMINISTRATOR_ROLE TO SYS WITH ADMIN OPTION;
  GRANT MGMT_USER TO SYS WITH ADMIN OPTION;
  GRANT JAVA_ADMIN TO SYS WITH ADMIN OPTION;
  GRANT EJBCLIENT TO SYS WITH ADMIN OPTION;
  GRANT JAVADEBUGPRIV TO SYS WITH ADMIN OPTION;
  GRANT JAVAIDPRIV TO SYS WITH ADMIN OPTION;
  GRANT SCHEDULER_ADMIN TO SYS WITH ADMIN OPTION;
  GRANT AQ_USER_ROLE TO SYS WITH ADMIN OPTION;
  GRANT GATHER_SYSTEM_STATISTICS TO SYS WITH ADMIN OPTION;
  GRANT DELETE_CATALOG_ROLE TO SYS WITH ADMIN OPTION;
  GRANT XDBADMIN TO SYS WITH ADMIN OPTION;
  GRANT LOGSTDBY_ADMINISTRATOR TO SYS WITH ADMIN OPTION;
  GRANT EXECUTE_CATALOG_ROLE TO SYS WITH ADMIN OPTION;
  GRANT RESOURCE TO SYS WITH ADMIN OPTION;
  GRANT XDBWEBSERVICES TO SYS WITH ADMIN OPTION;
  GRANT AUTHENTICATEDUSER TO SYS WITH ADMIN OPTION;
  GRANT JAVA_DEPLOY TO SYS WITH ADMIN OPTION;
  GRANT OEM_ADVISOR TO SYS WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO SYS WITH ADMIN OPTION;
  GRANT JAVASYSPRIV TO SYS WITH ADMIN OPTION;
  GRANT RECOVERY_CATALOG_OWNER TO SYS WITH ADMIN OPTION;
  GRANT OEM_MONITOR TO SYS WITH ADMIN OPTION;
  ALTER USER SYS DEFAULT ROLE ALL;
  -- 159 System Privileges for SYS 
  GRANT SELECT ANY SEQUENCE TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DROP TABLESPACE TO SYS;
  GRANT UNLIMITED TABLESPACE TO SYS;
  GRANT CREATE ROLLBACK SEGMENT TO SYS;
  GRANT CREATE ANY SYNONYM TO SYS;
  GRANT DROP PUBLIC SYNONYM TO SYS;
  GRANT CREATE ROLE TO SYS;
  GRANT CREATE PROCEDURE TO SYS;
  GRANT DROP PROFILE TO SYS;
  GRANT ALTER RESOURCE COST TO SYS;
  GRANT GRANT ANY PRIVILEGE TO SYS;
  GRANT ALTER ANY MATERIALIZED VIEW TO SYS;
  GRANT UNDER ANY TYPE TO SYS;
  GRANT CREATE OPERATOR TO SYS;
  GRANT CREATE ANY OPERATOR TO SYS;
  GRANT ALTER ANY INDEXTYPE TO SYS;
  GRANT GLOBAL QUERY REWRITE TO SYS;
  GRANT EXECUTE ANY INDEXTYPE TO SYS;
  GRANT CREATE DIMENSION TO SYS;
  GRANT CREATE ANY JOB TO SYS;
  GRANT DROP ANY SQL PROFILE TO SYS;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'SYS',
  ADMIN_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'SYS',
  ADMIN_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE SESSION TO SYS;
  GRANT ALTER SESSION TO SYS;
  GRANT CREATE TABLESPACE TO SYS;
  GRANT ALTER USER TO SYS;
  GRANT ALTER ROLLBACK SEGMENT TO SYS;
  GRANT CREATE TABLE TO SYS;
  GRANT DROP ANY VIEW TO SYS;
  GRANT CREATE SEQUENCE TO SYS;
  GRANT CREATE ANY SEQUENCE TO SYS;
  GRANT ALTER ANY PROCEDURE TO SYS;
  GRANT DROP ANY TRIGGER TO SYS;
  GRANT CREATE PROFILE TO SYS;
  GRANT DROP ANY LIBRARY TO SYS;
  GRANT MERGE ANY VIEW TO SYS;
  GRANT ADMINISTER ANY SQL TUNING SET TO SYS;
  GRANT MANAGE FILE GROUP TO SYS;
  GRANT UNDER ANY TABLE TO SYS;
  GRANT CREATE ANY DIMENSION TO SYS;
  GRANT RESUMABLE TO SYS;
  GRANT ADVISOR TO SYS;
  GRANT MANAGE SCHEDULER TO SYS;
  GRANT READ ANY FILE GROUP TO SYS;
  GRANT CHANGE NOTIFICATION TO SYS;
  GRANT INSERT ANY TABLE TO SYS;
  GRANT DELETE ANY TABLE TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ANALYZE ANY TO SYS;
  GRANT ALTER TABLESPACE TO SYS;
  GRANT BACKUP ANY TABLE TO SYS;
  GRANT COMMENT ANY TABLE TO SYS;
  GRANT CREATE ANY CLUSTER TO SYS;
  GRANT DROP ANY SEQUENCE TO SYS;
  GRANT DROP PUBLIC DATABASE LINK TO SYS;
  GRANT CREATE TRIGGER TO SYS;
  GRANT QUERY REWRITE TO SYS;
  GRANT ADMINISTER DATABASE TRIGGER TO SYS;
  GRANT ON COMMIT REFRESH TO SYS;
  GRANT DEBUG CONNECT SESSION TO SYS;
  GRANT EXPORT FULL DATABASE TO SYS;
  GRANT CREATE JOB TO SYS;
  GRANT SELECT ANY TRANSACTION TO SYS;
  GRANT ALTER ANY SQL PROFILE TO SYS;
  GRANT EXECUTE ANY TYPE TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT LOCK ANY TABLE TO SYS;
  GRANT MANAGE TABLESPACE TO SYS;
  GRANT BECOME USER TO SYS;
  GRANT DROP ANY TABLE TO SYS;
  GRANT DROP ANY CLUSTER TO SYS;
  GRANT DROP ANY SYNONYM TO SYS;
  GRANT CREATE PUBLIC DATABASE LINK TO SYS;
  GRANT AUDIT ANY TO SYS;
  GRANT FORCE ANY TRANSACTION TO SYS;
  GRANT EXECUTE ANY LIBRARY TO SYS;
  GRANT EXECUTE ANY OPERATOR TO SYS;
  GRANT DROP ANY INDEXTYPE TO SYS;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'SYS', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
  GRANT GRANT ANY OBJECT PRIVILEGE TO SYS;
  GRANT EXECUTE ANY CLASS TO SYS;
  GRANT CREATE ANY SQL PROFILE TO SYS;
  GRANT MANAGE ANY FILE GROUP TO SYS;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'SYS',
  ADMIN_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT EXECUTE ANY PROCEDURE TO SYS;
  GRANT ALTER ANY CLUSTER TO SYS;
  GRANT ALTER ANY INDEX TO SYS;
  GRANT CREATE DATABASE LINK TO SYS;
  GRANT CREATE LIBRARY TO SYS;
  GRANT CREATE ANY INDEXTYPE TO SYS;
  GRANT ALTER ANY DIMENSION TO SYS;
  GRANT CREATE ANY CONTEXT TO SYS;
  GRANT CREATE ANY OUTLINE TO SYS;
  GRANT FLASHBACK ANY TABLE TO SYS;
  GRANT ADMINISTER SQL TUNING SET TO SYS;
  GRANT SELECT ANY TABLE TO SYS WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT AUDIT SYSTEM TO SYS;
  GRANT RESTRICTED SESSION TO SYS;
  GRANT CREATE ANY TABLE TO SYS;
  GRANT CREATE CLUSTER TO SYS;
  GRANT CREATE ANY INDEX TO SYS;
  GRANT DROP ANY INDEX TO SYS;
  GRANT CREATE PUBLIC SYNONYM TO SYS;
  GRANT CREATE VIEW TO SYS;
  GRANT GRANT ANY ROLE TO SYS;
  GRANT DROP ANY PROCEDURE TO SYS;
  GRANT CREATE ANY TRIGGER TO SYS;
  GRANT CREATE MATERIALIZED VIEW TO SYS;
  GRANT CREATE ANY TYPE TO SYS;
  GRANT ALTER ANY TYPE TO SYS;
  GRANT ALTER ANY OUTLINE TO SYS;
  GRANT CREATE EXTERNAL JOB TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ALTER SYSTEM TO SYS;
  GRANT CREATE USER TO SYS;
  GRANT ALTER DATABASE TO SYS;
  GRANT CREATE ANY PROCEDURE TO SYS;
  GRANT ALTER ANY TRIGGER TO SYS;
  GRANT CREATE ANY MATERIALIZED VIEW TO SYS;
  GRANT CREATE ANY DIRECTORY TO SYS;
  GRANT DROP ANY OPERATOR TO SYS;
  GRANT DROP ANY DIMENSION TO SYS;
  GRANT DROP ANY CONTEXT TO SYS;
  GRANT DROP ANY OUTLINE TO SYS;
  GRANT DEBUG ANY PROCEDURE TO SYS;
  GRANT IMPORT FULL DATABASE TO SYS;
  GRANT EXECUTE ANY PROGRAM TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DROP USER TO SYS;
  GRANT DROP ROLLBACK SEGMENT TO SYS;
  GRANT ALTER ANY TABLE TO SYS;
  GRANT CREATE SYNONYM TO SYS;
  GRANT CREATE ANY VIEW TO SYS;
  GRANT ALTER ANY SEQUENCE TO SYS;
  GRANT DROP ANY ROLE TO SYS;
  GRANT ALTER ANY ROLE TO SYS;
  GRANT FORCE TRANSACTION TO SYS;
  GRANT ALTER PROFILE TO SYS;
  GRANT DROP ANY MATERIALIZED VIEW TO SYS;
  GRANT DROP ANY DIRECTORY TO SYS;
  GRANT CREATE TYPE TO SYS;
  GRANT DROP ANY TYPE TO SYS;
  GRANT CREATE ANY LIBRARY TO SYS;
  GRANT ALTER ANY LIBRARY TO SYS;
  GRANT CREATE INDEXTYPE TO SYS;
  GRANT UNDER ANY VIEW TO SYS;
  -- 23 Java Privileges for SYS 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'createClassLoader'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_POLICY_PERMISSION(
     grantee           => 'SYS'
    ,permission_schema => 'SYS'
    ,permission_type   => 'oracle.aurora.rdbms.security.PolicyTablePermission'
    ,permission_name   => '0:oracle.aurora.rdbms.security.PolicyTablePermission#*'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.net.NetPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.security.SecurityPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.net.ssl.SSLPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.util.PropertyPermission'
    ,permission_name   => '*'
    ,permission_action => 'write'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.reflect.ReflectPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.security.AllPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.xaNative'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.corejava'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.jox10oraawt'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.oraioser'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.corejava_d'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.orajaas'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.ordim10'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => 'LoadClassInPackage.java.*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => 'LoadClassInPackage.oracle.aurora.*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => 'LoadClassInPackage.oracle.jdbc.*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.util.logging.LoggingPermission'
    ,permission_name   => 'control'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.security.auth.AuthPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.rdbms.HandlePermission'
    ,permission_name   => '*'
    ,permission_action => '*'
    ,key               => KEYNUM
    );
END;
/


--
-- SYSMAN  (User) 
--
CREATE USER SYSMAN
  IDENTIFIED BY VALUES '25FD61A7879FB1B1'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SYSMAN 
  GRANT DBA TO SYSMAN;
  GRANT MGMT_USER TO SYSMAN WITH ADMIN OPTION;
  ALTER USER SYSMAN DEFAULT ROLE ALL;
  -- 6 System Privileges for SYSMAN 
  GRANT DROP USER TO SYSMAN;
  GRANT CREATE USER TO SYSMAN;
  GRANT ALTER USER TO SYSMAN;
  GRANT SELECT ANY DICTIONARY TO SYSMAN;
  GRANT CREATE ANY TABLE TO SYSMAN;
  GRANT UNLIMITED TABLESPACE TO SYSMAN;
  -- 1 Tablespace Quota for SYSMAN 
  ALTER USER SYSMAN QUOTA UNLIMITED ON SYSAUX;


--
-- SYSTEM  (User) 
--
CREATE USER SYSTEM
  IDENTIFIED BY VALUES 'EED9B65CCECDB2E9'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for SYSTEM 
  GRANT AQ_ADMINISTRATOR_ROLE TO SYSTEM WITH ADMIN OPTION;
  GRANT MGMT_USER TO SYSTEM;
  GRANT DBA TO SYSTEM WITH ADMIN OPTION;
  ALTER USER SYSTEM DEFAULT ROLE ALL;
  -- 5 System Privileges for SYSTEM 
  GRANT UNLIMITED TABLESPACE TO SYSTEM WITH ADMIN OPTION;
  GRANT GLOBAL QUERY REWRITE TO SYSTEM;
  GRANT CREATE TABLE TO SYSTEM;
  GRANT SELECT ANY TABLE TO SYSTEM;
  GRANT CREATE MATERIALIZED VIEW TO SYSTEM;
  -- 1 Java Privilege for SYSTEM 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYSTEM'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => '<<ALL FILES>>'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
END;
/
  -- 1 Resoure Group Privilege for SYSTEM 
BEGIN
  SYS.DBMS_RESOURCE_MANAGER.clear_pending_area();
  SYS.DBMS_RESOURCE_MANAGER.create_pending_area();
  SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SWITCH_CONSUMER_GROUP
    ('SYSTEM','SYS_GROUP',FALSE);
  SYS.DBMS_RESOURCE_MANAGER.submit_pending_area();
END;
/
BEGIN
  SYS.DBMS_RESOURCE_MANAGER.SET_INITIAL_CONSUMER_GROUP
    ('SYSTEM','SYS_GROUP');
END;
/


--
-- TKL  (User) 
--
CREATE USER TKL
  IDENTIFIED BY VALUES 'D9C558B212820C84'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for TKL 
  GRANT DBA TO TKL WITH ADMIN OPTION;
  GRANT CONNECT TO TKL WITH ADMIN OPTION;
  ALTER USER TKL DEFAULT ROLE ALL;
  -- 2 System Privileges for TKL 
  GRANT SELECT ANY TABLE TO TKL WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO TKL WITH ADMIN OPTION;
  -- 1 Tablespace Quota for TKL 
  ALTER USER TKL QUOTA UNLIMITED ON USERS;


--
-- TSMSYS  (User) 
--
CREATE USER TSMSYS
  IDENTIFIED BY VALUES '3DF26A8B17D0F29F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 Role for TSMSYS 
  GRANT RESOURCE TO TSMSYS;
  ALTER USER TSMSYS DEFAULT ROLE ALL;
  -- 1 System Privilege for TSMSYS 
  GRANT UNLIMITED TABLESPACE TO TSMSYS;


--
-- TSTOCK  (User) 
--
CREATE USER TSTOCK
  IDENTIFIED BY VALUES '26DDCBC015F9E343'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for TSTOCK 
  GRANT SELECT_CATALOG_ROLE TO TSTOCK;
  GRANT CONNECT TO TSTOCK;
  GRANT DBA TO TSTOCK;
  ALTER USER TSTOCK DEFAULT ROLE ALL;
  -- 1 System Privilege for TSTOCK 
  GRANT UNLIMITED TABLESPACE TO TSTOCK;


--
-- WMSYS  (User) 
--
CREATE USER WMSYS
  IDENTIFIED BY VALUES '7C9BA362F8314299'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 3 Roles for WMSYS 
  GRANT RESOURCE TO WMSYS;
  GRANT WM_ADMIN_ROLE TO WMSYS WITH ADMIN OPTION;
  GRANT CONNECT TO WMSYS;
  ALTER USER WMSYS DEFAULT ROLE ALL;
  -- 4 System Privileges for WMSYS 
  GRANT CREATE PUBLIC SYNONYM TO WMSYS;
  GRANT CREATE ROLE TO WMSYS;
  GRANT DROP PUBLIC SYNONYM TO WMSYS;
  GRANT UNLIMITED TABLESPACE TO WMSYS;


--
-- XDB  (User) 
--
CREATE USER XDB
  IDENTIFIED BY VALUES '88D8364765FCE6AF'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 3 Roles for XDB 
  GRANT JAVAUSERPRIV TO XDB;
  GRANT CTXAPP TO XDB;
  GRANT RESOURCE TO XDB;
  ALTER USER XDB DEFAULT ROLE ALL;
  -- 10 System Privileges for XDB 
  GRANT UNLIMITED TABLESPACE TO XDB;
  GRANT CREATE PUBLIC SYNONYM TO XDB;
  GRANT CREATE OPERATOR TO XDB;
  GRANT DROP PUBLIC SYNONYM TO XDB;
  GRANT CREATE LIBRARY TO XDB;
  GRANT ALTER SESSION TO XDB;
  GRANT CREATE INDEXTYPE TO XDB;
  GRANT CREATE VIEW TO XDB;
  GRANT QUERY REWRITE TO XDB;
  GRANT CREATE SESSION TO XDB;


--
-- DEFAULT_JOB_CLASS  (Job Class) 
--

BEGIN
  SYS.DBMS_SCHEDULER.CREATE_JOB_CLASS
    (
      job_class_name          => 'DEFAULT_JOB_CLASS'
     ,resource_consumer_group => NULL
     ,service                 => NULL
     ,logging_level           => SYS.DBMS_SCHEDULER.LOGGING_RUNS
     ,log_history             => NULL
     ,comments                => 'This is the default job class.'
    );
END;
/

--
-- AUTO_TASKS_JOB_CLASS  (Job Class) 
--

BEGIN
  SYS.DBMS_SCHEDULER.CREATE_JOB_CLASS
    (
      job_class_name          => 'AUTO_TASKS_JOB_CLASS'
     ,resource_consumer_group => 'AUTO_TASK_CONSUMER_GROUP'
     ,service                 => NULL
     ,logging_level           => SYS.DBMS_SCHEDULER.LOGGING_RUNS
     ,log_history             => NULL
     ,comments                => 'System maintenance job class'
    );
END;
/

--
-- WEEKNIGHT_WINDOW  (Window) 
--
BEGIN
  SYS.DBMS_SCHEDULER.CREATE_WINDOW
    (
       window_name     => 'WEEKNIGHT_WINDOW'
      ,start_date      => NULL
      ,repeat_interval => 'freq=daily;byday=MON,TUE,WED,THU,FRI;byhour=22;byminute=0; bysecond=0'
      ,end_date        => NULL
      ,resource_plan   => NULL
      ,duration        => to_dsInterval('+000 08:00:00')
      ,window_priority => 'LOW'
      ,comments        => 'Weeknight window for maintenance task'
    );

  SYS.DBMS_SCHEDULER.ENABLE
    (name                  => 'SYS.WEEKNIGHT_WINDOW');
END;
/


--
-- WEEKEND_WINDOW  (Window) 
--
BEGIN
  SYS.DBMS_SCHEDULER.CREATE_WINDOW
    (
       window_name     => 'WEEKEND_WINDOW'
      ,start_date      => NULL
      ,repeat_interval => 'freq=daily;byday=SAT;byhour=0;byminute=0;bysecond=0'
      ,end_date        => NULL
      ,resource_plan   => NULL
      ,duration        => to_dsInterval('+002 00:00:00')
      ,window_priority => 'LOW'
      ,comments        => 'Weekend window for maintenance task'
    );

  SYS.DBMS_SCHEDULER.ENABLE
    (name                  => 'SYS.WEEKEND_WINDOW');
END;
/


--
-- MAINTENANCE_WINDOW_GROUP  (Window Group) 
--
BEGIN
  SYS.DBMS_SCHEDULER.CREATE_WINDOW_GROUP
    (
       group_name     => 'MAINTENANCE_WINDOW_GROUP'
      ,window_list    => NULL
      ,comments       => NULL
    );
END;
/
BEGIN
  DBMS_SCHEDULER.ADD_WINDOW_GROUP_MEMBER
    (group_name  => 'SYS.MAINTENANCE_WINDOW_GROUP',
     window_list => 'WEEKNIGHT_WINDOW');
END;
/
BEGIN
  DBMS_SCHEDULER.ADD_WINDOW_GROUP_MEMBER
    (group_name  => 'SYS.MAINTENANCE_WINDOW_GROUP',
     window_list => 'WEEKEND_WINDOW');
END;
/


--
-- AUTO_TASK_CONSUMER_GROUP  (Consumer Group) 
--
begin
  sys.dbms_resource_manager.clear_pending_area();
  sys.dbms_resource_manager.create_pending_area();
  sys.dbms_resource_manager.create_consumer_group (
      consumer_group               => 'AUTO_TASK_CONSUMER_GROUP'
     ,comment                      => 'System maintenance task consumer group');
  sys.dbms_resource_manager.submit_pending_area();
end;
/



--
-- DEFAULT_CONSUMER_GROUP  (Consumer Group) 
--
begin
  sys.dbms_resource_manager.clear_pending_area();
  sys.dbms_resource_manager.create_pending_area();
  sys.dbms_resource_manager.create_consumer_group (
      consumer_group               => 'DEFAULT_CONSUMER_GROUP'
     ,comment                      => 'consumer group for users not assigned to any group');
  sys.dbms_resource_manager.submit_pending_area();
end;
/

begin
  sys.dbms_resource_manager.clear_pending_area();
  sys.dbms_resource_manager.create_pending_area();
  sys.dbms_resource_manager_privs.grant_switch_consumer_group (
      grantee_name                 => 'PUBLIC'
     ,consumer_group               => 'DEFAULT_CONSUMER_GROUP'
     ,grant_option                 => TRUE);
  sys.dbms_resource_manager.submit_pending_area();
end;
/




--
-- INTERNAL_PLAN  (Resource Plan) 
--
begin
  sys.dbms_resource_manager.clear_pending_area();
  sys.dbms_resource_manager.create_pending_area();
  sys.dbms_resource_manager.create_plan (
      plan                         => 'INTERNAL_PLAN'
     ,cpu_mth                      => 'EMPHASIS'
     ,active_sess_pool_mth         => 'ACTIVE_SESS_POOL_ABSOLUTE'
     ,parallel_degree_limit_mth    => 'PARALLEL_DEGREE_LIMIT_ABSOLUTE'
     ,queueing_mth                 => 'FIFO_TIMEOUT'
     ,comment                      => 'Default Plan');
  sys.dbms_resource_manager.create_plan_directive (
      plan                         => 'INTERNAL_PLAN'
     ,group_or_subplan             => 'OTHER_GROUPS'
     ,switch_estimate              => FALSE
     ,comment                      => 'Other sessions at lower priority'  );
  sys.dbms_resource_manager.submit_pending_area();
end;
/


--
-- INTERNAL_QUIESCE  (Resource Plan) 
--
begin
  sys.dbms_resource_manager.clear_pending_area();
  sys.dbms_resource_manager.create_pending_area();
  sys.dbms_resource_manager.create_plan (
      plan                         => 'INTERNAL_QUIESCE'
     ,cpu_mth                      => 'EMPHASIS'
     ,active_sess_pool_mth         => 'ACTIVE_SESS_POOL_ABSOLUTE'
     ,parallel_degree_limit_mth    => 'PARALLEL_DEGREE_LIMIT_ABSOLUTE'
     ,queueing_mth                 => 'FIFO_TIMEOUT'
     ,comment                      => 'Plan to internally quiesce system');
  sys.dbms_resource_manager.create_plan_directive (
      plan                         => 'INTERNAL_QUIESCE'
     ,group_or_subplan             => 'OTHER_GROUPS'
     ,active_sess_pool_p1          => 0
     ,switch_estimate              => FALSE
     ,comment                      => 'Other sessions at lower priority'  );
  sys.dbms_resource_manager.create_plan_directive (
      plan                         => 'INTERNAL_QUIESCE'
     ,group_or_subplan             => 'SYS_GROUP'
     ,switch_estimate              => FALSE
     ,comment                      => 'System sessions at high priority'  );
  sys.dbms_resource_manager.submit_pending_area();
end;
/


--
-- SYSTEM_PLAN  (Resource Plan) 
--
begin
  sys.dbms_resource_manager.clear_pending_area();
  sys.dbms_resource_manager.create_pending_area();
  sys.dbms_resource_manager.create_plan (
      plan                         => 'SYSTEM_PLAN'
     ,cpu_mth                      => 'EMPHASIS'
     ,active_sess_pool_mth         => 'ACTIVE_SESS_POOL_ABSOLUTE'
     ,parallel_degree_limit_mth    => 'PARALLEL_DEGREE_LIMIT_ABSOLUTE'
     ,queueing_mth                 => 'FIFO_TIMEOUT'
     ,comment                      => 'Plan to give system sessions priority');
  sys.dbms_resource_manager.create_plan_directive (
      plan                         => 'SYSTEM_PLAN'
     ,group_or_subplan             => 'OTHER_GROUPS'
     ,cpu_p2                       => 100
     ,switch_estimate              => FALSE
     ,comment                      => 'Other sessions at lower priority'  );
  sys.dbms_resource_manager.create_plan_directive (
      plan                         => 'SYSTEM_PLAN'
     ,group_or_subplan             => 'SYS_GROUP'
     ,cpu_p1                       => 100
     ,switch_estimate              => FALSE
     ,comment                      => 'System sessions at high priority'  );
  sys.dbms_resource_manager.create_consumer_group (
      consumer_group               => 'LOW_GROUP'
     ,comment                      => 'Group of low priority sessions');
  sys.dbms_resource_manager.create_plan_directive (
      plan                         => 'SYSTEM_PLAN'
     ,group_or_subplan             => 'LOW_GROUP'
     ,cpu_p3                       => 100
     ,switch_estimate              => FALSE
     ,comment                      => 'Other sessions at lowest priority'  );
  sys.dbms_resource_manager.submit_pending_area();
end;
/


--
-- AURORA$SERVER$SHUTDOWN  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.aurora$server$shutdown before shutdown on database
CALL dbms_java.server_shutdown;
/
SHOW ERRORS;

ALTER TRIGGER SYS.AURORA$SERVER$SHUTDOWN DISABLE;


--
-- AURORA$SERVER$STARTUP  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.aurora$server$startup after startup on database
CALL dbms_java.server_startup;
/
SHOW ERRORS;

ALTER TRIGGER SYS.AURORA$SERVER$STARTUP DISABLE;


--
-- AW_DROP_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.aw_drop_trg AFTER DROP ON DATABASE
BEGIN
  aw_drop_proc(ora_dict_obj_type, ora_dict_obj_name, ora_dict_obj_owner);
END;
/
SHOW ERRORS;


--
-- CDC_ALTER_CTABLE_BEFORE  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.cdc_alter_ctable_before
  BEFORE
    ALTER ON DATABASE
BEGIN
      /* NOP UNLESS A TABLE OBJECT */
      IF dictionary_obj_type = 'TABLE'
      THEN
        sys.dbms_cdc_ipublish.change_table_trigger(dictionary_obj_owner,dictionary_obj_name,sysevent);
      END IF;
      END;
/
SHOW ERRORS;

ALTER TRIGGER SYS.CDC_ALTER_CTABLE_BEFORE DISABLE;


--
-- CDC_CREATE_CTABLE_AFTER  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.cdc_create_ctable_after
  AFTER
    CREATE ON DATABASE
BEGIN
      /* NOP UNLESS A TABLE OBJECT */
      IF dictionary_obj_type = 'TABLE'
      THEN
        sys.dbms_cdc_ipublish.change_table_trigger(dictionary_obj_owner,dictionary_obj_name,sysevent);
      END IF;
      END;
/
SHOW ERRORS;

ALTER TRIGGER SYS.CDC_CREATE_CTABLE_AFTER DISABLE;


--
-- CDC_CREATE_CTABLE_BEFORE  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.cdc_create_ctable_before
  BEFORE
    CREATE ON DATABASE
BEGIN
      /* NOP UNLESS A TABLE OBJECT */
      IF dictionary_obj_type = 'TABLE'
      THEN
        sys.dbms_cdc_ipublish.change_table_trigger(dictionary_obj_owner,dictionary_obj_name,'LOCK');
      END IF;
      END;
/
SHOW ERRORS;

ALTER TRIGGER SYS.CDC_CREATE_CTABLE_BEFORE DISABLE;


--
-- CDC_DROP_CTABLE_BEFORE  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.cdc_drop_ctable_before
  BEFORE
    DROP ON DATABASE
BEGIN
      /* NOP UNLESS A TABLE OBJECT */
      IF dictionary_obj_type = 'TABLE'
      THEN
        sys.dbms_cdc_ipublish.change_table_trigger(dictionary_obj_owner,dictionary_obj_name,sysevent);
      END IF;
      END;
/
SHOW ERRORS;

ALTER TRIGGER SYS.CDC_DROP_CTABLE_BEFORE DISABLE;


--
-- EXPFIL_ALTEREXPTAB_MAINT  (Trigger) 
--
CREATE OR REPLACE TRIGGER EXFSYS.expfil_alterexptab_maint after alter or
        rename on database
declare 
        objown    VARCHAR2(32); 
        objnm     VARCHAR2(32);
        dcobjnum  NUMBER := null;
        newname   VARCHAR2(32) := null;
        eccnt     NUMBER;
        CURSOR cur1 (towner VARCHAR2, tname VARCHAR2) IS 
          select exscolnm, exstabobj from exf$exprset where exsowner = 
             towner and exstabnm = tname;
      begin 
        objown := DICTIONARY_OBJ_OWNER; 
        objnm := DICTIONARY_OBJ_NAME;

        if (DICTIONARY_OBJ_OWNER = 'EXFSYS') then
          return;
        end if;

        if (DICTIONARY_OBJ_TYPE != 'TABLE') then 
          return;
        end if;

        -- would just skip the loop if no rows found => not an expr table --
        for c1 in cur1(objown, objnm) loop
          if (newname is null) then 
          begin 
            newname := sys.exf$dbms_expfil_syspack.get_tab_name(c1.exstabobj);
          exception
            when others then
              dbms_job.submit(eccnt, 
                'begin exfsys.dbms_expfil_dr.rename_table_maint('||
                   c1.exstabobj||'); end;'); 
              return; -- bug on system trigger : 2355231 --
          end;
          end if;

          if (sys.exf$dbms_expfil_syspack.tab_column_exists(objown, objnm, 
                           c1.exscolnm) = 0) then 
            dcobjnum := c1.exstabobj;   -- indicates that the column is drpd

            -- the expression column was dropped or marked unusable. --
            -- drop the expression column (dictionary) --
            delete from exf$exprset where exsowner = objown and 
              exstabnm = objnm and exscolnm = c1.exscolnm;
          end if;                                            
        end loop;

        -- if this was a drop column and one of the expression sets was 
        -- dropped, the export dep obj dict should be maintained if this 
        -- is the last expression column in the table --
        if (dcobjnum is not null) then 
          -- Count the number of expression columns left in td  he table --
          select count(*) into eccnt from exf$exprset where
                            exsowner = objown and exstabnm = objnm;

          -- this was the last expression column in the table. 
          if (eccnt = 0) then 
            -- Clear the entry from the dependent action list --
            -- auto commit after delete from expdepact$ --
            sys.exf$dbms_expfil_syspack.clr_exp_depaction(dcobjnum);
          end if;        
        end if;
        -- if the name of the table storing expression changes, update dict
        -- accordingly --
        if (newname is not null and newname != objnm) then 
          -- could be updating 0 or 1 or more rows --
          update exf$exprset set exstabnm = newname where exsowner = objown
            and exstabnm = objnm;
          -- see if there is an index or stats etc., for this table --
          if (SQL%ROWCOUNT > 0) then 
            update exf$expsetprivs set esexptab = newname where 
              esowner = objown and esexptab = objnm;
            update exf$expsetstats set esettable = newname where 
              esetowner = objown and esettable = objnm;
            update exf$idxsecobj set idxesettab = newname where
              idxowner = objown and idxesettab = objnm;
            update exf$esetidxparam set esettabn = newname where
              esetowner = objown and esettabn = objnm;
          end if;
        end if;
        return;
      exception when others then null;
      end;
/
SHOW ERRORS;

ALTER TRIGGER EXFSYS.EXPFIL_ALTEREXPTAB_MAINT DISABLE;


--
-- EXPFIL_DROPOBJ_MAINT  (Trigger) 
--
CREATE OR REPLACE TRIGGER EXFSYS.expfil_dropobj_maint before drop on database
declare 
        objown VARCHAR2(32); 
        objnm  VARCHAR2(32);
        attsetc  number;
        tabobjn  number := null;
        
        CURSOR cur2 (tabown VARCHAR2) is 
          select distinct(exstabobj) tobjn from exf$exprset where 
            exsowner = tabown;
      begin 
        objown := DICTIONARY_OBJ_OWNER; 
        objnm := DICTIONARY_OBJ_NAME;

        if (DICTIONARY_OBJ_OWNER = 'EXFSYS') then 
          return;
        end if;
          exfsys.adm_rlmgr_systrig.pre_dropobj_maint(DICTIONARY_OBJ_OWNER,
                              DICTIONARY_OBJ_NAME, DICTIONARY_OBJ_TYPE); 
      
        if (DICTIONARY_OBJ_TYPE = 'TABLE') then 
          begin 
            -- only one row expected --
            select distinct(exstabobj) into tabobjn from exf$exprset where
              exsowner = objown and exstabnm = objnm;
            if (tabobjn is not null) then 
              sys.exf$dbms_expfil_syspack.clr_exp_depaction(tabobjn);
            end if;
            delete from exf$exprset where exsowner = objown and 
              exstabnm = objnm;
          exception 
            when no_data_found then 
              null;
          end;
          return;
        elsif (DICTIONARY_OBJ_TYPE = 'TYPE' or 
               DICTIONARY_OBJ_TYPE = 'TYPE BODY') then 
          if (dbms_expfil_utl.db_operation_type =
              dbms_expfil_utl.OP_DROP_USER or
              dbms_expfil_utl.db_operation_type =
              dbms_expfil_utl.EXF_MAINT_OP) then
            return;                   --- return is dropping the user ---
          end if;

          select count(*) into attsetc from exf$attrset where atsowner 
             = objown and atsname = objnm; 
          if (attsetc != 0) then 
            dbms_expfil_utl.error_out(38473);
          end if;
          return;
        elsif (DICTIONARY_OBJ_TYPE = 'USER') then
          if (objnm = 'EXFSYS') then 
            return;
          end if;
          -- set the drop user context; no error dropping types --
          dbms_expfil_utl.db_operation_type :=
                       dbms_expfil_utl.OP_DROP_USER;
        end if;
      exception when others then 
        -- recognize all the errors that are valid to throw --
        if (SQLCODE = -38473 or SQLCODE = -41657) then
          raise;
        end if;
      end;
/
SHOW ERRORS;

ALTER TRIGGER EXFSYS.EXPFIL_DROPOBJ_MAINT DISABLE;


--
-- EXPFIL_DROPUSR_MAINT  (Trigger) 
--
CREATE OR REPLACE TRIGGER EXFSYS.expfil_dropusr_maint after drop on database
declare 
        objnm VARCHAR2(32);
        CURSOR cur1 (tabown VARCHAR2) is 
          select distinct(exstabobj) tobjn from exf$exprset where 
            exsowner = tabown and exstabnm is not null;
      begin 
        objnm := DICTIONARY_OBJ_NAME;
        if (DICTIONARY_OBJ_TYPE != 'USER') then 
          return;
        end if;

        -- user being dropped is not EXFSYS --
        if (objnm = 'EXFSYS') then
          return;
        end if;

        dbms_expfil_utl.db_operation_type := dbms_expfil_utl.NO_SIG_OPER;

        for c1 in cur1 (objnm) loop 
          sys.exf$dbms_expfil_syspack.clr_exp_depaction(c1.tobjn); 
        end loop;
        delete from exf$exprset where exsowner = objnm;
        delete from exf$attrset where atsowner = objnm;
        delete from exf$expsetprivs where esgrantee = objnm;
      exception when others then null;
      end;
/
SHOW ERRORS;

ALTER TRIGGER EXFSYS.EXPFIL_DROPUSR_MAINT DISABLE;


--
-- EXPFIL_RESTRICT_TYPEEVOLVE  (Trigger) 
--
CREATE OR REPLACE TRIGGER EXFSYS.expfil_restrict_typeevolve before alter
       or create on database
declare 
        objown VARCHAR2(32);
        objnm  VARCHAR2(32);
        attsetc  number;
      begin 
        objown := DICTIONARY_OBJ_OWNER; 
        objnm := DICTIONARY_OBJ_NAME;
 
        if (DICTIONARY_OBJ_OWNER = 'EXFSYS') then
          return;
        end if;

        if (DICTIONARY_OBJ_TYPE != 'TYPE') then
          return;
        end if;

        -- see if the ADT is used for an attribute set --
        select count(*) into attsetc from exf$attrset where atsowner
           = objown and atsname = objnm;

        -- if the type is being created because of add_elementary_attr
        -- operation, let it go --
        if (attsetc != 0 and dbms_expfil_utl.db_operation_type !=
            dbms_expfil_utl.EXF_MAINT_OP) then
          -- we are about to throw the error; just check if this 
          -- attribute set is invalid due to evolution of one of its 
          -- embedded types with INVALIDATE option. If this is the case, 
          -- the system trigger will be invoked next time the ADT is 
          -- being used with status = INVALID --
          if (sys.exf$dbms_expfil_syspack.get_typelv_status(objown,objnm) 
                  = 'VALID') then 
            dbms_expfil_utl.error_out(38476); -- no doubt; has to be error --
          end if; 
        end if;
      exception when others then 
        if (SQLCODE = -38476) then raise; end if;
      end;
/
SHOW ERRORS;

ALTER TRIGGER EXFSYS.EXPFIL_RESTRICT_TYPEEVOLVE DISABLE;


--
-- NO_VM_ALTER  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.no_vm_alter before alter on database
WHEN (
sys.dictionary_obj_type in ('INDEX','TABLE')
      )
begin









  if (sys_context('lt_ctx', 'allowDDLOperation')='true') then
    return ;
  end if ;

  sys.no_vm_alter_proc(sys.dictionary_obj_type, sys.dictionary_obj_name, sys.dictionary_obj_owner);
end;
/
SHOW ERRORS;

ALTER TRIGGER SYS.NO_VM_ALTER DISABLE;


--
-- NO_VM_CREATE  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.no_vm_create before create on database
WHEN (
sys.dictionary_obj_type in ('PROCEDURE', 'TRIGGER', 'VIEW')
      )
begin










  if (sys_context('lt_ctx', 'allowDDLOperation')='true') then
    return ;
  end if ;

  sys.no_vm_create_proc(sys.dictionary_obj_type, sys.dictionary_obj_name, sys.dictionary_obj_owner);
end;
/
SHOW ERRORS;

ALTER TRIGGER SYS.NO_VM_CREATE DISABLE;


--
-- NO_VM_DROP  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.no_vm_drop before drop on database
WHEN (
sys.dictionary_obj_type in ('INDEX', 'PROCEDURE', 'ROLE', 'TABLE', 'TRIGGER', 'TYPE', 'USER', 'VIEW')
      )
begin










  if (sys_context('lt_ctx', 'allowDDLOperation')='true') then
    return ;
  end if ;

  sys.no_vm_drop_proc(sys.dictionary_obj_type, sys.dictionary_obj_name, sys.dictionary_obj_owner);
end;
/
SHOW ERRORS;

ALTER TRIGGER SYS.NO_VM_DROP DISABLE;


--
-- NO_VM_DROP_A  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.no_vm_drop_a after drop on database
WHEN (
sys.dictionary_obj_type in ('USER')
      )
begin
  sys.lt_ctx_pkg.allowDDLOperation('false') ;



end;
/
SHOW ERRORS;

ALTER TRIGGER SYS.NO_VM_DROP_A DISABLE;


--
-- OLAPISHUTDOWNTRIGGER  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.OlapiShutdownTrigger BEFORE SHUTDOWN ON DATABASE
DECLARE openMode VARCHAR2(10);
          olapOn BOOLEAN;
          histRetention BOOLEAN;
          sessionCount NUMBER;
          histID NUMBER;
  BEGIN

  SELECT open_mode INTO openMode FROM V$DATABASE;
  IF (openMode != 'READ WRITE') THEN
    histRetention := FALSE;
    OlapiHistoryRetention(olapOn, histRetention, sessionCount);
    RETURN;
  END IF;

  OlapiHistoryRetention(olapOn, histRetention, sessionCount);
  IF (olapOn AND histRetention) THEN



    BEGIN
    SELECT MAX(hist_id) INTO histID FROM Olapi_History;
    IF (histRetention) THEN
      UPDATE Olapi_History SET collecting_stop_time = CURRENT_TIMESTAMP WHERE
        inst_id = SYS_CONTEXT('USERENV', 'Instance') AND hist_id = histID;
    END IF;
    UPDATE Olapi_History SET stop_time = CURRENT_TIMESTAMP,
      session_count = sessionCount WHERE
      inst_id = SYS_CONTEXT('USERENV', 'Instance') AND hist_id = histID;
    EXCEPTION


    WHEN OTHERS THEN
      RETURN;
    END;
  END IF;
  END;
/
SHOW ERRORS;


--
-- OLAPISTARTUPTRIGGER  (Trigger) 
--
CREATE OR REPLACE TRIGGER SYS.OlapiStartupTrigger AFTER STARTUP ON DATABASE
DECLARE openMode VARCHAR2(10);
          olapOn BOOLEAN;
          histRetention BOOLEAN;
          hist_id NUMBER;
          sessionCount NUMBER;
  BEGIN

  SELECT open_mode INTO openMode FROM V$DATABASE;
  IF (openMode != 'READ WRITE') THEN
    histRetention := FALSE;
    OlapiHistoryRetention(olapOn, histRetention, sessionCount);
    RETURN;
  END IF;

  OlapiHistoryRetention(olapOn, histRetention, hist_id);
  IF (olapOn AND histRetention) THEN
    BEGIN
    SELECT Olapi_History_Seq.NEXTVAL INTO hist_id FROM DUAL;


    INSERT INTO Olapi_History VALUES(SYS_CONTEXT('USERENV', 'Instance'),
      hist_id, CURRENT_TIMESTAMP, NULL, NULL, 0);
    EXCEPTION


    WHEN OTHERS THEN
      histRetention := FALSE;
      OlapiHistoryRetention(olapOn, histRetention, sessionCount);
    END;
  END IF;
  END;
/
SHOW ERRORS;


--
-- RLMGR_TRUNCATE_MAINT  (Trigger) 
--
CREATE OR REPLACE TRIGGER EXFSYS.rlmgr_truncate_maint before truncate on 
        database
declare 
        objown VARCHAR2(32);
        objnm  VARCHAR2(32);
        rcpcknm VARCHAR2(32);
      begin 
        objown := DICTIONARY_OBJ_OWNER; 
        objnm := DICTIONARY_OBJ_NAME;
 
        if (DICTIONARY_OBJ_OWNER = 'EXFSYS') then
          return;
        end if;
        if (DICTIONARY_OBJ_TYPE = 'TABLE') then 
        begin
          select rset_pack into rcpcknm from rlm$ruleset where 
            rset_owner = objown and rset_name = objnm and 
             bitand(rset_prop, 4) = 4; 
          if (sys.exf$dbms_expfil_syspack.proc_is_definers(
                    objown, rcpcknm, 'TRUNCATE_RCTAB') = 0) then
            dbms_rlmgr_dr.raise_error(41682);
          end if;
          EXECUTE IMMEDIATE ' begin "'||objown||'".'||rcpcknm||
                    '.TRUNCATE_RCTAB; end;';
        exception 
          when no_data_found then 
             null;
        end;
        end if;
      end;
/
SHOW ERRORS;

ALTER TRIGGER EXFSYS.RLMGR_TRUNCATE_MAINT DISABLE;


--
-- SDO_DROP_USER  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.sdo_drop_user
after drop on DATABASE
declare
   stmt varchar2(200);
BEGIN
     if dictionary_obj_type = 'USER' THEN
       stmt := 'DELETE FROM SDO_GEOM_METADATA_TABLE ' ||
     ' WHERE ''"''||SDO_OWNER||''"'' = ''"' || dictionary_obj_name || '"'' ';
       EXECUTE IMMEDIATE stmt;

       stmt := 'DELETE FROM SDO_MAPS_TABLE ' ||
    ' WHERE ''"''||SDO_OWNER||''"'' = ''"' || dictionary_obj_name || '"'' ';
       EXECUTE IMMEDIATE stmt;

       stmt := 'DELETE FROM SDO_STYLES_TABLE ' ||
    ' WHERE ''"''||SDO_OWNER||''"'' = ''"' || dictionary_obj_name || '"'' ';
       EXECUTE IMMEDIATE stmt;

       stmt := 'DELETE FROM SDO_THEMES_TABLE ' ||
   ' WHERE ''"''||SDO_OWNER||''"'' = ''"' || dictionary_obj_name || '"'' ';
       EXECUTE IMMEDIATE stmt;

       stmt := 'DELETE FROM SDO_LRS_METADATA_TABLE ' ||
   ' WHERE ''"''||SDO_OWNER||''"'' = ''"' || dictionary_obj_name || '"'' ';
       EXECUTE IMMEDIATE stmt;

       stmt := 'DELETE FROM SDO_TOPO_METADATA_TABLE ' ||
   ' WHERE ''"''||SDO_OWNER||''"'' = ''"' || dictionary_obj_name || '"'' ';
       EXECUTE IMMEDIATE stmt;

    end if;
end;
/
SHOW ERRORS;


--
-- SDO_DROP_USER_BEFORE  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.sdo_drop_user_before
before drop on DATABASE
declare
   stmt varchar2(200);
   rdf_exception EXCEPTION;   pragma exception_init(rdf_exception, -20000);
BEGIN
     if dictionary_obj_type = 'USER' THEN
       BEGIN
         EXECUTE IMMEDIATE
          'begin ' ||
            'mdsys.rdf_apis_internal.' ||
            'notify_drop_user(''' || dictionary_obj_name || '''); ' ||
          'end;';

         EXCEPTION
           WHEN rdf_exception THEN RAISE;
           WHEN OTHERS        THEN NULL;
       END;
    end if;
end;
/
SHOW ERRORS;


--
-- SDO_GEOR_DROP_USER  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.SDO_GEOR_DROP_USER
AFTER DROP ON DATABASE
DECLARE
  type vcurType is REF CURSOR;
  vcur vcurType;
  stmt VARCHAR2(1000);
  stm2 VARCHAR2(200);
  rdt  VARCHAR2(80);
  rsid number;
  cnt  number;
BEGIN
  IF dictionary_obj_type = 'USER' THEN
    stmt := 'DELETE FROM SDO_GEOR_SYSDATA_TABLE WHERE SDO_OWNER = :name';
    EXECUTE IMMEDIATE stmt using dictionary_obj_name;

  ELSIF dictionary_obj_type = 'TABLE' AND
        dictionary_obj_owner <> 'MDSYS' AND
        dictionary_obj_name <> 'SDO_GEOR_SYSDATA_TABLE' THEN
    stmt := 'SELECT COUNT(*) FROM SDO_GEOR_SYSDATA_TABLE ' ||
            ' WHERE SDO_OWNER = :1 AND GEORASTER_TABLE_NAME = :2';
    EXECUTE IMMEDIATE stmt INTO cnt USING dictionary_obj_owner,
                                          dictionary_obj_name;
    IF cnt > 0 THEN
      stmt := 'SELECT RDT_TABLE_NAME, RASTER_ID FROM SDO_GEOR_SYSDATA_TABLE' ||
              ' WHERE SDO_OWNER = :1 AND GEORASTER_TABLE_NAME = :2';
      open vcur for stmt using dictionary_obj_owner, dictionary_obj_name;
      loop
        fetch vcur into rdt, rsid;
        exit when vcur%NOTFOUND;
        if instr(rdt, '.') = 0 then
          rdt := dictionary_obj_owner || '.' || rdt;
        end if;
        stm2 := 'DELETE FROM ' || rdt || ' WHERE rasterid=:1';
        begin
          execute immediate stm2 using rsid;
        exception
          when others then

            if SQLCODE <> -942 then
              raise;
            end if;
        end;
      end loop;
      stmt := 'DELETE FROM SDO_GEOR_SYSDATA_TABLE ' ||
              ' WHERE SDO_OWNER = :name AND GEORASTER_TABLE_NAME = :2';
      EXECUTE IMMEDIATE stmt USING dictionary_obj_owner, dictionary_obj_name;
    END IF;
  END IF;
END;
/
SHOW ERRORS;


--
-- SDO_GEOR_TRUNC_TABLE  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.SDO_GEOR_TRUNC_TABLE
AFTER TRUNCATE ON DATABASE
DECLARE
  type vcurType is REF CURSOR;
  vcur vcurType;
  stmt VARCHAR2(1000);
  stm2 VARCHAR2(250);
  rdt  VARCHAR2(80);
  rsid number;
  cnt  number;
  m_id number;
BEGIN
  IF dictionary_obj_type <> 'TABLE' THEN
    return;
  END IF;

  stmt := 'SELECT COUNT(*) FROM SDO_GEOR_SYSDATA_TABLE ' ||
          ' WHERE SDO_OWNER = :1 AND GEORASTER_TABLE_NAME = :2';
  EXECUTE IMMEDIATE stmt INTO cnt USING dictionary_obj_owner,
                                        dictionary_obj_name;
  IF cnt > 0 THEN
    stmt := 'SELECT RDT_TABLE_NAME, RASTER_ID FROM SDO_GEOR_SYSDATA_TABLE' ||
            ' WHERE SDO_OWNER = :1 AND GEORASTER_TABLE_NAME = :2';
    open vcur for stmt using dictionary_obj_owner, dictionary_obj_name;
    loop
      fetch vcur into rdt, rsid;
      exit when vcur%NOTFOUND;
      if instr(rdt, '.') = 0 then
        rdt := dictionary_obj_owner || '.' || rdt;
      end if;
      stm2 := 'DELETE FROM ' || rdt || ' WHERE rasterid=:1';
      begin
        execute immediate stm2 using rsid;
      exception
        when others then

          if SQLCODE <> -942 then
            raise;
          end if;
      end;
    end loop;
    stmt := 'DELETE FROM SDO_GEOR_SYSDATA_TABLE ' ||
            ' WHERE SDO_OWNER = :name AND GEORASTER_TABLE_NAME = :2';
    EXECUTE IMMEDIATE stmt USING dictionary_obj_owner, dictionary_obj_name;
  END IF;



  stmt := 'SELECT COUNT(*) FROM ALL_TABLES ' ||
          ' WHERE OWNER = ''MDSYS'' AND TABLE_NAME = ''RDF_MODEL$'' ';
  EXECUTE IMMEDIATE stmt INTO cnt;
  if (cnt = 1) then
  begin
    cnt := 0;
    stmt := 'SELECT count(*) FROM MDSYS.RDF_MODEL$ ' ||
            ' WHERE OWNER = :1 AND TABLE_NAME = :2';
     EXECUTE IMMEDIATE stmt INTO cnt USING dictionary_obj_owner,
                                           dictionary_obj_name;

    if (cnt > 0)  then
      stmt := 'SELECT model_id FROM MDSYS.RDF_MODEL$ ' ||
            ' WHERE OWNER = :1 AND TABLE_NAME = :2';
       EXECUTE IMMEDIATE stmt INTO m_id USING dictionary_obj_owner,
                                             dictionary_obj_name;

        stmt := ' DELETE  MDSYS.RDF_LINK$ WHERE  model_id = '||to_char(m_id) ;

        EXECUTE IMMEDIATE stmt;
    end if;

     exception
        when others then NULL;
  end;

  end if;

END;
/
SHOW ERRORS;


--
-- SDO_NETWORK_CONS_DROP_TRIG  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.sdo_network_cons_drop_trig
  AFTER DROP ON DATABASE
DECLARE
  stmt    VARCHAR2(256);
BEGIN
  stmt := 'DELETE FROM SDO_NETWORK_CONSTRAINTS WHERE SDO_OWNER = :name';
  IF  dictionary_obj_type = 'USER'  THEN
     EXECUTE IMMEDIATE stmt using NLS_UPPER(dictionary_obj_name);
  END IF;
END ;
/
SHOW ERRORS;


--
-- SDO_NETWORK_DROP_USER  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.SDO_NETWORK_DROP_USER
AFTER DROP ON DATABASE
DECLARE
  stmt    VARCHAR2(256);
BEGIN

  stmt := 'DELETE FROM SDO_NETWORK_METADATA_TABLE WHERE SDO_OWNER = :name';
  IF  dictionary_obj_type = 'USER'  THEN
     EXECUTE IMMEDIATE stmt using NLS_UPPER(dictionary_obj_name);
  END IF;
END ;
/
SHOW ERRORS;


--
-- SDO_NETWORK_UD_DROP_TRIG  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.sdo_network_ud_drop_trig
  AFTER DROP ON DATABASE
DECLARE
  stmt    VARCHAR2(256);
BEGIN
  stmt := 'DELETE FROM SDO_NETWORK_USER_DATA WHERE SDO_OWNER = :name';
  IF  dictionary_obj_type = 'USER'  THEN
     EXECUTE IMMEDIATE stmt using NLS_UPPER(dictionary_obj_name);
  END IF;
END ;
/
SHOW ERRORS;


--
-- SDO_TOPO_DROP_FTBL  (Trigger) 
--
CREATE OR REPLACE TRIGGER MDSYS.sdo_topo_drop_ftbl
  BEFORE DROP ON DATABASE
WHEN (
ora_dict_obj_type = 'TABLE'
      )
DECLARE
    cnt        NUMBER;
    stmt       VARCHAR(500);
    topology   VARCHAR(100);
    REG_TBL    EXCEPTION;

  BEGIN

    stmt := 'SELECT  topology ' ||
            '  FROM  SDO_TOPO_METADATA_TABLE a, TABLE(a.Topo_Geometry_Layers) b ' ||
            '  WHERE b.owner = ''' || ORA_DICT_OBJ_OWNER  ||
            '''  AND b.table_name = ''' || ORA_DICT_OBJ_NAME || '''' ;
    EXECUTE IMMEDIATE stmt into topology;
    RAISE REG_TBL;

    EXCEPTION
      WHEN REG_TBL THEN
        MDSYS.MDERR.raise_md_error(
         'MD', 'SDO', -13199,
         'Need use delete_topo_geometry_layer() to deregister table '
         || ORA_DICT_OBJ_NAME || ' from topology ' || topology ||
         ' before drop it');
      WHEN OTHERS THEN
        RETURN;
  END;
/
SHOW ERRORS;


--
-- XDB_PI_TRIG  (Trigger) 
--
CREATE OR REPLACE TRIGGER XDB.xdb_pi_trig
BEFORE DROP OR TRUNCATE on DATABASE
BEGIN
  BEGIN
    IF (xdb.DBMS_XDBZ0.is_hierarchy_enabled_internal(sys.dictionary_obj_owner, sys.dictionary_obj_name, sys.dictionary_obj_owner)) THEN
      xdb.XDB_PITRIG_PKG.pitrig_truncate(sys.dictionary_obj_owner, sys.dictionary_obj_name);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
     null;
  END;
  BEGIN
    IF (xdb.DBMS_XDBZ0.is_hierarchy_enabled_internal(sys.dictionary_obj_owner, sys.dictionary_obj_name, sys.dictionary_obj_owner, xdb.DBMS_XDBZ.IS_ENABLED_RESMETADATA)) THEN
      xdb.XDB_PITRIG_PKG.pitrig_dropmetadata(sys.dictionary_obj_owner, sys.dictionary_obj_name);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
     null;
  END;
END;
/
SHOW ERRORS;


