SELECT ORDID , ARTICUL , COUNT1 , PRICE , EXPIRY_DATE , ID  , RRL_ARTICULS.NORMA_UKLADKI , RRL_ARTICULS.CELL
FROM rabaev.RRL_PRIHOD_NAKLAD_ROWS , rabaev.RRL_articuls 
where  RRL_PRIHOD_NAKLAD_ROWS.ARTICUL = RRL_ARTICULS.ACTICUL