set define off
set sqlblanklines on

prompt TABLE INVENTORY_LINE_PALLET_AUDIT

  CREATE TABLE "RABAEV"."INVENTORY_LINE_PALLET_AUDIT" 
   (	"УИД" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"КОЛ" NUMBER(*,0) DEFAULT 0, 
	"PALLETID" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ДАТАСОЗДАНИЯ" DATE, 
	"USER_ID" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"METHOD" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE LOT_AUDIT

  CREATE TABLE "RABAEV"."LOT_AUDIT" 
   (	"SSCC" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE LOT_AUDIT_ERROR_LINES

  CREATE TABLE "RABAEV"."LOT_AUDIT_ERROR_LINES" 
   (	"SSCC" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"UNIT_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"UID1" VARCHAR2(12 CHAR) COLLATE "USING_NLS_COMP", 
	"EAN" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP", 
	"TIME_OF_AUDIT" DATE, 
	"PLAN_COUNT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE ORDER_AUDIT

  CREATE TABLE "RABAEV"."ORDER_AUDIT" 
   (	"ORDER_NUMBER" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE ORDER_AUDIT_ERROR_LINES

  CREATE TABLE "RABAEV"."ORDER_AUDIT_ERROR_LINES" 
   (	"ORDER_NUMBER" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"UNIT_COUNT" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"UID1" VARCHAR2(12 CHAR) COLLATE "USING_NLS_COMP", 
	"EAN" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP", 
	"TIME_OF_AUDIT" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE ORDER_MOV_HIST

  CREATE TABLE "RABAEV"."ORDER_MOV_HIST" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORDER_UID" NUMBER(*,0) NOT NULL ENABLE, 
	"ZONE" NVARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"RUSER" NVARCHAR2(15) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TIME_STAMP" DATE, 
	"LAST_FLAG" NUMBER(*,0) DEFAULT 1, 
	"USSCC" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE PLACE_AUDIT

  CREATE TABLE "RABAEV"."PLACE_AUDIT" 
   (	"PALLETID" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE PLACE_AUDIT_ERROR_LINES

  CREATE TABLE "RABAEV"."PLACE_AUDIT_ERROR_LINES" 
   (	"PALLETID" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"UNIT_COUNT" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"UID1" VARCHAR2(12 CHAR) COLLATE "USING_NLS_COMP", 
	"EAN" VARCHAR2(25 CHAR) COLLATE "USING_NLS_COMP", 
	"RUSER" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"DATE1" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE Q1

  CREATE TABLE "RABAEV"."Q1" 
   (	"ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RIGHTS

  CREATE TABLE "RABAEV"."RIGHTS" 
   (	"RIGHT1" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"USER_GROUP" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"ID" NUMBER(*,0), 
	"DESCR" VARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ADDR

  CREATE TABLE "RABAEV"."RRL_ADDR" 
   (	"ADDR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"NAPR" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"RAION" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"REGION" VARCHAR2(250) COLLATE "USING_NLS_COMP", 
	"ORD" NUMBER(*,0) DEFAULT 0, 
	"TRANSPORT_TYPE" VARCHAR2(15) COLLATE "USING_NLS_COMP" DEFAULT 15, 
	"PRIM1" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STOL" NUMBER(*,0) DEFAULT 0, 
	"DOLGOTA" NUMBER, 
	"SHIROTA" NUMBER, 
	"LEAD_TIME" NUMBER(*,0) DEFAULT 0, 
	"CLIENT_GROUP" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SHIPPING_TIME" VARCHAR2(5) COLLATE "USING_NLS_COMP" DEFAULT '00:00'
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ALARMS

  CREATE TABLE "RABAEV"."RRL_ALARMS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TYPE1" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ALARM_TIME" DATE, 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COMMENT1" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"SEND_BEGIN" NUMBER(*,0) DEFAULT 0, 
	"SEND_ENDED" NUMBER(*,0) DEFAULT 0, 
	"WARE_ID" NUMBER(*,0), 
	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CELL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PALLET_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TIME_SEND_ENDED" DATE, 
	 CONSTRAINT "RRL_ALARMS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ARTICUL_MODS

  CREATE TABLE "RABAEV"."RRL_ARTICUL_MODS" 
   (	"ID" NUMBER(*,0), 
	"ARTICUL" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SHT_IN_KOR" NUMBER, 
	"SHT_WEIGHT" NUMBER, 
	"KARTON_WEIGHT" NUMBER, 
	"DELETED" NUMBER(*,0), 
	"SHK_SHT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SHK_KOR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DIMK_X" NUMBER, 
	"DIMK_Y" NUMBER, 
	"DIMK_Z" NUMBER, 
	"BRT_WEIGHT_OF_KOR" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ARTICULS

  CREATE TABLE "RABAEV"."RRL_ARTICULS" 
   (	"ACTICUL" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"NORMA_UKLADKI" NUMBER NOT NULL ENABLE, 
	"CELL" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"UNIT_TYPE" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"BARCODE_SHT" VARCHAR2(128 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 777 NOT NULL ENABLE, 
	"BARCODE_KOR" VARCHAR2(128 CHAR) COLLATE "USING_NLS_COMP", 
	"BARCODE_BL" VARCHAR2(128 CHAR) COLLATE "USING_NLS_COMP", 
	"WEIGHT_OF_KOR" NUMBER, 
	"COUNT_IN_ROW" NUMBER(*,0), 
	"ROWS_IN_PAL" NUMBER(*,0), 
	"COUNT_SHT_IN_KOR" NUMBER, 
	"COUNT_SHT_IN_BL" NUMBER DEFAULT 1, 
	"PALLET_MULTIPLE" NUMBER DEFAULT 1, 
	"CARTON_WEIGHT" NUMBER DEFAULT 0, 
	"ETAJ_LIMIT" NUMBER(*,0) DEFAULT 100, 
	"BESTBEFOREDAYS" NUMBER(*,0) DEFAULT 360, 
	"SSP" NUMBER DEFAULT 0, 
	"ABC_GROUP" VARCHAR2(1) COLLATE "USING_NLS_COMP", 
	"XYZ_GROUP" VARCHAR2(1) COLLATE "USING_NLS_COMP", 
	"ORDER_OF_COMP" NUMBER(*,0) DEFAULT 0, 
	"RCECOMPLECT" NUMBER(*,0) DEFAULT 0, 
	"FLOATING_WEIGHT" NUMBER(*,0) DEFAULT 0, 
	"TYPE_W" NUMBER(*,0) DEFAULT 0, 
	"WEIGHT_OF_SHT" NUMBER DEFAULT 0, 
	"ROUND_TO" NUMBER(*,0) DEFAULT 2, 
	"DEF_PERC" NUMBER DEFAULT 0, 
	"LAST_MOD_ID" NUMBER(*,0), 
	"AUTHOR_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"FAKE_PARTION_UID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"DIMKOR_X" NUMBER, 
	"DIMKOR_Y" NUMBER, 
	"DIMKOR_Z" NUMBER, 
	"BRUTTO_WEIGHT_OF_KOR" NUMBER, 
	"LAST_PRICE" NUMBER, 
	"LAST_USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"UUZ" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_BILL_COMPANY

  CREATE TABLE "RABAEV"."RRL_BILL_COMPANY" 
   (	"COMPANYNAME" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"ADDR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DELETED" NUMBER(*,0) DEFAULT 0, 
	"POS" NUMBER(*,0), 
	"COLOR" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SPECIAL_PRICE" NUMBER(*,0) DEFAULT 0, 
	"TRASH" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_BILLING

  CREATE TABLE "RABAEV"."RRL_BILLING" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"UE" NUMBER, 
	"TIMEOF" DATE, 
	"OPERATION" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PRIM" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PALLET_UID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"DELETED" NUMBER(*,0), 
	"CELL_FROM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CELL_TO" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_BILLING_NASTR_INTMOV

  CREATE TABLE "RABAEV"."RRL_BILLING_NASTR_INTMOV" 
   (	"EXPEDIT_GROUP_TO" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"USER_GROUP" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"UE" NUMBER DEFAULT 0, 
	"EXPEDIT_GROUP_FROM" VARCHAR2(20) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_BILL_ORDERS

  CREATE TABLE "RABAEV"."RRL_BILL_ORDERS" 
   (	"ID" NUMBER(*,0), 
	"NUM" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"COMPANY" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"DATEOFORDER" DATE, 
	"DATEFROM" DATE, 
	"DATETO" DATE, 
	"CLOSED" NUMBER(*,0) DEFAULT 0, 
	"SUMM" NUMBER DEFAULT 0, 
	"PAYED" NUMBER(*,0) DEFAULT 0, 
	"NUM_PLAT" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_CELLS

  CREATE TABLE "RABAEV"."RRL_CELLS" 
   (	"CELL" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"OTBOR" NUMBER(*,0) DEFAULT 0, 
	"BLOCKED_FOR_REMAINS" NUMBER(*,0) DEFAULT 0, 
	"BLOCKED_FOR_POPOLNENIE" NUMBER(*,0) DEFAULT 0, 
	"UID_POLETA_FOR_BLOCK" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"TIME_FOR_BLOCK" DATE, 
	"X" NUMBER(*,0) DEFAULT 10000 NOT NULL ENABLE, 
	"Y" NUMBER(*,0) DEFAULT 10000 NOT NULL ENABLE, 
	"Z" NUMBER(*,0) DEFAULT 10000 NOT NULL ENABLE, 
	"BLOCKED_FOR_ACCEPT" NUMBER(*,0) DEFAULT 0, 
	"WARE_ID" NUMBER(*,0) DEFAULT 1, 
	"IS_SYSTEM" NUMBER(*,0) DEFAULT 0, 
	"EXPEDITION_GROUP" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"LAST_TIME_OF_UPDATE" DATE, 
	"LIMIT_WEIGHT" NUMBER DEFAULT 10000, 
	"LIMIT_HEIGHT" NUMBER DEFAULT 10000, 
	"Y_VISOTA" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_CELLS_CONDITIONS_MAPPING

  CREATE TABLE "RABAEV"."RRL_CELLS_CONDITIONS_MAPPING" 
   (	"XFROM" NUMBER(*,0), 
	"YFROM" NUMBER(*,0), 
	"ZFROM" NUMBER(*,0), 
	"XTO" NUMBER(*,0), 
	"YTO" NUMBER(*,0), 
	"ZTO" NUMBER(*,0), 
	"COMPL_ORDER_FROM" NUMBER(*,0), 
	"COMPL_ORDER_TO" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_COMPL_RESERVE

  CREATE TABLE "RABAEV"."RRL_COMPL_RESERVE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PARTIONID" VARCHAR2(250) COLLATE "USING_NLS_COMP", 
	"QTY" NUMBER, 
	"ORDERID" NUMBER, 
	"ORDERROWID" NUMBER, 
	"CONDITION" NUMBER, 
	"EXPDATE" DATE, 
	"MOD_ID" NUMBER, 
	"WARE_ID" NUMBER, 
	 CONSTRAINT "RRL_COMPL_RESERVE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_COMPL_SEQ

  CREATE TABLE "RABAEV"."RRL_COMPL_SEQ" 
   (	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"WARE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SEQ" NUMBER(*,0) NOT NULL ENABLE, 
	"SEQ_GROUP" NUMBER(*,0) NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_CONSTANTS

  CREATE TABLE "RABAEV"."RRL_CONSTANTS" 
   (	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"VALUE" VARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_CROSS_DOCKING_ZONES

  CREATE TABLE "RABAEV"."RRL_CROSS_DOCKING_ZONES" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CELL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CONDITION_FROM_COUNT" NUMBER, 
	"CONDITION_TO_COUNT" NUMBER, 
	 CONSTRAINT "RRL_CROSS_DOCKING_ZONES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ERROR_LOG

  CREATE TABLE "RABAEV"."RRL_ERROR_LOG" 
   (	"ERROR" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"DATET" DATE, 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_EVENTS

  CREATE TABLE "RABAEV"."RRL_EVENTS" 
   (	"ID_EVENT" NUMBER, 
	"CELL_FROM" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"CELL_TO" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"DATE_EVENT" DATE NOT NULL ENABLE, 
	"DATE_OF_ORDER" DATE, 
	"COUNT_EVENT" NUMBER, 
	"TYPE_EVENT" NUMBER(38,0) NOT NULL ENABLE, 
	"UID_POLETA" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PRIHOD_NAKL_ID" NUMBER(*,0) DEFAULT 0, 
	"OTHOD_NAKL_ID" NUMBER(*,0) DEFAULT 0, 
	"PALLET_ROW_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_HISTORY_NOTES

  CREATE TABLE "RABAEV"."RRL_HISTORY_NOTES" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ADDR_TO" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ADDR_FROM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"MESS" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"PUID" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"COUNT1" NUMBER, 
	"EVENTDATE" DATE, 
	"MESS2" VARCHAR2(1024) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_INVENTARIZ_LINES

  CREATE TABLE "RABAEV"."RRL_INVENTARIZ_LINES" 
   (	"ID_OF_INVENT" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_LINE" NUMBER(*,0), 
	"CELL" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PALLET_ID" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COUNT1" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_INVETARIZ

  CREATE TABLE "RABAEV"."RRL_INVETARIZ" 
   (	"ID" NUMBER(*,0), 
	"DATE_OF" DATE NOT NULL ENABLE, 
	"TYPE1" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_LOGIN_HISTORY

  CREATE TABLE "RABAEV"."RRL_LOGIN_HISTORY" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"START_TIME" DATE, 
	"IP_ADDR" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"VERSION" VARCHAR2(150) COLLATE "USING_NLS_COMP", 
	"END_TIME" DATE, 
	"PASS" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SUCCSESS" NUMBER(*,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_OBJECT

  CREATE TABLE "RABAEV"."RRL_OBJECT" 
   (	"OBJECT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BUSINESS_FIELD" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PARENT_OBJECT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COMMENT1" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"TYPE1" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT 'TABLE', 
	"ARTICLE1" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "RRL_OBJECT_PK" PRIMARY KEY ("OBJECT_NAME")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ORDER_PALLET_ROWS

  CREATE TABLE "RABAEV"."RRL_ORDER_PALLET_ROWS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ARTICUL" VARCHAR2(15) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SHORTNAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EI" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP", 
	"ORDER_WEIGHT" NUMBER, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"SORTFIELD" NUMBER(*,0), 
	"WARE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PACK_COUNT" NUMBER(*,0), 
	"ORIGINAL_QUANTITY" NUMBER DEFAULT 0, 
	"ORIGINAL_ORDER_WEIGHT" NUMBER DEFAULT 0, 
	"CONDITION" NUMBER(*,0), 
	"TARESIZE" NUMBER, 
	"TAREWEIGHT" NUMBER, 
	"VERSION_D" NUMBER(*,0), 
	"PALL_NUMB" NUMBER(*,0), 
	 CONSTRAINT "RRL_ORDER_PALLET_ROWS_I1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ORDER_ROWS

  CREATE TABLE "RABAEV"."RRL_ORDER_ROWS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ARTICUL" VARCHAR2(15) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SHORTNAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EI" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP", 
	"ORDER_WEIGHT" NUMBER, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"SORTFIELD" NUMBER(*,0), 
	"WARE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PACK_COUNT" NUMBER(*,0), 
	"ORIGINAL_QUANTITY" NUMBER DEFAULT 0, 
	"ORIGINAL_ORDER_WEIGHT" NUMBER DEFAULT 0, 
	"CONDITION" NUMBER(*,0), 
	"TARESIZE" NUMBER, 
	"TAREWEIGHT" NUMBER, 
	"MOD_ID" NUMBER DEFAULT 0, 
	"QUANTITY_PLANNED" NUMBER DEFAULT 0, 
	"PARTIONPLANNED" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "RRL_ORDER_ROWS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ORDERS

  CREATE TABLE "RABAEV"."RRL_ORDERS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORD_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"WARE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ADDR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ORDDATE" DATE, 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COND" NUMBER DEFAULT 0, 
	"ORD1" NUMBER DEFAULT 0, 
	 CONSTRAINT "RRL_ORDERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_ORDERS_PALL_VERSIONS

  CREATE GLOBAL TEMPORARY TABLE "RABAEV"."RRL_ORDERS_PALL_VERSIONS" 
   (	"VERSION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORD_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MAXMASS" NUMBER, 
	"MAXVOL" NUMBER, 
	"COUNT_OF_PALL" NUMBER(*,0), 
	"VOLUME_OF_MAX_PAL" NUMBER, 
	"VOLUME_OF_MIN_PAL" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT DELETE ROWS ;

prompt TABLE RRL_OTHOD_NAKLAD

  CREATE TABLE "RABAEV"."RRL_OTHOD_NAKLAD" 
   (	"ID" NUMBER(*,0), 
	"NAKLADNAME" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MAG_NO" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NAKLADDATE" DATE NOT NULL ENABLE, 
	"CREATIONDATE" DATE NOT NULL ENABLE, 
	"PLANNEDDELIVERYDATE" DATE, 
	"CONDITION" NUMBER(*,0) DEFAULT 0, 
	"SUMM" NUMBER DEFAULT 0, 
	"WARE_ID" NUMBER(*,0) DEFAULT 1
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_OTHOD_NAKLAD_ROWS

  CREATE TABLE "RABAEV"."RRL_OTHOD_NAKLAD_ROWS" 
   (	"ID" NUMBER(*,0), 
	"ID_NAKLAD" NUMBER(*,0) NOT NULL ENABLE, 
	"ARTICUL" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COUNT1" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_PALLETS

  CREATE TABLE "RABAEV"."RRL_PALLETS" 
   (	"UID_PALLET" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"ARTICUL" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"UNIT_COUNT" NUMBER, 
	"PRICE" NUMBER, 
	"PRIHOD_NAKLAD_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRINTED" NUMBER(*,0) DEFAULT 0, 
	"KLADOVSHIK" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"PRODUCED_DATE" DATE, 
	"MOD_ID" NUMBER(*,0), 
	"WEIGHT_BRUTTO" NUMBER, 
	"WEIGHT_TN" NUMBER, 
	"DEFECT_PERC" NUMBER DEFAULT 0, 
	"COUNT_KOR" NUMBER(*,0), 
	"DEFECT_PERC_INCOME" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_PRIHOD_NAKLAD

  CREATE TABLE "RABAEV"."RRL_PRIHOD_NAKLAD" 
   (	"NAKLAD_NUMBER" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"DATE_OF_NAKLAD" DATE, 
	"DATE_OF_ACCEPT" DATE, 
	"POSTAVSHIK_NAME" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"SM_NAKLAD_NUMBER" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"CONDITION" NUMBER(*,0) DEFAULT 0, 
	"ID" NUMBER(*,0), 
	"WARE_ID" NUMBER(*,0) DEFAULT 1, 
	"ZAKAZ_NUMBER" VARCHAR2(20) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_PRIHOD_NAKLAD_ROWS

  CREATE TABLE "RABAEV"."RRL_PRIHOD_NAKLAD_ROWS" 
   (	"ORDID" NUMBER(*,0), 
	"ARTICUL" VARCHAR2(15 CHAR) COLLATE "USING_NLS_COMP", 
	"EXPIRY_DATE" DATE, 
	"ID" NUMBER(*,0), 
	"COUNT1" NUMBER DEFAULT 0, 
	"PRICE" NUMBER DEFAULT 0, 
	"INVENT_CELL" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"KOLPAL" NUMBER, 
	"SROK_GODNOSTI" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_PRINTFORMS

  CREATE TABLE "RABAEV"."RRL_PRINTFORMS" 
   (	"ID" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CONTENT" CLOB COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "RRL_PRINTFORMS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_REMAINS

  CREATE TABLE "RABAEV"."RRL_REMAINS" 
   (	"CELL" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"UID_POLETA" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"REMAIN" NUMBER, 
	"OTHOD_NAKL_ID" NUMBER(*,0) DEFAULT 0, 
	"TIME_OF_LAST_UPDATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_REMAIN_SNAPSHOT

  CREATE TABLE "RABAEV"."RRL_REMAIN_SNAPSHOT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TYPE1" NUMBER NOT NULL ENABLE, 
	"SNAP_SHOT_TIME" DATE NOT NULL ENABLE, 
	"CLOSED" NUMBER DEFAULT 0, 
	"CREATE_TIME" DATE, 
	 CONSTRAINT "RRL_REMAIN_SNAPSHOT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_REMAIN_SNAPSHOT_ROWS

  CREATE TABLE "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PALLET_UID" VARCHAR2(150) COLLATE "USING_NLS_COMP", 
	"CELL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"WARE_ID" NUMBER, 
	"SNAP_TIME" DATE, 
	"REMAIN" NUMBER, 
	"CONDITION" NUMBER DEFAULT 0, 
	"SNAP_SHOT_ID" NUMBER, 
	 CONSTRAINT "RRL_REMAIN_SNAPSHOT_ROWS_I1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_REVISION_ROW

  CREATE TABLE "RABAEV"."RRL_REVISION_ROW" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"REVISION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CELL" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"REMARK1" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"COUNT1" NUMBER, 
	"REV_DATE" DATE, 
	"COUNT_KOR" NUMBER, 
	"ARTICUL1" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"NUM_OF_PALL" NUMBER, 
	 CONSTRAINT "RRL_REVISION_ROW_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_REVIZION

  CREATE TABLE "RABAEV"."RRL_REVIZION" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"WARE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"CONDITION" NUMBER(*,0) DEFAULT 0, 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"REV_NAKLAD_ID" NUMBER, 
	"SNAPSHOT_BEFORE" NUMBER, 
	"SNAPSHOT_AFTER" NUMBER, 
	 CONSTRAINT "RRL_REVIZION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_SBORKA_PALLET_ROWS

  CREATE TABLE "RABAEV"."RRL_SBORKA_PALLET_ROWS" 
   (	"ID" NUMBER(*,0), 
	"PALLET_UID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ARTICUL" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"SHORTNAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SHTRIHKOD" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"EI" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP", 
	"TAREWEIGHT" NUMBER, 
	"ORDER_WEIGHT" NUMBER, 
	"TARESIZE" NUMBER, 
	"QUANTITY" NUMBER, 
	"SORTFIELD" NUMBER(*,0), 
	"AUCTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DOCID" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"WARE_ID" NUMBER(*,0), 
	"PATH" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PACK_COUNT" NUMBER(*,0), 
	"ORIGINAL_QUANTITY" NUMBER DEFAULT 0, 
	"ORIGINAL_ORDER_WEIGHT" NUMBER DEFAULT 0, 
	"TIME_OF_CHECKING" DATE, 
	"CURRENT_MOD_ID" NUMBER(*,0), 
	"SELECTED" NUMBER(*,0), 
	"VYCHERK_USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PRIHOD_PALLET_UID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SOBRANO" NUMBER, 
	"EXPIRY_DATE" DATE, 
	"PRIHOD_PALLET_UID_COUNT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_SBORKA_PALLETS

  CREATE TABLE "RABAEV"."RRL_SBORKA_PALLETS" 
   (	"ID" NUMBER(*,0), 
	"ST_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CREATE_DATE" DATE, 
	"WARE_ID" NUMBER(*,0), 
	"PALLET_NUMBER" NUMBER(*,0), 
	"PALLET_UID" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"ADDR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"STDATE" DATE, 
	"NAKLAD_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TRANSTASK_ID" NUMBER(*,0), 
	"ROWS_NUMBER" NUMBER(*,0) DEFAULT 0, 
	"NAPR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ORIGINAL_ST_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"WOOD_WEIGHT" NUMBER DEFAULT 0, 
	"PROOVED" NUMBER(*,0) DEFAULT 0, 
	"TRIAL_WEIGHT" NUMBER DEFAULT 0, 
	"ZONE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ORD" NUMBER(*,0) DEFAULT 0, 
	"SBORSHIK" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"KLADOVSHIK" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"PROOVED_BY_SCAN" NUMBER(*,0) DEFAULT 0, 
	"PRIM" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"COUNT_OF_ERRORS" NUMBER(*,0) DEFAULT 0, 
	"VESOVSHIK" VARCHAR2(55) COLLATE "USING_NLS_COMP", 
	"TT_OPLATA" NUMBER DEFAULT 0, 
	"CONDITION" NUMBER(*,0) DEFAULT 0, 
	"COUNT_OF_PRINTS" NUMBER(*,0) DEFAULT 0, 
	"ZONE_TIME_PLAN_IN" TIMESTAMP (0), 
	"ZONE_TIME_PLAN_OUT" TIMESTAMP (0), 
	"IP_ADDR" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COUNT_OF_PRINTS2" NUMBER(*,0) DEFAULT 0, 
	"SUMMARY_TASK_ID" NUMBER(*,0), 
	"COUNT_OF_PRINTS3" NUMBER(*,0) DEFAULT 0, 
	"USER_ID_LAST_UPD" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ORIGINAL_ORDER_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CHECKING_TIME" DATE, 
	"REMOTE_ID" NUMBER(*,0), 
	"KROSS_WEIGHT" NUMBER, 
	"REMOTE_TT_ID" NUMBER(*,0), 
	"KROSS_SYNCRONIZED" NUMBER(*,0), 
	"RETURN_SUPPLIER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_SBORKA_PALLETS_COND

  CREATE TABLE "RABAEV"."RRL_SBORKA_PALLETS_COND" 
   (	"COND" VARCHAR2(25) COLLATE "USING_NLS_COMP", 
	"DONE" NUMBER(*,0) DEFAULT 0, 
	"SENDT" NUMBER(*,0) DEFAULT 1, 
	"IN_PROCESS" NUMBER(*,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_SBORKA_PALLETS_HISTORY

  CREATE TABLE "RABAEV"."RRL_SBORKA_PALLETS_HISTORY" 
   (	"ID" NUMBER(*,0), 
	"PALLET_UID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ZONE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"EVENT" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TIME1" DATE, 
	"WEIGHT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_SBORKA_PALL_ROWS_PARTS

  CREATE TABLE "RABAEV"."RRL_SBORKA_PALL_ROWS_PARTS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PALLET_UID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COUNT" NUMBER, 
	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"EXPIRY_DATE" DATE, 
	 CONSTRAINT "RRL_SBORKA_PALL_ROWS_PARTSPK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_SUMMARY_PICK_LIST

  CREATE TABLE "RABAEV"."RRL_SUMMARY_PICK_LIST" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CREATEDATE" DATE, 
	"CONDITION" NUMBER(*,0) DEFAULT 0, 
	"WARE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "RRL_SUMMARY_PICK_LIST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_SUMMARY_PICK_LIST_ROWS

  CREATE TABLE "RABAEV"."RRL_SUMMARY_PICK_LIST_ROWS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SPL_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER DEFAULT 0, 
	"QUANTITY_COMPLETE" NUMBER DEFAULT 0, 
	"CONDITION" NUMBER(*,0) DEFAULT 0, 
	"QUANTITY_PLANNED" NUMBER, 
	 CONSTRAINT "RRL_SUMMARY_PICK_LIST_ROWS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TOVARO_NOSITEL

  CREATE TABLE "RABAEV"."RRL_TOVARO_NOSITEL" 
   (	"ID" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TYPE_TN" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "RRL_TOVARO_NOSITEL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TRANSPORT_PRICE

  CREATE TABLE "RABAEV"."RRL_TRANSPORT_PRICE" 
   (	"ID" NUMBER(*,0), 
	"PRICE_NAME" VARCHAR2(1024) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(255) COLLATE "USING_NLS_COMP" DEFAULT null, 
	"RANGE1" NUMBER, 
	"PRICE_FOR_HOURS" NUMBER DEFAULT 0, 
	"TYPE_TR" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"PRICE_FOLDER" NUMBER(*,0) DEFAULT 0, 
	"PRICE_FOR_ADDR" NUMBER DEFAULT 0, 
	"NORM_HOURS" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TRANSPORT_TASK

  CREATE TABLE "RABAEV"."RRL_TRANSPORT_TASK" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CREATEDATE" DATE, 
	"TRANSPORT" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TRANSTYPE" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"ROUTETYPE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CONDITION" VARCHAR2(25) COLLATE "USING_NLS_COMP" DEFAULT '???????????', 
	"TRANSP_ZONE" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"WAVE" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"SHIPMENT_DATE" DATE, 
	"PLANNED_DELIVERY_DATE" DATE, 
	"VODITEL_ID" NUMBER(*,0), 
	"PRIMECHANIE" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"DELETED" NUMBER(*,0) DEFAULT 0, 
	"DOCK" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PRICE" NUMBER, 
	"HOURS" NUMBER, 
	"RANGE1" NUMBER, 
	"TEMP_REGION" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"PAY_ORDER_ID" NUMBER(*,0) DEFAULT 0, 
	"TEMP_WEIGHT" NUMBER, 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PAY_REGION" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"ADDR_PREMIO" NUMBER(*,0), 
	"SHIPMENT_TIME" DATE, 
	"DOCK_REZERV_TIME_FROM" TIMESTAMP (0), 
	"DOCK_REZERV_TIME_TO" TIMESTAMP (0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TRANSPORT_TASK_HISTORY

  CREATE TABLE "RABAEV"."RRL_TRANSPORT_TASK_HISTORY" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TTASK_ID" NUMBER(*,0), 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TRANSTYPE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"TRANSPORT" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ROUTETYPE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"SHIPMENT_TIME" DATE, 
	"VODITEL_ID" NUMBER(*,0), 
	"PRIMECHANIE" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"DOCK" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SHIPMENT_DATE" DATE, 
	"OPERATION" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"EVENT_TIME" TIMESTAMP (0), 
	"ST_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "BIN$UX1xZvV8S6/gYw8CAAo/Yg==$0" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "RABAEV"."BIN$UX1xZvV/S6/gYw8CAAo/Yg==$0" ON "RABAEV"."RRL_TRANSPORT_TASK_HISTORY" ("ID") 
  )  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TRANSPORT_TYPE

  CREATE TABLE "RABAEV"."RRL_TRANSPORT_TYPE" 
   (	"TRANSPORTTYPE" VARCHAR2(25) COLLATE "USING_NLS_COMP", 
	"REF" NUMBER(*,0), 
	"NORMA_PALLET" NUMBER(*,0), 
	"NORMA_WEIGHT" NUMBER, 
	"ORD" NUMBER(*,0), 
	"MIN_PALLET_LOAD" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TR_VEHICLE

  CREATE TABLE "RABAEV"."RRL_TR_VEHICLE" 
   (	"ID" NUMBER(*,0), 
	"NUM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TR_TYPE" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"MARKA" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"REF_REJIM" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT '���', 
	"WORKING_NOW" NUMBER(*,0) DEFAULT 1, 
	"PALLETS" NUMBER(*,0), 
	"BLOCKED" NUMBER(*,0) DEFAULT 0, 
	"GIDROBORT" NUMBER(*,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TR_VODITEL

  CREATE TABLE "RABAEV"."RRL_TR_VODITEL" 
   (	"ID" NUMBER(*,0), 
	"F" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"I" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"O" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"DELETED" NUMBER(*,0) DEFAULT 0, 
	"SOBSTVENNYY" NUMBER(*,0) DEFAULT 0, 
	"VEH_ID" NUMBER(*,0), 
	"PASSPORT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DOVERENNOST_OT" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TRANSPORT_NUM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ADDR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TEL" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TR_VODITEL_EXT

  CREATE TABLE "RABAEV"."RRL_TR_VODITEL_EXT" 
   (	"VOD_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TABEL_NO" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"INN" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"LAST_UPD" DATE DEFAULT sysdate, 
	"USER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "BIN$UX1xZvWCS6/gYw8CAAo/Yg==$0" PRIMARY KEY ("VOD_ID")
  USING INDEX (CREATE UNIQUE INDEX "RABAEV"."BIN$UX1xZvWDS6/gYw8CAAo/Yg==$0" ON "RABAEV"."RRL_TR_VODITEL_EXT" ("VOD_ID") 
  )  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TT_BILL_PRICE_KM

  CREATE TABLE "RABAEV"."RRL_TT_BILL_PRICE_KM" 
   (	"TT" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"KM_FROM" NUMBER(*,0), 
	"KM_TO" NUMBER(*,0), 
	"PRICE" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TT_DOCK

  CREATE TABLE "RABAEV"."RRL_TT_DOCK" 
   (	"DOCK" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"WARE_ID" NUMBER(*,0), 
	"ORD" NUMBER(*,0), 
	"COUNT_OF_PALLETS" NUMBER(*,0) DEFAULT 0, 
	"DOCK_IS_BLOCKED" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TT_GLOBAL_MESS

  CREATE TABLE "RABAEV"."RRL_TT_GLOBAL_MESS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MESS" VARCHAR2(250) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "RRL_TT_GLOBAL_MESS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TT_LOAD_TASK

  CREATE TABLE "RABAEV"."RRL_TT_LOAD_TASK" 
   (	"TT_ID" NUMBER(*,0), 
	"DOCK" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"LOAD_FROM" DATE, 
	"LOAD_TO" DATE, 
	"WARE_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TT_PATH

  CREATE TABLE "RABAEV"."RRL_TT_PATH" 
   (	"PATH1" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"RANGE1" NUMBER, 
	"NORMATIVE_HOURS" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TT_ZONES

  CREATE TABLE "RABAEV"."RRL_TT_ZONES" 
   (	"ZONE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"SUB_ZONE" VARCHAR2(25) COLLATE "USING_NLS_COMP", 
	"DOCK" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"X" NUMBER DEFAULT 1000, 
	"Y" NUMBER DEFAULT 1000
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_TYPE_PALL

  CREATE TABLE "RABAEV"."RRL_TYPE_PALL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "RRL_TYPE_PALL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_VERSIONS

  CREATE TABLE "RABAEV"."RRL_VERSIONS" 
   (	"VERSION" VARCHAR2(150) COLLATE "USING_NLS_COMP", 
	"ALLOW" NUMBER(*,0) DEFAULT 1
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_WARE_DISTR_TIME_PARAM

  CREATE TABLE "RABAEV"."RRL_WARE_DISTR_TIME_PARAM" 
   (	"WARE_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TIME_PERC_FROM" NUMBER, 
	"TIME_PERC_TO" NUMBER, 
	"DISTR_PERC" NUMBER, 
	"CLIENT_GROUP" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_WARE_MASKS

  CREATE TABLE "RABAEV"."RRL_WARE_MASKS" 
   (	"WARE_MASK" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"WARE_MASK_IDS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ORD_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_WARES

  CREATE TABLE "RABAEV"."RRL_WARES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"OVERFLOW_CELL_NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT 'OVERFLOW', 
	"PREFIX" VARCHAR2(3) COLLATE "USING_NLS_COMP", 
	"FAKE_ROWS" NUMBER(*,0) DEFAULT 0, 
	"FAKE_ART" VARCHAR2(25) COLLATE "USING_NLS_COMP" DEFAULT 'Z0001', 
	"BLOCK_IF_NO_PROOVE" NUMBER(*,0) DEFAULT 0, 
	"VERIFY_VYCHERK" NUMBER(*,0) DEFAULT 0, 
	"WRITE_BOTH_EXPIRYANDBEST" NUMBER(*,0) DEFAULT 0, 
	"SPIS_IF_HRAN_NO_EMPTY" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"ALLOW_HALF_VYCHERK" NUMBER(*,0) DEFAULT 1, 
	"SPIS_OTBOR_ON_SCAN_OPALL" NUMBER(*,0) DEFAULT 0, 
	"SPIS_OTBOR_ON_WPROOVE_OPALL" NUMBER(*,0) DEFAULT 0, 
	"TIME_COEFF" NUMBER DEFAULT 0.33, 
	"XYZ_XCOV" NUMBER DEFAULT 0.1, 
	"XYZ_YCOV" NUMBER DEFAULT 0.5, 
	"ABC_A" NUMBER DEFAULT 0.8, 
	"ABC_B" NUMBER DEFAULT 0.10, 
	"ABC_XYZ_TIME_EDGES_IN_DAYS" NUMBER(30,0), 
	"VERIFY_VYCHERK_IN_OTBOR" NUMBER(*,0) DEFAULT 0, 
	"PRINT_EXPIRY_DATE_OP" NUMBER(*,0) DEFAULT 0, 
	"COUNT_OF_PRINTS" NUMBER(*,0) DEFAULT 10000, 
	"WEIGHT_LIMIT_WARNING" NUMBER(*,0) DEFAULT 0, 
	"WEIGHT_LIMIT_STOP" NUMBER(*,0) DEFAULT 0, 
	"PARENT_WARE_ID" NUMBER(*,0), 
	"ORD2" NUMBER(*,0), 
	"COUNT_WEIGHT_AUTORECALC" NUMBER(*,0) DEFAULT 0, 
	"AUTO_PLAN_DOCK" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_WARE_TRACKS

  CREATE TABLE "RABAEV"."RRL_WARE_TRACKS" 
   (	"WTRACK" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SPEEDX" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"ZLIMIT" NUMBER DEFAULT 2, 
	"SPEEDZ" NUMBER DEFAULT 0.5 NOT NULL ENABLE, 
	"SPEEDY" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"WARE_ID" NUMBER(*,0) DEFAULT 3, 
	 CONSTRAINT "RRL_WARE_TRACKS_PK" PRIMARY KEY ("WTRACK")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RRL_WT

  CREATE TABLE "RABAEV"."RRL_WT" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TYPE1" VARCHAR2(5) COLLATE "USING_NLS_COMP", 
	"PUID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"FROM1" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"TO1" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COUNT1" NUMBER, 
	"PLAN_START_TIME" DATE, 
	"PLAN_END_TIME" DATE, 
	"FACT_START_TIME" DATE, 
	"FACT_END_TIME" DATE, 
	"WORKER" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CONDTION" NUMBER(*,0) DEFAULT 0, 
	"PARENT_ID" NUMBER(*,0), 
	"ORDER1" NUMBER(*,0), 
	"ARTICUL" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"FLAG_LAST_PAL" NUMBER(*,0) DEFAULT 0, 
	"FLAG_PARTIAL" NUMBER(*,0) DEFAULT 0, 
	 CONSTRAINT "RRL_WT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE RUSERS

  CREATE TABLE "RABAEV"."RUSERS" 
   (	"ID" NVARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NAME" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PRAVO_INVENTORY_EDIT" NUMBER(*,0) DEFAULT 0, 
	"PRAVO_CHECK_ORDER" NUMBER(*,0) DEFAULT 0, 
	"PRAVO_LIGHT_INVENTORY_CHECK" NUMBER(*,0) DEFAULT 0, 
	"DELETED" NUMBER(*,0) DEFAULT 0, 
	"PRAVO_RAZVOZ_ZAYAVOK" NUMBER(*,0) DEFAULT 0, 
	"WMSUSER_ID" VARCHAR2(5) COLLATE "USING_NLS_COMP", 
	"PRAVO_EAN_PRODUCT_CHANGE" NUMBER(*,0) DEFAULT 0, 
	"PRAVO_KARSHIK" NUMBER(*,0) DEFAULT 0, 
	"WARE_ID" NUMBER(*,0) DEFAULT 1, 
	"PASS" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PRAVO_ADMIN_LOGIN" NUMBER(*,0), 
	"SMFILEPATH" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"IP_SERVER_PRINT" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"USER_GROUP" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"SMENA" VARCHAR2(5) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE SFERA_EAN

  CREATE TABLE "RABAEV"."SFERA_EAN" 
   (	"TMC_UID" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"EAN_SHT" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"EAN_BL" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"EAN_KOR" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"MANUALENTER" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"SHT_IN_BL" NUMBER(*,0) NOT NULL ENABLE, 
	"BL_IN_KOR" NUMBER(*,0) NOT NULL ENABLE, 
	"���" NUMBER(*,0), 
	"NAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

prompt TABLE TMP_ORDERS_PALL_VERSIONS

  CREATE GLOBAL TEMPORARY TABLE "RABAEV"."TMP_ORDERS_PALL_VERSIONS" 
   (	"VERSION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORD_NUMBER" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MAXMASS" NUMBER, 
	"MAXVOL" NUMBER, 
	"COUNT_OF_PALL" NUMBER(*,0), 
	"VOLUME_OF_MAX_PAL" NUMBER, 
	"VOLUME_OF_MIN_PAL" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT DELETE ROWS ;

prompt TABLE TMP_PALLET_ROWS

  CREATE GLOBAL TEMPORARY TABLE "RABAEV"."TMP_PALLET_ROWS" 
   (	"VERS" NUMBER(*,0), 
	"ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ARTICUL" VARCHAR2(15) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"EI" VARCHAR2(3) COLLATE "USING_NLS_COMP", 
	"ORDER_WEIGHT" NUMBER, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"SORTFIELD" NUMBER(*,0), 
	"PACK_COUNT" NUMBER(*,0), 
	"TARESIZE" NUMBER, 
	"TAREWEIGHT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT DELETE ROWS ;

prompt TABLE USER_GROUP

  CREATE TABLE "RABAEV"."USER_GROUP" 
   (	"ID" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

