set define off
set sqlblanklines on

prompt INDEX RRL_ALARMS_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_ALARMS_PK" ON "RABAEV"."RRL_ALARMS" ("ID") 
  ;

prompt INDEX RRL_COMPL_RESERVE_I1

  CREATE INDEX "RABAEV"."RRL_COMPL_RESERVE_I1" ON "RABAEV"."RRL_COMPL_RESERVE" ("ARTICUL", "WARE_ID") 
  ;

prompt INDEX RRL_COMPL_RESERVE_I2

  CREATE INDEX "RABAEV"."RRL_COMPL_RESERVE_I2" ON "RABAEV"."RRL_COMPL_RESERVE" ("ORDERID", "ORDERROWID") 
  ;

prompt INDEX RRL_COMPL_RESERVE_I3

  CREATE INDEX "RABAEV"."RRL_COMPL_RESERVE_I3" ON "RABAEV"."RRL_COMPL_RESERVE" ("PARTIONID") 
  ;

prompt INDEX RRL_COMPL_RESERVE_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_COMPL_RESERVE_PK" ON "RABAEV"."RRL_COMPL_RESERVE" ("ID") 
  ;

prompt INDEX RRL_COMPL_SEQ_I1

  CREATE INDEX "RABAEV"."RRL_COMPL_SEQ_I1" ON "RABAEV"."RRL_COMPL_SEQ" ("ARTICUL", "WARE_ID") 
  ;

prompt INDEX RRL_COMPL_SEQ_I2

  CREATE INDEX "RABAEV"."RRL_COMPL_SEQ_I2" ON "RABAEV"."RRL_COMPL_SEQ" ("SEQ_GROUP") 
  ;

prompt INDEX RRL_COMPL_SEQ_I3

  CREATE INDEX "RABAEV"."RRL_COMPL_SEQ_I3" ON "RABAEV"."RRL_COMPL_SEQ" ("SEQ") 
  ;

prompt INDEX RRL_CONSTANTS_I1

  CREATE INDEX "RABAEV"."RRL_CONSTANTS_I1" ON "RABAEV"."RRL_CONSTANTS" ("NAME") 
  ;

prompt INDEX RRL_CROSS_DOCKING_ZONES_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_CROSS_DOCKING_ZONES_PK" ON "RABAEV"."RRL_CROSS_DOCKING_ZONES" ("ID") 
  ;

prompt INDEX RRL_OBJECT_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_OBJECT_PK" ON "RABAEV"."RRL_OBJECT" ("OBJECT_NAME") 
  ;

prompt INDEX RRL_ORDER_PALLET_ROWS_I1

  CREATE UNIQUE INDEX "RABAEV"."RRL_ORDER_PALLET_ROWS_I1" ON "RABAEV"."RRL_ORDER_PALLET_ROWS" ("ID") 
  ;

prompt INDEX RRL_ORDER_PALLET_ROWS_I2

  CREATE INDEX "RABAEV"."RRL_ORDER_PALLET_ROWS_I2" ON "RABAEV"."RRL_ORDER_PALLET_ROWS" ("ORDER_ID", "ARTICUL", "PALL_NUMB", "VERSION_D") 
  ;

prompt INDEX RRL_ORDER_ROWS_I1

  CREATE INDEX "RABAEV"."RRL_ORDER_ROWS_I1" ON "RABAEV"."RRL_ORDER_ROWS" ("ARTICUL", "ORDER_ID", "WARE_ID") 
  ;

prompt INDEX RRL_ORDER_ROWS_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_ORDER_ROWS_PK" ON "RABAEV"."RRL_ORDER_ROWS" ("ID") 
  ;

prompt INDEX RRL_ORDERS_I1

  CREATE INDEX "RABAEV"."RRL_ORDERS_I1" ON "RABAEV"."RRL_ORDERS" ("CREATE_DATE", "ORD_NUMBER", "WARE_ID", "ADDR", "STATE", "USER_ID") 
  ;

prompt INDEX RRL_ORDERS_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_ORDERS_PK" ON "RABAEV"."RRL_ORDERS" ("ID") 
  ;

prompt INDEX RRL_ORDERS_UI8

  CREATE UNIQUE INDEX "RABAEV"."RRL_ORDERS_UI8" ON "RABAEV"."RRL_ORDERS" ("ORD_NUMBER") 
  ;

prompt INDEX RRL_PEMAIN_SNAPSHOT_ROWS_I2

  CREATE INDEX "RABAEV"."RRL_PEMAIN_SNAPSHOT_ROWS_I2" ON "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS" ("ARTICUL", "PALLET_UID", "CELL", "WARE_ID") 
  ;

prompt INDEX RRL_PRINTFORMS_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_PRINTFORMS_PK" ON "RABAEV"."RRL_PRINTFORMS" ("ID") 
  ;

prompt INDEX RRL_REMAIN_SNAPSHOT_I1

  CREATE INDEX "RABAEV"."RRL_REMAIN_SNAPSHOT_I1" ON "RABAEV"."RRL_REMAIN_SNAPSHOT" ("TYPE1", "CLOSED") 
  ;

prompt INDEX RRL_REMAIN_SNAPSHOT_I2

  CREATE INDEX "RABAEV"."RRL_REMAIN_SNAPSHOT_I2" ON "RABAEV"."RRL_REMAIN_SNAPSHOT" ("SNAP_SHOT_TIME", "CREATE_TIME") 
  ;

prompt INDEX RRL_REMAIN_SNAPSHOT_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_REMAIN_SNAPSHOT_PK" ON "RABAEV"."RRL_REMAIN_SNAPSHOT" ("ID") 
  ;

prompt INDEX RRL_REMAIN_SNAPSHOT_ROWS_I1

  CREATE UNIQUE INDEX "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS_I1" ON "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS" ("ID") 
  ;

prompt INDEX RRL_REMAIN_SNAPSHOT_ROWS_I11

  CREATE INDEX "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS_I11" ON "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS" ("SNAP_SHOT_ID") 
  ;

prompt INDEX RRL_REMAIN_SNAPSHOT_ROWS_I9

  CREATE INDEX "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS_I9" ON "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS" ("CONDITION") 
  ;

prompt INDEX RRL_REMIAN_SNAPSHOT_ROWS_I5

  CREATE INDEX "RABAEV"."RRL_REMIAN_SNAPSHOT_ROWS_I5" ON "RABAEV"."RRL_REMAIN_SNAPSHOT_ROWS" ("SNAP_TIME") 
  ;

prompt INDEX RRL_REVISION_ROW_I1

  CREATE INDEX "RABAEV"."RRL_REVISION_ROW_I1" ON "RABAEV"."RRL_REVISION_ROW" ("REVISION_ID", "CELL") 
  ;

prompt INDEX RRL_REVISION_ROW_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_REVISION_ROW_PK" ON "RABAEV"."RRL_REVISION_ROW" ("ID") 
  ;

prompt INDEX RRL_REVIZION_I

  CREATE INDEX "RABAEV"."RRL_REVIZION_I" ON "RABAEV"."RRL_REVIZION" ("WARE_ID", "CONDITION", "USER_ID") 
  ;

prompt INDEX RRL_REVIZION_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_REVIZION_PK" ON "RABAEV"."RRL_REVIZION" ("ID") 
  ;

prompt INDEX RRL_SBORKA_PALL_ROWS_PARTSI1

  CREATE INDEX "RABAEV"."RRL_SBORKA_PALL_ROWS_PARTSI1" ON "RABAEV"."RRL_SBORKA_PALL_ROWS_PARTS" ("PALLET_UID", "ARTICUL") 
  ;

prompt INDEX RRL_SBORKA_PALL_ROWS_PARTSPK

  CREATE UNIQUE INDEX "RABAEV"."RRL_SBORKA_PALL_ROWS_PARTSPK" ON "RABAEV"."RRL_SBORKA_PALL_ROWS_PARTS" ("ID") 
  ;

prompt INDEX RRL_SUMMARY_PICK_LIST_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_SUMMARY_PICK_LIST_PK" ON "RABAEV"."RRL_SUMMARY_PICK_LIST" ("ID") 
  ;

prompt INDEX RRL_SUMMARY_PICK_LIST_ROWS_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_SUMMARY_PICK_LIST_ROWS_PK" ON "RABAEV"."RRL_SUMMARY_PICK_LIST_ROWS" ("ID") 
  ;

prompt INDEX RRL_TOVARO_NOSITEL_I1

  CREATE INDEX "RABAEV"."RRL_TOVARO_NOSITEL_I1" ON "RABAEV"."RRL_TOVARO_NOSITEL" ("TYPE_TN") 
  ;

prompt INDEX RRL_TOVARO_NOSITEL_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_TOVARO_NOSITEL_PK" ON "RABAEV"."RRL_TOVARO_NOSITEL" ("ID") 
  ;

prompt INDEX RRL_TT_GLOBAL_MESS_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_TT_GLOBAL_MESS_PK" ON "RABAEV"."RRL_TT_GLOBAL_MESS" ("ID") 
  ;

prompt INDEX RRL_TYPE_PALL_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_TYPE_PALL_PK" ON "RABAEV"."RRL_TYPE_PALL" ("ID") 
  ;

prompt INDEX RRL_TYPE_PALL_U1

  CREATE UNIQUE INDEX "RABAEV"."RRL_TYPE_PALL_U1" ON "RABAEV"."RRL_TYPE_PALL" ("NAME") 
  ;

prompt INDEX RRL_WARE_TRACKS_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_WARE_TRACKS_PK" ON "RABAEV"."RRL_WARE_TRACKS" ("WTRACK") 
  ;

prompt INDEX RRL_WT_I1

  CREATE INDEX "RABAEV"."RRL_WT_I1" ON "RABAEV"."RRL_WT" ("CONDTION", "WORKER") 
  ;

prompt INDEX RRL_WT_I2

  CREATE INDEX "RABAEV"."RRL_WT_I2" ON "RABAEV"."RRL_WT" ("TYPE1") 
  ;

prompt INDEX RRL_WT_I5

  CREATE INDEX "RABAEV"."RRL_WT_I5" ON "RABAEV"."RRL_WT" ("PUID", "FROM1", "TO1") 
  ;

prompt INDEX RRL_WT_I7

  CREATE INDEX "RABAEV"."RRL_WT_I7" ON "RABAEV"."RRL_WT" ("PLAN_START_TIME", "PLAN_END_TIME", "FACT_START_TIME", "FACT_END_TIME") 
  ;

prompt INDEX RRL_WT_I8

  CREATE INDEX "RABAEV"."RRL_WT_I8" ON "RABAEV"."RRL_WT" ("PARENT_ID") 
  ;

prompt INDEX RRL_WT_PK

  CREATE UNIQUE INDEX "RABAEV"."RRL_WT_PK" ON "RABAEV"."RRL_WT" ("ID") 
  ;

prompt INDEX SYS_IL0000082172C00002$$

  CREATE UNIQUE INDEX "RABAEV"."SYS_IL0000082172C00002$$" ON "RABAEV"."RRL_PRINTFORMS" (
  ;

