SET DEFINE OFF;
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_BILLING', 'WARE_HEAD', 100, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('KOMPLECT', 'ST_SMEN', 46390, 'Права на раздачу заказов на сборку');
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('DELETE_ST', 'RAZVITIE', 102, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('INTERNAL_MOVE', 'STOCK_MANAGER', 267, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHECK_WEIGHT', 'STOCK_MANAGER', 268, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_BILLING', 'STOCK_MANAGER', 270, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_BILLING', 'KLADOVSHIK', 987, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'VESOV', 1223, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('INTERNAL_MOVE', 'VESOV', 1287, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_PALL_HIST', 'STOCK_MANAGER', 7634, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CREATE_TT_PRICE', 'LOGIST', 5478, 'Права на рассчет заработной платы');
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'REVIZOR', 200, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'REVIZOR', 201, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_BILLING', 'ST_SMEN', 400, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('INTERNAL_MOVE', 'ST_SMEN', 500, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'KLADOVSHIK', 600, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHECK_WEIGHT', 'KLADOVSHIK', 700, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_TT_BILLING', 'LOGIST', 564, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_BILLING', 'LOGIST', 6720, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CREATE_WARES', 'GLOBAL_ADMIN', 1011, 'Создание Складов');
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('PRINT_OP_PASSPORT_UNLIMIT', 'ST_SMEN', 12312, 'Права на распечатывание второй раз пакета документов');
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('PLAN_TT_TIME', 'LOGIST', 3189, 'Планирование даты отгрузки');
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'ST_PRIEMO_SD', 30, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'ST_PRIEMO_SD', 31, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'STOPPER', 122, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'STOCK_MANAGER', 300, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'STOCK_MANAGER', 3002, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('STOCK_MANAGER', 'VIEW_ADRESS', 2856, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('KOMPLECT', 'KLADOVSHIK', 5767, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHECK_WEIGHT', 'KLADOVSHIK', 4333, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CREATE_VYCHERK', 'KLADOVSHIK', 444, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'KLADOVSHIK', 5555, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CREATE_ROUTE', 'LOGIST', 1, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'LOGIST', 2, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('DELETE_ROUTE', 'LOGIST', 3, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHANGE_ROUTE', 'LOGIST', 4, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'LOGIST', 5, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('LOAD_ST', 'LOGIST', 6, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CREATE_VYCHERK', 'VESOV', 7, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'VESOV', 8, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('LOAD_ST', 'STOPPER', 9, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_VESOV', 'STOPPER', 10, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CREATE_VYCHERK', 'STOPPER', 11, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHANGE_ARTICUL', 'STOCK_MANAGER', 12, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ADRESS', 'LOGIST', 13, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_PALL_HIST', 'SB', 14, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('STOCK_MANAGER', 'STOCK_MANAGER', 15, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHANGE_VODITEL', 'LOGIST', 16, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'ST_SMEN', 17, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('DIVIDE_ST', 'LOGIST', 18, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('DIVIDE_ST', 'STOPPER', 19, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CREATE_FAKE_PAL', 'VESOV', 20, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHECK_WEIGHT', 'VESOV', 21, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ADRESS', 'WARE_HEAD', 4000, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHANGE_ADDR', 'LOGIST', 5000, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('VIEW_ROUTE', 'WARE_HEAD', 10000, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('INTERNAL_MOVE', 'WARE_HEAD', 9009, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('SECOND_CH_WOOD', 'VESOV2', 2344, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('STORNO_PRIHOD', 'RAZVITIE', 2134, 'Сторнирование накладной во 2-м состоянии');
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('OP_DELETE', 'VESOV', 2343, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('OP_CHANGE', 'VESOV', 2398, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('INTERNAL_MOVE', 'KLADOV', 6923, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CALC_TT_PRICE', 'LOGIST', 90147, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('EDIT_BILL_TT', 'LOGIST', 90148, NULL);
Insert into RABAEV.RIGHTS
   (RIGHT1, USER_GROUP, ID, DESCR)
 Values
   ('CHANGE_TT_DOCK', 'LOGIST', 6832, 'Планирование и смена дока для маршрута');
COMMIT;
