prompt Loading master seed data for WindowsApplication2 xp12
set define off
whenever sqlerror exit failure rollback

prompt Resetting target master tables
DELETE FROM RABAEV.RRL_TR_VODITEL;
DELETE FROM RABAEV.RRL_TR_VEHICLE;
DELETE FROM RABAEV.RRL_TT_ZONES;
DELETE FROM RABAEV.RRL_TT_DOCK;
DELETE FROM RABAEV.RRL_BILL_COMPANY;
DELETE FROM RABAEV.RRL_TRANSPORT_TYPE;
DELETE FROM RABAEV.RRL_CELLS;
DELETE FROM RABAEV.RRL_ARTICUL_MODS;
DELETE FROM RABAEV.RRL_ARTICULS;
DELETE FROM RABAEV.RRL_ADDR;
DELETE FROM RABAEV.RIGHTS;
DELETE FROM RABAEV.RUSERS;
DELETE FROM RABAEV.RRL_VERSIONS;
DELETE FROM RABAEV.RRL_CONSTANTS;
DELETE FROM RABAEV.RRL_WARE_MASKS;
DELETE FROM RABAEV.RRL_WARES;
COMMIT;

prompt Seeding required warehouses
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (0,  'WARE_0',  'OVERFLOW', 'Z', 'Z0001', 'OVERFLOW', 0);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (1,  'WARE_1',  'OVERFLOW', 'C', 'Z0001', 'OVERFLOW', 1);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (2,  'WARE_2',  'OVERFLOW', 'M', 'Z0001', 'OVERFLOW', 2);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (3,  'WARE_3',  'OVERFLOW', 'A', 'Z0001', 'OVERFLOW', 3);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (4,  'WARE_4',  'OVERFLOW', 'B', 'Z0001', 'OVERFLOW', 4);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (5,  'WARE_5',  'OVERFLOW', 'E', 'Z0001', 'OVERFLOW', 5);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (6,  'WARE_6',  'OVERFLOW', 'O', 'Z0001', 'OVERFLOW', 6);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (7,  'WARE_7',  'OVERFLOW', 'D', 'Z0001', 'OVERFLOW', 7);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (8,  'WARE_8',  'OVERFLOW', 'V', 'Z0001', 'OVERFLOW', 8);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (10, 'WARE_10', 'OVERFLOW', 'R', 'Z0001', 'OVERFLOW', 10);
INSERT INTO RABAEV.RRL_WARES (ID, NAME, OVERFLOW_CELL_NAME, PREFIX, FAKE_ART, SPIS_IF_HRAN_NO_EMPTY, ORD2) VALUES (12, 'WARE_12', 'OVERFLOW', 'T', 'Z0001', 'OVERFLOW', 12);
COMMIT;

prompt Loading imported master data
@master_seed/01_rights.sql
@master_seed/02_users.sql
@master_seed/03_addresses.sql
@master_seed/04_articuls.sql
@master_seed/05_articul_mods.sql
@master_seed/06_cells.sql
@master_seed/07_transport_types.sql
@master_seed/08_bill_company.sql
@master_seed/09_docks.sql
@master_seed/10_tt_zones.sql
@master_seed/11_vehicles.sql
@master_seed/12_voditeli.sql

prompt Applying runtime defaults for current desktop build
INSERT INTO RABAEV.RRL_VERSIONS (VERSION, ALLOW) VALUES ('xp12', 1);

INSERT INTO RABAEV.RRL_CONSTANTS (NAME, VALUE) VALUES ('EXT_BASE_CONNECTION_STRING', 'Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)));User ID=SUPERMAG;Password=SUPERMAG');
INSERT INTO RABAEV.RRL_CONSTANTS (NAME, VALUE) VALUES ('load_logopar_from_supermag', '0');
INSERT INTO RABAEV.RRL_CONSTANTS (NAME, VALUE) VALUES ('storeloc', '1');

INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('A----', '3', 1);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('B----', '4', 2);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('C----', '1', 3);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('D----', '7', 4);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('E----', '5', 5);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('M----', '2', 6);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('O----', '6', 7);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('R----', '10', 8);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('T----', '12', 9);
INSERT INTO RABAEV.RRL_WARE_MASKS (WARE_MASK, WARE_MASK_IDS, ORD_ID) VALUES ('V----', '8', 10);

MERGE INTO RABAEV.RUSERS tgt
USING (
  SELECT 'admin' AS ID,
         'Administrator' AS NAME,
         0 AS PRAVO_INVENTORY_EDIT,
         1 AS PRAVO_CHECK_ORDER,
         0 AS PRAVO_LIGHT_INVENTORY_CHECK,
         0 AS DELETED,
         1 AS PRAVO_RAZVOZ_ZAYAVOK,
         CAST(NULL AS VARCHAR2(50)) AS WMSUSER_ID,
         0 AS PRAVO_EAN_PRODUCT_CHANGE,
         0 AS PRAVO_KARSHIK,
         1 AS WARE_ID,
         'admin' AS PASS,
         1 AS PRAVO_ADMIN_LOGIN,
         CAST(NULL AS VARCHAR2(255)) AS SMFILEPATH,
         CAST(NULL AS VARCHAR2(255)) AS IP_SERVER_PRINT,
         'GLOBAL_ADMIN' AS USER_GROUP,
         CAST(NULL AS VARCHAR2(50)) AS SMENA
  FROM dual
) src
ON (tgt.ID = src.ID)
WHEN MATCHED THEN UPDATE SET
  tgt.NAME = src.NAME,
  tgt.PRAVO_INVENTORY_EDIT = src.PRAVO_INVENTORY_EDIT,
  tgt.PRAVO_CHECK_ORDER = src.PRAVO_CHECK_ORDER,
  tgt.PRAVO_LIGHT_INVENTORY_CHECK = src.PRAVO_LIGHT_INVENTORY_CHECK,
  tgt.DELETED = src.DELETED,
  tgt.PRAVO_RAZVOZ_ZAYAVOK = src.PRAVO_RAZVOZ_ZAYAVOK,
  tgt.WMSUSER_ID = src.WMSUSER_ID,
  tgt.PRAVO_EAN_PRODUCT_CHANGE = src.PRAVO_EAN_PRODUCT_CHANGE,
  tgt.PRAVO_KARSHIK = src.PRAVO_KARSHIK,
  tgt.WARE_ID = src.WARE_ID,
  tgt.PASS = src.PASS,
  tgt.PRAVO_ADMIN_LOGIN = src.PRAVO_ADMIN_LOGIN,
  tgt.SMFILEPATH = src.SMFILEPATH,
  tgt.IP_SERVER_PRINT = src.IP_SERVER_PRINT,
  tgt.USER_GROUP = src.USER_GROUP,
  tgt.SMENA = src.SMENA
WHEN NOT MATCHED THEN INSERT
  (ID, NAME, PRAVO_INVENTORY_EDIT, PRAVO_CHECK_ORDER, PRAVO_LIGHT_INVENTORY_CHECK, DELETED,
   PRAVO_RAZVOZ_ZAYAVOK, WMSUSER_ID, PRAVO_EAN_PRODUCT_CHANGE, PRAVO_KARSHIK, WARE_ID, PASS,
   PRAVO_ADMIN_LOGIN, SMFILEPATH, IP_SERVER_PRINT, USER_GROUP, SMENA)
VALUES
  (src.ID, src.NAME, src.PRAVO_INVENTORY_EDIT, src.PRAVO_CHECK_ORDER, src.PRAVO_LIGHT_INVENTORY_CHECK, src.DELETED,
   src.PRAVO_RAZVOZ_ZAYAVOK, src.WMSUSER_ID, src.PRAVO_EAN_PRODUCT_CHANGE, src.PRAVO_KARSHIK, src.WARE_ID, src.PASS,
   src.PRAVO_ADMIN_LOGIN, src.SMFILEPATH, src.IP_SERVER_PRINT, src.USER_GROUP, src.SMENA);

COMMIT;
prompt Master seed data loaded successfully
