-- Migration 058 — Push subscriptions table
-- Sprint 106: Browser Push API (VAPID)
-- 2026-05-29

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE RABAEV.RRL_PUSH_SUBSCRIPTIONS (
      ID          NUMBER(15) PRIMARY KEY,
      USER_ID     VARCHAR2(50) NOT NULL,
      ENDPOINT    VARCHAR2(500) NOT NULL,
      AUTH        VARCHAR2(200),
      P256DH      VARCHAR2(200),
      CREATED_AT  DATE DEFAULT SYSDATE,
      ACTIVE      NUMBER(1) DEFAULT 1
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE RABAEV.SEQ_PUSH_SUB START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Migration 059 — Notification settings
-- Sprint 107: Email notifications
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE RABAEV.RRL_NOTIFICATION_SETTINGS (
      ID          NUMBER(15) PRIMARY KEY,
      USER_ID     VARCHAR2(50) NOT NULL UNIQUE,
      EMAIL       VARCHAR2(200),
      EVENTS_JSON CLOB,
      ENABLED     NUMBER(1) DEFAULT 1,
      UPDATED_AT  DATE DEFAULT SYSDATE
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE RABAEV.SEQ_NOTIF_SETTINGS START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
